loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [{compId:"ID_title",
							x:2,
							y:1, 
							width:438,
							height:17,
							size:14,
							textAlign:"center"}];
							
	var commonImages = [];
							
	var graphics_slide = [];
	
	var slide_1_type = "IMAGE";
	var slide_1_images = [{name:"11_3_4_3_A.png",
							x:3,
							y:59, 
							width:430,
							height:287.05,
							type:""}];								
	var slide_1_texts = [	{compId:"static_txt01",
							bodyText:"<table width='374' border='0' cellspacing='0' cellpadding='0'> <tr> <td colspan='6'>R3<strong>#show cdp neighbors </strong></td> </tr> <tr> <td colspan='6'>&nbsp;</td> </tr> <tr> <td colspan='6'><table width='100%' border='0' cellspacing='0' cellpadding='0'> <tr> <td class='wide';>Capability Codes:</td> <td>R - Router, T - Trans Bridge,</td> </tr> <tr> <td>&nbsp;</td> <td>B - Source Route Bridge</td> </tr> <tr> <td>&nbsp;</td> <td>S - Switch, H - Host, I - IGMP,</td> </tr> <tr> <td>&nbsp;</td> <td>r - Repeater, P - Phone</td> </tr> </table></td> </tr> <tr> <td colspan='6'>&nbsp;</td> </tr> <tr> <td width='70'>Device ID</td> <td width='105'> Local Intrfce </td> <td width='54'>Holdtme </td> <td width='70'>Capability</td> <td width='65'>Platform</td> <td width='78'>Port ID</td> </tr> <tr> <td>S3 </td> <td> Fas 0/0</td> <td>151 </td> <td>S I</td> <td>WS-C2950</td> <td>Fas 0/6</td> </tr> <tr> <td>R2</td> <td>Ser 0/0/1 </td> <td>125</td> <td>R</td> <td>1841</td> <td>Ser 0/0/1</td> </tr> <tr> <td colspan='6'>&nbsp;</td> </tr> <tr> <td colspan='6'>R3<strong>#show cdp neighbors detail</strong></td> </tr> <tr> <td colspan='6'>Device ID: R2</td> </tr> <tr> <td colspan='6'>Entry address(es): </td> </tr> <tr> <td colspan='6'>IP address : 192.168.1.2</td> </tr> <tr> <td colspan='6'>Platform: Cisco 1841, Capabilities: Router Switch IGMP<br /> Interface: Serial0/0/1, Port ID (outgoing port): Serial0/0/1<br /> Holdtime : 161 sec</td> </tr> <tr> <td colspan='6'>&nbsp;</td> </tr> <tr> <td colspan='6'>Version :</td> </tr> <tr> <td colspan='6'>Cisco IOS Software, 1841 Software (C1841-ADVIPSERVICESK9-M),<br /> Version 12.4(10b), RELEASE SOFTWARE (fc3)<br /> Technical Support: http://www.cisco.com/techsupport<br /> Copyright (c) 1986-2007 by Cisco Systems, Inc.<br /> Compiled Fri 19-Jan-07 15:15 by prod_rel_team</td> </tr> <tr> <td colspan='6'>&nbsp;</td> </tr> <tr> <td colspan='6'>advertisement version: 2</td> </tr> <tr> <td colspan='6'>VTP Management Domain: ''</td> </tr> <tr> <td colspan='6'>&nbsp;</td> </tr> <tr> <td colspan='6'>-------------------------------</td> </tr> <tr> <td colspan='6'>Device ID: S3</td> </tr> <tr> <td colspan='6'>Entry address(es): </td> </tr> <tr> <td colspan='6'>Platform: cisco WS-C2950-24, Capabilities: Switch IGMP<br /> Interface: FastEthernet0/0, Port ID (outgoing port): FastEthernet0/11<br /> Holdtime : 148 sec</td> </tr> <tr> <td colspan='6'>&nbsp;</td> </tr> <tr> <td colspan='6'>Version :</td> </tr> <tr> <td colspan='6'>Cisco Internetwork Operating System Software<br /> IOS (tm) C2950 Software (C2950-I6Q4L2-M), Version 12.1(9)EA1, <br /> RELEASE SOFTWARE (fc1)<br /> Copyright (c) 1986-2002 by cisco Systems, Inc.<br /> Compiled Wed 24-Apr-02 06:57 by antonino</td> </tr> <tr> <td colspan='6'>&nbsp;</td> </tr> <tr> <td colspan='6'>advertisement version: 2</td> </tr> <tr> <td colspan='6'>Protocol Hello: OUI=0x00000C, Protocol ID=0x0112; payload len=27, value=00000000FFFFFFFF0<br /> 10231FF000000000000000AB769F6C0FF0000<br /> VTP Management Domain: 'CCNA3'<br /> Duplex: full</td> </tr> <tr> <td colspan='6'>&nbsp;</td> </tr> <tr> <td colspan='6'>R3#</td> </tr></table>",
							x:28,
							y:62+9, 
							width:394,
							height:258,
							size:10,
							textAlign:"left",}];							
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts};
							
	
	var slide_2_type = "IMAGE";
	var slide_2_images = [{name:"11_3_4_3_B.png",
							x:-5,
							y:74.55, 
							width:444.55,
							height:253.9,
							type:""}];								
	var slide_2_texts = [	{compId:"static_txt001",
							bodyText:"<b>PC2</b>",
							x:208.25+9,
							y:78.55+1, 
							width:25.3,
							height:17,
							size:11,
							color:"white",
							textAlign:"left"},
							{compId:"static_txt02",
							bodyText:"<b>172.16.1.0/24</b>",
							x:119.05+8,
							y:152.05+3, 
							width:72.95,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt03",
							bodyText:"Fa0/0",
							x:186.95+8,
							y:188.55+2, 
							width:32.05,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt04",
							bodyText:".1",
							x:219+8,
							y:190.05+1, 
							width:21.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt05",
							bodyText:"S0/0/0",
							x:156.5+7,
							y:228.85+2, 
							width:44.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt06",
							bodyText:"S0/0/1<br/>DCE",
							x:243.25+1,
							y:228.35+1, 
							width:44.45,
							height:31,
							size:11,
							textAlign:"center"},
							{compId:"static_txt07",
							bodyText:"<b>R2</b>",
							x:208.35+9,
							y:224.15, 
							width:17.85,
							height:17,
							size:11,
							color:"white",
							textAlign:"center"},
							{compId:"static_txt08",
							bodyText:".2",
							x:196.05+8,
							y:241.05, 
							width:21.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt09",
							bodyText:".2",
							x:217.55+6,
							y:241.05, 
							width:21.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt10",
							bodyText:"<b>172.16.2.0/24</b>",
							x:103.55+11,
							y:259.05, 
							width:76.95,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt11",
							bodyText:"<b>192.168.1.0/24</b>",
							x:262.05+6,
							y:259.05, 
							width:76.95,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt12",
							bodyText:".1",
							x:158.05+6,
							y:273+1, 
							width:21.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt13",
							bodyText:".1",
							x:266.55+7,
							y:273+1, 
							width:21.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt14",
							bodyText:"S0/0/0<br/>DCE",
							x:180.25+12,
							y:275.35+1, 
							width:44.45,
							height:31,
							size:11,
							textAlign:"left"},
							{compId:"static_txt15",
							bodyText:"S0/0/1",
							x:220.4+7,
							y:275.35, 
							width:44.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt16",
							bodyText:"Fa0/0",
							x:106.45+6,
							y:291.55, 
							width:32.05,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt17",
							bodyText:"Fa0/0",
							x:297+7,
							y:292.55, 
							width:32.05,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt18",
							bodyText:".1",
							x:120.05+8,
							y:306.9+2, 
							width:21.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt19",
							bodyText:".1",
							x:291.55+8,
							y:307.9, 
							width:21.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt20",
							bodyText:"<b>PC1</b>",
							x:4.8+7,
							y:295.5+1, 
							width:25.3,
							height:17,
							size:11,
							color:"white",
							textAlign:"center"},
							{compId:"static_txt21",
							bodyText:"<b>PC3</b>",
							x:405.3+6,
							y:295.5+1, 
							width:25.3,
							height:17,
							size:11,
							color:"white",
							textAlign:"center"},
							{compId:"static_txt22",
							bodyText:"<b>R1</b>",
							x:152+6,
							y:306.75, 
							width:17.85,
							height:17,
							size:11,
							color:"white",
							textAlign:"center"},
							{compId:"static_txt23",
							bodyText:"<b>R3</b>",
							x:267.6+6,
							y:306.75, 
							width:17.85,
							height:17,
							size:11,
							color:"white",
							textAlign:"center"},
							{compId:"static_txt24",
							bodyText:"<b>172.16.3.0/24</b>",
							x:41+7,
							y:318.55, 
							width:76.95,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"static_txt25",
							bodyText:"<b>192.168.2.0/24</b>",
							x:309.45+8,
							y:318.55, 
							width:76.95,
							height:17,
							size:11,
							textAlign:"center"}
							];							
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts};
							
											
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			images:commonImages,
			graphics:graphics_slide,
			slideObject:slides};
	
}
