loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js"); 

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 772;
var STAGE_HEIGHT = 400;
var TYPE = "MULTI_BAR";
var isDD = true;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	var common_images = [];
	
	var slide_1_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_s1_drag01",
						x:116.5,
						y:228.55,
						width:68.45,
						height:44.25,
						size:11,
						tag:8,
						textAlign:"center"},     
					{compId:"ID_s1_drag02",
						x:217.15,
						y:228.55,
						width:68.45,
						height:44.25,
						size:11,
						tag:6,
						textAlign:"center"},
					{compId:"ID_s1_drag03",
						x:317.85,
						y:228.55,
						width:68.45,
						height:44.25,
						size:11,
						tag:1,
						textAlign:"center"},
					{compId:"ID_s1_drag04",
						x:418.6,
						y:228.55,
						width:68.45,
						height:44.25,
						size:11,
						tag:3,
						textAlign:"center"},
					{compId:"ID_s1_drag05",
						x:519.25,
						y:228.55,
						width:68.45,
						height:44.25,
						size:11,
						tag:7,
						textAlign:"center"},
					{compId:"ID_s1_drag06",
						x:116.5,
						y:283.7,
						width:68.45,
						height:44.25,
						size:11,
						tag:2,
						textAlign:"center"},     
					{compId:"ID_s1_drag07",
						x:217.15,
						y:283.7,
						width:68.45,
						height:44.25,
						size:11,
						tag:5,
						textAlign:"center"},
					{compId:"ID_s1_drag08",
						x:317.85,
						y:283.7,
						width:68.45,
						height:44.25,
						size:11,
						tag:10,
						textAlign:"center"},
					{compId:"ID_s1_drag09",
						x:418.6,
						y:283.7,
						width:68.45,
						height:44.25,
						size:11,
						tag:9,
						textAlign:"center"},
					{compId:"ID_s1_drag10",
						x:519.25,
						y:283.7,
						width:68.45,
						height:44.25,
						size:11,
						tag:4,
						textAlign:"center"}];
    var dropBox = [{compId:"a1_dt",
						x:154.35,
						y:59.2,
						width:64.25,
						height:44.25,
						size:11,
						answer:1,
						textAlign:"center"},
					{compId:"a2_dt",
						x:339.2,
						y:59.2,
						width:64.25,
						height:44.25,
						answer:2,
						textAlign:"center"},
					{compId:"a3_dt",
						x:559-29,
						y:59.2,
						width:64.25,
						height:44.25,
						size:11,
						answer:3,
						textAlign:"center"},
					{compId:"a4_dt",
						x:44.15-29,
						y:158.8,
						width:64.25,
						height:44.25,
						size:11,
						answer:4,
						textAlign:"center"},
					{compId:"a5_dt",
						x:131.75-29,
						y:158.8,
						width:64.25,
						height:44.25,
						answer:5,
						textAlign:"center"},
					{compId:"a6_dt",
						x:216.85-29,
						y:158.8,
						width:64.25,
						height:44.25,
						size:11,
						answer:6,
						textAlign:"center"},
					{compId:"a7_dt",
						x:302.75-29,
						y:158.8,
						width:64.25,
						height:44.25,
						answer:7,
						textAlign:"center"},
					{compId:"a8_dt",
						x:374.3,
						y:158.8,
						width:64.25,
						height:44.25,
						size:11,
						answer:8,
						textAlign:"center"},
					{compId:"a9_dt",
						x:497.95,
						y:158.8,
						width:64.25,
						height:44.25,
						answer:9,
						textAlign:"center"},
					{compId:"a10_dt",
						x:627.3,
						y:158.8,
						width:64.25,
						height:44.25,
						answer:10,
						textAlign:"center"}];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_1_texts = [{compId:"ID_s1_inst",
							x:30,
							y:1,
							width:375.9,
							height:17,
							size:11,
							textAlign:"left"},
						{compId:"ID_s1_txt06",
							x:225.5,
							y:106.4,
							width:171,
							height:17,
							size:11,
							textAlign:"center"},
						{compId:"ID_s1_txt07",
							x:400.3,
							y:106.4,
							width:194,
							height:17,
							size:11,
							textAlign:"center"},
						{compId:"ID_s1_txt01",
							x:396.35,
							y:130.9,
							width:339,
							height:17,
							size:11,
							textAlign:"left"},
						{compId:"ID_s1_txt02",
							x:396.35,
							y:177.1,
							width:339,
							height:17,
							size:11,
							textAlign:"left"},
						{compId:"ID_s1_txt03",
							x:396.35,
							y:234.3,
							width:339,
							height:17,
							size:11,
							textAlign:"left"},
						{compId:"ID_s1_txt04",
							x:396.35,
							y:274.5,
							width:339,
							height:17,
							size:11,
							textAlign:"left"},
						{compId:"ID_s1_txt05",
							x:396.35,
							y:330.7,
							width:339,
							height:17,
							size:11,
							textAlign:"left"}];
							
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_1_images = [{name:"media_9.1.2.3.jpg",
							x:0,
							y:0, 
							width:727.95,
							height:228,
							type:""},
							];
    var submit_buttons = [{compId:"ID_s1_CHECK",
								x:550,
								y:363,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"},
							{compId:"ID_s1_RESET",
								x:650,
								y:363,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
							x:276.9,
							y:227.4,
							width:200,
							height:125,
							size:11,
							image:"../../../common/images/feedback4.png",
							textAlign:"left"}];
    var instobj = {ansType:"many-one",clue:1};
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_1_texts,
							slideImages:slide_1_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
	
/* Slide 2 */
	var slide_2_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
						overSkinImage:"../../../common/images/drop_normal.png",
						dropNormalSkinImage:"drop_normal.png",
						normalTextStyle:'#FFFFFF',
						overTextStyle:'#006699',
						cornorRadius:5,
						selected:0};

   var buttons = [{compId:"ID_s2_drag01",
						x:80,
						y:108,
						width:140,
						height:36,
						size:11,
						tag:1,
						color:"#393536",
						textAlign:"center"},     
					{compId:"ID_s2_drag02",
						x:80,
						y:156.25,
						width:140,
						height:36,
						size:11,
						tag:5,
						textAlign:"center"},
					{compId:"ID_s2_drag03",
						x:80,
						y:204.5,
						width:140,
						height:36,
						size:11,
						tag:4,
						textAlign:"center"},
					{compId:"ID_s2_drag04",
						x:80,
						y:252.75,
						width:140,
						height:36,
						size:11,
						tag:2,
						textAlign:"center"},
					{compId:"ID_s2_drag05",
						x:80,
						y:301,
						width:140,
						height:36,
						size:11,
						tag:3,
						textAlign:"center"}];
						
    var dropBox = [{compId:"a1_dt",
						x:252,
						y:108,
						width:140,
						height:36,
						size:11,
						answer:1,
						textAlign:"center"},
					{compId:"a2_dt",
						x:252,
						y:156.25,
						width:140,
						height:36,
						size:11,
						answer:2,
						textAlign:"center"},
					{compId:"a3_dt",
						x:252,
						y:204.5,
						width:140,
						height:36,
						size:11,
						answer:3,
						textAlign:"center"},
					{compId:"a4_dt",
						x:252,
						y:252.75,
						width:140,
						height:36,
						size:11,
						answer:4,
						textAlign:"center"},
					{compId:"a5_dt",
						x:252,
						y:301,
						width:140,
						height:36,
						size:11,
						answer:5,
						textAlign:"center"}];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_2_texts = [{compId:"ID_s2_inst",
								x:30,
								y:1,
								width:706.05,
								height:17,
								size:11,
								textAlign:"left"},
							{compId:"ID_s2_txt01",
								x:398.35,
								y:117.9,
								width:312.1,
								height:17,
								size:11,
								textAlign:"left"},
							{compId:"ID_s2_txt02",
								x:398.35,
								y:166.1,
								width:312.1,
								height:17,
								size:11,
								textAlign:"left"},
							{compId:"ID_s2_txt03",
								x:398.35,
								y:214.3,
								width:312.1,
								height:17,
								size:11,
								textAlign:"left"},
							{compId:"ID_s2_txt04",
								x:398.35,
								y:262.5,
								width:312.1,
								height:17,
								size:11,
								textAlign:"left"},
							{compId:"ID_s2_txt05",
								x:398.35,
								y:310.7,
								width:312.1,
								height:17,
								size:11,
								textAlign:"left"}];
								
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_2_images = [{name:"bg.png",
							x:230,
							y:78.1, 
							width:489,
							height:269.9,
							type:""},
							];
    var submit_buttons = [{compId:"ID_s2_CHECK",
								x:550,
								y:363,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"},
							{compId:"ID_s2_RESET",
								x:650,
								y:363,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"}
								];
    var feedbackObj = [{compId:"ID_FEEDBACK",
							x:22,
							y:105,
							width:170,
							height:98,
							size:11,
							image:"../../../common/images/feedback2.png",
							textAlign:"left"}];
    var instobj = {ansType:"many-one",clue:1};
	
 var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_2_texts,
							slideImages:slide_2_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
			
	
															
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
		    images:common_images,
			slideObject:slides,
			buttonBarPos:{x:700}};
	
}



