loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	
	var slide_1_type = "IMAGE";
	var slide_1_images = [{name:"4_2_1_4.jpg",
							x:33.6,
							y:84.3, 
							width:382.7,
							height:211.4,
							type:""}];								
	var slide_1_texts = [{compId:"ID_s1_txt01",
							x:358.6,
							y:139.2, 
							width:60,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s1_txt02",
							x:135-23,
							y:243+12, 
							width:222.25,
							height:124.15,
							size:11,
							textAlign:"center",
							expand:"down",
							rotation:-27},
							{compId:"ID_s1_txt05",
							x:119,
							y:210, 
							width:222.25,
							height:124.15,
							size:11,
							textAlign:"center",
							expand:"down",
							rotation:-27},
							{compId:"ID_s1_txt07",
							x:341,
							y:69.05, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up"},
							{compId:"ID_s1_txt04",
							x:7.15,
							y:297.4, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s1_txt09",
							x:0,
							y:365.8, 
							width:435.1,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},];							
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts};
							
	var slide_2_type = "IMAGE";
	var slide_2_images = [{name:"4_2_1_4A.jpg",
							x:35.05,
							y:2, 
							width:400,
							height:368,
							type:""}];								
	var slide_2_texts = [{compId:"ID_s2_txt11",
							x:3 ,
							y:243.05,
							size:11,
							textAlign:"center"},
							{compId:"ID_s2_txt01",
							x:20.55,
							y:373.8, 
							width:85.9,
							height:17,
							size:11,
							textAlign:"center",
							expand:"right"},
							{compId:"ID_s2_txt02",
							x:371.4+25,
							y:373.8, 
							width:66.95,
							height:17,
							size:11,
							textAlign:"center",
							expand:"left"},
							{compId:"ID_s2_txt03",
							x:206.1,
							y:207.75, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s2_txt04",
							x:32.4,
							y:74.2, 
							width:109,
							height:17,
							size:11,
							textAlign:"right",
							expand:"down"},
							{compId:"ID_s2_txt05",
							x:335.45+17,
							y:74.2, 
							width:86.45,
							height:17,
							size:11,
							textAlign:"left",
							expand:"down"},
							{compId:"ID_s2_txt06",
							x:212.1,
							y:31.05, 
							width:67,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s2_txt07",
							x:348.05,
							y:177.1, 
							width:95.5,
							height:17,
							size:11,
							textAlign:"left",
							expand:"up+down"},
							{compId:"ID_s2_txt09",
							x:31.45,
							y:56.2, 
							width:108.95,
							height:17,
							size:11,
							textAlign:"right",
							expand:"up"},
							{compId:"ID_s2_txt10",
							x:335.45+17,
							y:56.2, 
							width:88.4,
							height:17,
							size:11,
							textAlign:"left",
							expand:"up"},
							{compId:"ID_s2_txt12",
							x:45.05+36,
							y:177.1, 
							width:100,
							height:17,
							size:11,
							textAlign:"right",
							expand:"up+down"},];							
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts};
	
							
											
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			slideObject:slides};
	
}