//loadScript("../../../common/scripts/templates/slide/ImageSlideNew.js");
loadScript("../../../common/scripts/swfobject.js", registerSWF);

function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}

var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
    var template_type = "IMAGE";

    var slide_images = [{name:"7_2_3_3.png",
						x:11,
						y:25,
						width:454,
						height:352,
						type:""}];

    var slide_texts = [{compId:"ID_txt01",
							x:349.3,
							y:40.85, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_txt02",
							x:349.3,
							y:101.85, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_txt03",
							x:349.3,
							y:156, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_txt04",
							x:349.3,
							y:218.75, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_txt05",
							x:349.3,
							y:278.5, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_txt06",
							x:349.3,
							y:348.25, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_txt07",
							x:22,
							y:187.95, 
							width:150,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"}
							];
							
	var graphic_slide = [{x:19,
							y:179.45,
							width:150.4,
							height:45.1,
							color:"#DBECDA",
							thickness:0,
							stroke:0,
							corner:0,
							type:"rectangle"},
							{x:316.15,
							y:26,
							width:150.4,
							height:45.1,
							color:"#DBECDA",
							thickness:0,
							stroke:0,
							corner:0,
							type:"rectangle"},
							{x:316.15,
							y:87.3,
							width:150.4,
							height:45.1,
							color:"#DBECDA",
							thickness:0,
							stroke:0,
							corner:0,
							type:"rectangle"},
							{x:316.15,
							y:148.65,
							width:150.4,
							height:45.1,
							color:"#DBECDA",
							thickness:0,
							stroke:0,
							corner:0,
							type:"rectangle"},
							{x:316.15,
							y:209.95,
							width:150.4,
							height:45.1,
							color:"#DBECDA",
							thickness:0,
							stroke:0,
							corner:0,
							type:"rectangle"},
							{x:316.15,
							y:271.3,
							width:150.4,
							height:45.1,
							color:"#DBECDA",
							thickness:0,
							stroke:0,
							corner:0,
							type:"rectangle"},
							{x:316.15,
							y:332.6,
							width:150.4,
							height:45.1,
							color:"#DBECDA",
							thickness:0,
							stroke:0,
							corner:0,
							type:"rectangle"},];

    var slide_object = {images:slide_images,
        texts:slide_texts,
		graphics:graphic_slide};

    return {templateType:template_type,
        slideObject:slide_object};

}

