loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js"); 

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 760;
var STAGE_HEIGHT = 400;
var TYPE = "MULTI_BAR";
var isDD = true;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	
	var slide_1_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal_new.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_s1_drag04",
		x:145,
        y:135,
        width:110,
        height:20,
        size:11,
	    textAlign:"left",
		color:"#585556",
		tag:4
		}, 
		{compId:"ID_s1_drag05",
		x:145,
        y:175,
        width:110,
        height:20,
        size:11,
	    textAlign:"left",
		color:"#585556",
		tag:2,},		
		{compId:"ID_s1_drag02",
		x:145,
        y:215,
        width:110,
        height:20,
        size:11,
	    textAlign:"left",
		color:"#585556",
		tag:2,}, 
		{compId:"ID_s1_drag01",
		x:145,
        y:255,
        width:110,
        height:20,
        size:11,
	    textAlign:"left",
		color:"#585556",
		tag:1,},
		{compId:"ID_s1_drag03",
		x:145,
        y:295,
        width:110,
        height:20,
        size:11,
	    textAlign:"left",
		color:"#585556",
		tag:3,}  
        ];
    var dropBox = [{compId:"a1_dt",
        x:552.30,
        y:127.30,
        width:110,
        height:20,
        size:11,
        answer:1,
        textAlign:"center"},
		{compId:"a1_dt2",
        x:595.30,
        y:171.30,
        width:110,
        height:20,
        size:11,
        answer:2,
        textAlign:"center"},
		{compId:"a1_dt3",
        x:595.30,
        y:256.6,
        width:110,
        height:20,
        size:11,
        answer:3,
        textAlign:"center"},
		{compId:"a1_dt4",
        x:595.30,
        y:277.9,
        width:110,
        height:20,
        size:11,
        answer:4,
        textAlign:"center"},
		{compId:"a1_dt5",
        x:595.30,
        y:300.2,
        width:110,
        height:20,
        size:11,
        answer:2,
        textAlign:"center"},
         ];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_1_texts = [
		{compId:"ID_s1_title",
        x:100,
        y:2,
        width:250,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt01A",
        x:385,
        y:104,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt01B",
        x:385,
        y:124,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt01C",
        x:385,
        y:144,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt02",
        x:368,
        y:204,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt03A",
        x:380,
        y:255,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt03B",
        x:380,
        y:275,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt03C",
        x:380,
        y:295,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt04",
        x:664,
        y:130,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt05A",
        x:560,
        y:175,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt05B",
        x:560,
        y:260.3,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt05C",
        x:560,
        y:280.6,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s1_txt05D",
        x:560,
        y:300.9,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},	
		{compId:"ID_s1_txt06",
        x:402,
        y:326,
        width:200,
        height:17,
        size:11,
        textAlign:"center"},
		{compId:"ID_s1_drag_header",
        x:57.45+144-55,
        y:108.3,
        width:110,
        height:20,
        size:11,
        textAlign:"center"},
		{compId:"ID_s1_drop_header",
        x:625.1-271,
        y:118.05-94,
        width:293,
        height:17,
        size:11,
		expand:"up+down",
        textAlign:"center"}		
	];
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_1_images = [{compId:"ID_image01",
        name:"5_2_1_9_A.png",
        x:380.35,
        y:50,
        width:235,
        height:271,
        size:11,
        textAlign:"left"},
		{compId:"ID_image01",
        name:"bg.png",
        x:137,
        y:131.3,
        width:126,
        height:187,
        size:11,
        textAlign:"left"}
		];
    var submit_buttons = [{compId:"ID_s1_CHECK",
								x:534,
								y:357,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"},
							{compId:"ID_s1_RESET",
									x:639,
									y:357,
									width:80,
									height:23,
									size:11,
									normalSkinImage:"../../../common/images/btn_normal.png",
									textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:15,
        y:117,
        width:225,
        height:121,
        size:11,
        image:"../../../common/images/feedback2.png",
        textAlign:"center"}];
   var instobj = {ansType:"many-one"};
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_1_texts,
							slideImages:slide_1_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
	
	/* Slide 2 */
	var slide_2_type = "DRAG_DROP";
   var slide_2_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal_new.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_s2_drag01",
		x:145,
        y:135,
        width:110,
        height:20,
        size:11,
	    textAlign:"left",
		color:"#585556",
		tag:1}, 
		{compId:"ID_s2_drag03",
		x:145,
        y:175,
        width:110,
        height:20,
        size:11,
	    textAlign:"left",
		color:"#585556",
		tag:1},		
		{compId:"ID_s2_drag02",
		x:145,
        y:215,
        width:110,
        height:20,
        size:11,
	    textAlign:"left",
		color:"#585556",
		tag:2}, 
		{compId:"ID_s2_drag04",
		x:145,
        y:255,
        width:110,
        height:20,
        size:11,
	    textAlign:"left",
		color:"#585556",
		tag:2},
	];
    var dropBox = [{compId:"a1_dt",
        x:552.30,
        y:117.30,
        width:110,
        height:20,
        size:11,
        answer:1,
        textAlign:"center"},
		{compId:"a1_dt2",
        x:581.30,
        y:168.30,
        width:110,
        height:20,
        size:11,
        answer:2,
        textAlign:"center"},
		{compId:"a1_dt3",
        x:581.30,
        y:207.30,
        width:110,
        height:20,
        size:11,
        answer:1,
        textAlign:"center"},
		{compId:"a1_dt4",
        x:552.30,
        y:297.30,
        width:110,
        height:20,
        size:11,
        answer:2,
        textAlign:"center"}];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_2_texts = [
		{compId:"ID_s2_title",
        x:100,
        y:2,
        width:250,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_txt01",
        x:395,
        y:104,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_txt02",
        x:368,
        y:200,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_txt03",
        x:375,
        y:238,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_txt04",
        x:388,
        y:273,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_txt05",
        x:664,
        y:120,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_txt06",
        x:553,
        y:171,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_txt07",
        x:553,
        y:211,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_txt08",
        x:664,
        y:300,
        width:100,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_drag_header",
        x:167.45,
        y:106.3,
        width:110,
        height:20,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_drop_header",
        x:377.95,
        y:24.6,
        width:285,
        height:17,
        size:11,
        textAlign:"left"}
		];
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_2_images = [{compId:"ID_image01",
        name:"5_2_1_9_B.png",
        x:380.35,
        y:50,
        width:235,
        height:271,
        size:11,
        textAlign:"left"},
		{compId:"ID_image01",
        name:"bg.png",
        x:137,
        y:126,
        width:127,
        height:157.05,
        size:11,
        textAlign:"left"}
		];
    var submit_buttons = [{compId:"ID_s1_CHECK",
								x:534,
								y:357,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"},
							{compId:"ID_s1_RESET",
								x:639,
								y:357,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"}
    							];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:15,
        y:117,
        width:225,
        height:121,
        size:11,
        image:"../../../common/images/feedback2.png",
        textAlign:"center"}];
   var instobj = {ansType:"many-one"};
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_2_texts,
							slideImages:slide_2_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
			
	
															
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			slideObject:slides,
			buttonBarPos:{x:686}};
	
}



