loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/TableSlideNew.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "TABLE";
	
	var slide_1_images =[{name:"11_3_1_2.jpg",
							x:3.3,
							y:136.9,
							width:464,
							height:109,
							type:""}];
	
	var slide_1_tables = [];				
	var slide_1_texts = [{compId:"pc1",
							bodyText:'<b>PC1</b>',
							x:13+8,
							y:144,
							width:23,
							height:17,
							color:"#ffffff",
							size:10,
                        	textAlign:"center"},
							{compId:"pc2",
							bodyText:'<b>PC2</b>',
							x:13+7,
							y:144+72,
							width:23,
							height:17,
							color:"#ffffff",
							size:10,
                        	textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'.10',
							x:44,
							y:140,
							width:29.4,
							height:17,
							size:11,
                        	textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'.10',
							x:44,
							y:140+72,
							width:29.4,
							height:17,
							size:11,
                        	textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'<b>192.168.10.0/24</b>',
							x:53.05+15,
							y:130,
							width:95.7,
							height:17,
                            size:11,
							textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'<b>192.168.10.0/24</b>',
							x:50.05+15,
							y:243,
							width:95.7,
							height:17,
                            size:11,
							textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'G0/0<br/>.1',
							x:134.65,
							y:149.15,
							width:30.8,
							height:17,
                            size:11,
							textAlign:"right"},
							{compId:"staticTxt",
							bodyText:'.1<br/>G0/1',
							x:134.65,
							y:202.9,
							width:30.8,
							height:17,
                            size:11,
							textAlign:"right"},
							{compId:"staticTxt",
							bodyText:'.225<br/>S0/0/0',
							x:189.95,
							y:190.85,
							width:38.2,
							height:17,
                            size:11,
							textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'.226',
							x:264,
							y:182.45,
							width:27.7,
							height:7.3,
                            size:11,
							textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'<b>209.165.200.224 /30</b>',
							x:169.05,
							y:161.6,
							width:101.9,
							height:13.5,
                            size:11,
							textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'.1',
							x:318.75,
							y:173.45,
							width:22.55,
							height:17,
                            size:11,
							textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'.1',
							x:318.05,
							y:209.1,
							width:22.55,
							height:17,
                            size:11,
							textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'<b>10.1.1.0/24</b>',
							x:341.95,
							y:130.25,
							width:83.4,
							height:17,
                            size:11,
							textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'<b>10.1.2.0/24</b>',
							x:340.3,
							y:240.75,
							width:83.4,
							height:17,
                            size:11,
							textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'.10',
							x:415.85,
							y:139.65,
							width:22.55,
							height:17,
                            size:11,
							textAlign:"center"},
							{compId:"staticTxt",
							bodyText:'.10',
							x:415.85,
							y:208.65,
							width:22.55,
							height:17,
                            size:11,
							textAlign:"center"},
							{compId:"r1",
							bodyText:'<b>R1</b>',
							x:153.25+9,
							y:153.25+41,
							width:31,
							height:17,
                            size:10,
							color:"#ffffff",
							textAlign:"center"},
							{compId:"r2",
							bodyText:'<b>R2</b>',
							x:283.15+9,
							y:153.25+41,
							width:31,
							height:17,
                            size:10,
							color:"#ffffff",
							textAlign:"center"},
							];						
	var graphics_slide = [];			
	return {templateType:template_type,
			tables:slide_1_tables,
			texts:slide_1_texts,
			images:slide_1_images,
			graphics:graphics_slide};
	
}
