
loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	
	var slide_1_type = "IMAGE";
	var slide_1_images = [{name:"7_2_1_2.jpg",
							x:42.35,
							y:64.35, 
							width:379.1,
							height:247.25,
							type:""}];								
	var slide_1_texts = [{compId:"ID_s1_title",
							x:10,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s1_txt01",
							x:65.85,
							y:196.85, 
							width:96.15,
							height:29,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s1_txt02",
							x:182,
							y:141.35, 
							width:108.35,
							height:29,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s1_txt03",
							x:161,
							y:245.35, 
							width:126.5,
							height:29,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s1_txt04",
							x:289.5,
							y:204.85, 
							width:121.9,
							height:29,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s1_txt05",
							bodyText:"<b>R1</b>",
							x:215.55,
							y:230.35, 
							width:17.4,
							height:17,
							size:10,
							color:"#ffffff",
							textAlign:"center"}];							
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts};
							
	
	var slide_2_type = "IMAGE";
	var slide_2_images = [{name:"7_2_1_2_A.jpg",
							x:0,
							y:52, 
							width:439.85,
							height:226.4,
							type:""}];								
	var slide_2_texts = [{compId:"ID_s2_title",
							x:10,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s2_txt01",
							x:305,
							y:221.85+15,  
							width:112,
							height:17,
							size:11,
							textAlign:"center",
							expand:"left+right"},
							{compId:"ID_s2_txt02",
							x:132.35,
							y:133.75+19, 
							width:112,
							height:17,
							size:11,
							textAlign:"left",
							expand:"right"},
							{compId:"ID_s2_txt03",
							x:189.4+6,
							y:133.75+21, 
							width:112,
							height:17,
							size:11,
							textAlign:"right",
							expand:"left"},
							{compId:"ID_s2_txt04",
							x:45.9,
							y:221.85+15, 
							width:112,
							height:17,
							size:11,
							textAlign:"left",
							expand:"right"},
							{compId:"ID_s2_txt05",
							x:158.05-19,
							y:84.9+22, 
							width:134,
							height:17,
							size:11,
							textAlign:"right",
							expand:"left"},
							{compId:"ID_s2_txt06",
							bodyText:"<b>Tunnel</b>",
							x:200.15,
							y:68.15+19, 
							width:43.8,
							height:17,
							size:10,
							color:"#ffffff",
							textAlign:"center"},
							{compId:"ID_s2_txt07",
							bodyText:"<b>R1</b>",
							x:107,
							y:158.55+24, 
							width:17.4,
							height:17,
							size:10,
							color:"#ffffff",
							textAlign:"center"},
							{compId:"ID_s2_txt08",
							bodyText:"<b>R2</b>",
							x:310,
							y:158.55+24, 
							width:17.4,
							height:17,
							size:10,
							color:"#ffffff",
							textAlign:"center"},
							{compId:"ID_s2_txt09",
							bodyText:"<b>PC1</b>",
							x:75,
							y:192.55+13, 
							width:24,
							height:17,
							size:10,
							color:"#ffffff",
							textAlign:"center"},
							{compId:"ID_s2_txt10",
							bodyText:"<b>PC2</b>",
							x:338,
							y:192.55+13, 
							width:24,
							height:17,
							size:10,
							color:"#ffffff",
							textAlign:"center"}];
							
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts};
	
	var slide_3_type = "IMAGE";
	var slide_3_images = [{name:"7_2_1_2_B.jpg",
							x:2.85,
							y:113.9, 
							width:434.05,
							height:114.1,
							type:""}];								
	var slide_3_texts = [{compId:"ID_s3_title",
							x:10,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s3_txt01",
							x:42.35,
							y:180.85, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s3_txt02",
							x:300,
							y:180.85, 
							width:104,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s3_txt03",
							x:168,
							y:201.5, 
							width:104,
							height:17,
							size:11,
							color:"#ffffff",
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s3_txt04",
							bodyText:"<b>PC1</b>",
							x:69,
							y:143.95, 
							width:39,
							height:17,
							size:10,
							color:"#ffffff",
							textAlign:"center"},
							{compId:"ID_s3_txt05",
							bodyText:"<b>PC2</b>",
							x:336,
							y:143.95, 
							width:24,
							height:17,
							size:10,
							color:"#ffffff",
							textAlign:"center"}];
							
	var slide_3_object = {templateType:slide_3_type,
							x:0,
							y:0,
							images:slide_3_images,
							texts:slide_3_texts};										
	var slides = [slide_1_object,slide_2_object,slide_3_object];
					
	return {templateType:template_type,
			textObject:commonTexts,
			slideObject:slides};
	
}
