loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js"); 

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 793;
var STAGE_HEIGHT = 400;
var TYPE = "MULTI_BAR";
var isDD = true;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [	];
	var common_images = [];
	
	var slide_1_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_sub3_DS",
		x:7.5,
        y:133.45,
        width:160,
        height:36.5,
        size:11,
		
        textAlign:"center",
		expand:"left"},     
        {compId:"ID_sub2_DS",
		x:7.5,
        y:179,
        width:160,
        height:36.5,
        size:11,
		
        textAlign:"center",
		expand:"left"}, 
		{compId:"ID_sub1_DS",
		x:7.5,
        y:224.55,
        width:160,
        height:36.5,
        size:11,
		
        textAlign:"center",
		expand:"left"}, 
		{compId:"ID_sub5_DS",
		x:7.5,
        y:270.1,
        width:160,
        height:36.5,
        size:11,
		
        textAlign:"center",
		expand:"left"}, 
	{compId:"ID_sub4_DS",
		x:7.5,
        y:315.65,
        width:160,
        height:36.5,
        size:11,
		
        textAlign:"center",
		expand:"left"},      
       
];
    var dropBox = [{compId:"ID_sub1_DT",/*First group*/
       x:558.3 - 20,
        y:159.65,
        width:160,
        height:36.5,
        size:11,
        answer:3,
        textAlign:"center",
		expand:"left"},
        {compId:"ID_sub2_DT",/*First group*/
       x:558.3 - 20,
        y:199.1,
        width:160,
        height:36.5,
        size:11,
        answer:2,
        textAlign:"center",
		expand:"left"},
		{compId:"ID_sub3_DT",/*First group*/
       x:558.3 - 20,
        y:238.55,
        width:160,
        height:36.5,
        size:11,
        answer:1,
        textAlign:"center",
		expand:"left"},
        {compId:"ID_sub4_DT",/*First group*/
       x:558.3 - 20,
        y:278,
        width:160,
        height:36.5,
        size:11,
        answer:5,
        textAlign:"center",
		expand:"left"},
		{compId:"ID_sub5_DT",/*First group*/
       x:558.3 - 20,
        y:317.6,
        width:160,
        height:36.5,
        size:11,
        answer:4,
        textAlign:"center",
		expand:"left"},
        
		
    ];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_1_texts = [
		{compId:"ID_s1_inst",
        x:2,
        y:1,
        width:605.95,
        height:17,
        size:11,
        textAlign:"left"},
	{compId:"ID_s1_header",
        x:240 - 20,
        y:79.85,
        width:465.75,
        height:17,
        size:11,
        textAlign:"left",
		expand:"up+down"},
		{compId:"ID_s1_subheader",
        x:240 - 20,
        y:114.85,
        width:478.5,
        height:17,
        size:11,
		textAlign:"left",
		expand:"up+down"},
		{compId:"ID_s1_txt01",
        x:240 - 20,
        y:159.85,
        width:316,
        height:9,
        size:11,
		textAlign:"left",
		expand:"down"},
		{compId:"ID_s1_txt02",
        x:240 - 20,
        y:199.85,
        width:316,
        height:9,
        size:11,
		textAlign:"left",
		expand:"down"},
		{compId:"ID_s1_txt03",
        x:240 - 20,
        y:239.85,
        width:316,
        height:9,
        size:11,
		textAlign:"left",
		expand:"down"},
		{compId:"ID_s1_txt04",
        x:240 - 20,
        y:279.85,
        width:316,
        height:9,
        size:11,
		textAlign:"left",
		expand:"down"},
		{compId:"ID_s1_txt05",
        x:240 - 20,
        y:319.85,
        width:316,
        height:9,
        size:11,
		textAlign:"left",
		expand:"down"},
		 
    ];
	var graphics_slide =[];
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_1_images = [{name:"bg.png",
							x:232.65 - 19,
							y:76.25, 
							width:490.05,
							height:281.1,
							type:""},
							{name:"line.png",
							x:220.15,
							y:100.25, 
							width:481.75 - 5,
							height:4,
							type:""},
							];
    var submit_buttons = [{compId:"ID_s1_CHECK",
        x:546- 20,
        y:359,
        width:80,
		height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s1_RESET",
             x:651- 20,
			 y:359,
             width:80,
			 height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:248- 20,
        y:127,
        width:225,
        height:121,
        size:11,
        image:"../../../common/images/feedback2.png",
        textAlign:"center"}];
    var instobj = {ansType:""};
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_1_texts,
							slideImages:slide_1_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
							graphics:graphics_slide,
                            instobj:instobj
    };
	
	/* Slide 2 */
	var slide_2_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_vlsm5_DS",
		x:7.5,
        y:133.45,
        width:160,
        height:36.5,
        size:11,
		textAlign:"center",
		expand:"left"},     
        {compId:"ID_vlsm3_DS",
		x:7.5,
        y:179,
        width:160,
        height:36.5,
        size:11,
		textAlign:"center",
		expand:"left"}, 
		{compId:"ID_vlsm1_DS",
		x:7.5,
        y:224.55,
        width:160,
        height:36.5,
        size:11,
		textAlign:"center",
		expand:"left"}, 
		{compId:"ID_vlsm2_DS",
		x:7.5,
        y:270.1,
        width:160,
        height:36.5,
        size:11,
		textAlign:"center",
		expand:"left"}, 
	{compId:"ID_vlsm4_DS",
		x:7.5,
        y:315.65,
        width:160,
        height:36.5,
        size:11,
		textAlign:"center",
		expand:"left"},      
       
];
    var dropBox = [{compId:"ID_sub1_DT",/*First group*/
       x:558.3 - 20,
        y:159.65,
        width:160,
        height:36.5,
        size:11,
        answer:3,
        textAlign:"center",
		expand:"left"},
        {compId:"ID_sub2_DT",/*First group*/
       x:558.3 - 20,
        y:199.1,
        width:160,
        height:36.5,
        size:11,
        answer:4,
        textAlign:"center",
		expand:"left"},
		{compId:"ID_sub3_DT",/*First group*/
       x:558.3 - 20,
        y:238.55,
        width:160,
        height:36.5,
        size:11,
        answer:2,
        textAlign:"center",
		expand:"left"},
        {compId:"ID_sub4_DT",/*First group*/
       x:558.3 - 20,
        y:278,
        width:160,
        height:36.5,
        size:11,
        answer:5,
        textAlign:"center",
		expand:"left"},
		{compId:"ID_sub5_DT",/*First group*/
       x:558.3 - 20,
        y:317.6,
        width:160,
        height:36.5,
        size:11,
        answer:1,
        textAlign:"center",
		expand:"left"},
        
		
    ];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_2_texts = [
		{compId:"ID_s2_inst",
        x:2,
        y:1,
        width:605.95,
        height:17,
        size:11,
        textAlign:"left"},
	{compId:"ID_s2_header",
        x:240 - 20,
        y:79.85,
        width:465.75,
        height:17,
        size:11,
        textAlign:"left",
		expand:"up+down"},
		{compId:"ID_s2_subheader",
        x:240 - 20,
        y:114.85,
        width:478.75,
        height:17,
        size:11,
		textAlign:"left",
		expand:"up+down"},
		{compId:"ID_s1_txt01",
        x:240 - 20,
        y:159.85,
        width:316,
        height:9,
        size:11,
		textAlign:"left",
		expand:"down"},
		{compId:"ID_s2_txt02",
        x:240 - 20,
        y:199.85,
        width:316,
        height:9,
        size:11,
		textAlign:"left",
		expand:"down"},
		{compId:"ID_s2_txt03",
        x:240 - 20,
        y:239.85,
        width:316,
        height:9,
        size:11,
		textAlign:"left",
		expand:"down"},
		{compId:"ID_s2_txt04",
        x:240 - 20,
        y:279.85,
        width:316,
        height:9,
        size:11,
		textAlign:"left",
		expand:"down"},
		{compId:"ID_s2_txt05",
        x:240 - 20,
        y:319.85,
        width:316,
        height:9,
        size:11,
		textAlign:"left",
		expand:"down"},
		 
    ];
	var graphics_slide =[];
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_2_images = [{name:"bg.png",
							x:232.65 - 19,
							y:76.25, 
							width:490.05,
							height:281.1,
							type:""},
							{name:"line.png",
							x:220.15,
							y:100.25, 
							width:481.75 - 5,
							height:4,
							type:""},
							];
    var submit_buttons = [{compId:"ID_s2_CHECK",
        x:546 - 20,
        y:359,
        width:80,
		height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s2_RESET",
             x:651 - 20,
			 y:359,
             width:80,
			 height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:248- 20,
        y:127,
        width:194,
        height:23,
        size:11,
        image:"../../../common/images/feedback2.png",
        textAlign:"center"}];
    var instobj = {ansType:""};
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_2_texts,
							slideImages:slide_2_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
							graphics:graphics_slide,
                            instobj:instobj
    };
															
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
		    images:common_images,
			slideObject:slides,
			buttonBarPos:{x:720}};
	
}



