loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js"); 

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 800;
var STAGE_HEIGHT = 400;
var TYPE = "MULTI_BAR";
var isDD = true;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	var common_images = [];
	
	var slide_1_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_s1_traget01",
						x:28,
						y:94.4,
						width:171,
						height:34.45,
						size:11,
						tag:1,
						textAlign:"center"},     
				  {compId:"ID_s1_traget02",
						x:28,
						y:133.9,
						width:171,
						height:34.45,
						size:11,
						tag:7,
						textAlign:"center"},
				{compId:"ID_s1_traget03",
						x:28,
						y:173.4,
						width:171,
						height:34.45,
						size:11,
						tag:2,
						textAlign:"center"},
				{compId:"ID_s1_traget04",
						x:28,
						y:212.9,
						width:171,
						height:34.45,
						size:11,
						tag:6,
						textAlign:"center"},
				{compId:"ID_s1_traget05",
						x:28,
						y:252.4,
						width:171,
						height:34.45,
						size:11,
						tag:4,
						textAlign:"center"},
				{compId:"ID_s1_traget06",
						x:28,
						y:291.9,
						width:171,
						height:34.45,
						size:11,
						tag:5,
						textAlign:"center"},     
				{compId:"ID_s1_traget07",
						x:28,
						y:331.4,
						width:171,
						height:34.45,
						size:11,
						tag:3,
						textAlign:"center"}];
						
    var dropBox = [{compId:"a1_dt",
							x:228.5,
							y:90.4,
							width:171,
							height:35.35,
							size:11,
							answer:1,
							textAlign:"center"},
					{compId:"a2_dt",
							x:228.5,
							y:130.3,
							width:171,
							height:35.35,
							size:11,        
							answer:2,
							textAlign:"center"},
					{compId:"a3_dt",
							x:228.5,
							y:170.2,
							width:171,
							height:35.35,
							size:11,
							answer:3,
							textAlign:"center"},
					{compId:"a4_dt",
							x:228.5,
							y:210.1,
							width:171,
							height:35.35,
							size:11,
							answer:4,
							textAlign:"center"},
					{compId:"a5_dt",
							x:228.5,
							y:250,
							width:171,
							height:35.35,
							size:11,
							answer:5,
							textAlign:"center"},
					{compId:"a6_dt",
							x:228.5,
							y:289.9,
							width:171,
							height:35.35,
							size:11,
							answer:6,
							textAlign:"center"},
					{compId:"a7_dt",
							x:228.5,
							y:329.8,
							width:171,
							height:35.35,
							size:11,
							answer:7,
							textAlign:"center"}];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_1_texts = [{compId:"ID_s1_inst",
								x:30,
								y:1,
								width:679.1,
								height:17,
								size:11,
								textAlign:"left"},
						{compId:"ID_s1_txt08",
								x:228.5,
								y:63.4,
								width:171,
								height:17,
								size:11,
								textAlign:"center"},
						{compId:"ID_s1_txt09",
								x:405.3,
								y:63.4,
								width:328,
								height:17,
								size:11,
								textAlign:"center"},
						{compId:"ID_s1_txt01",
								x:416.35,
								y:99.55,
								width:338.1,
								height:17,
								size:11,
								textAlign:"left"},
						{compId:"ID_s1_txt02",
								x:416.35,
								y:137.9,
								width:338.1,
								height:17,
								size:11,
								textAlign:"left"},
						{compId:"ID_s1_txt03",
								x:416.35,
								y:180.85,
								width:338.1,
								height:17,
								size:11,
								textAlign:"left"},
						{compId:"ID_s1_txt04",
								x:416.35,
								y:220.3,
								width:338.1,
								height:17,
								size:11,
								textAlign:"left"},
						{compId:"ID_s1_txt05",
								x:416.35,
								y:259.75,
								width:338.1,
								height:17,
								size:11,
								textAlign:"left"},
						{compId:"ID_s1_txt06",
								x:416.35,
								y:298.45,
								width:338.1,
								height:17,
								size:11,
								textAlign:"left"},
						{compId:"ID_s1_txt07",
								x:416.35,
								y:339.15,
								width:338.1,
								height:17,
								size:11,
								textAlign:"left"}];
								
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_1_images = [{name:"bg.png",
							x:210,
							y:56.15, 
							width:539,
							height:312.85,
							type:""}];
							
    var submit_buttons = [{compId:"ID_s1_CHECK",
								x:594,
								y:377,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"},
							{compId:"ID_s1_RESET",
								x:669,
								y:377,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"}];
								
    var feedbackObj = [{compId:"ID_FEEDBACK",
								x:25,
								y:105,
								width:170,
								height:98,
								size:11,
								image:"../../../common/images/feedback4.png",
								textAlign:"left"}];
								
    var instobj = {ansType:"many-one",clue:1};
	
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_1_texts,
							slideImages:slide_1_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
	
	/* Slide 2 */
	var slide_2_type = "DRAG_DROP";
    var buttonStyle = {
		normalSkinImage:"drag_normal1.png",
		//normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal1.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

   var buttons = [{compId:"ID_s2_traget01",
						x:45.2,
						y:228,
						width:80.15,
						height:74.95,
						size:11,
						tag:4,
						color:"#393536",
						textAlign:"center"},     
				{compId:"ID_s2_traget02",
						x:144.85,
						y:228,
						width:80.15,
						height:74.95,
						size:11,
						tag:7,
						textAlign:"center"},
				{compId:"ID_s2_traget03",
						x:247.5,
						y:228,
						width:80.15,
						height:74.95,
						size:11,
						tag:2,
						textAlign:"center"},
				{compId:"ID_s2_traget04",
						x:348.15,
						y:228,
						width:80.15,
						height:74.95,
						size:11,
						tag:1,
						textAlign:"center"},
				{compId:"ID_s2_traget05",
						x:451.8,
						y:228,
						width:80.15,
						height:74.95,
						size:11,
						tag:6,
						textAlign:"center"},  
				{compId:"ID_s2_traget06",
						x:557.45,
						y:228,
						width:80.15,
						height:74.95,
						size:11,
						tag:5,
						textAlign:"center"},  
				{compId:"ID_s2_traget07",
						x:662.1,
						y:228,
						width:80.15,
						height:74.95,
						size:11,
						tag:3,
						textAlign:"center"}];
						
    var dropBox = [{compId:"a1_dt",
							x:45.2,
							y:125,
							width:80.15,
							height:73.95,
							size:11,
							answer:1,
							textAlign:"center"},
					{compId:"a2_dt",
							x:144.85,
							y:125,
							width:80.15,
							height:73.95,
							size:11,
							answer:2,
							textAlign:"center"},
					{compId:"a3_dt",
							x:247.5,
							y:125,
							width:80.15,
							height:73.95,
							answer:3,
							textAlign:"center"},
					{compId:"a4_dt",
							x:348.15,
							y:125,
							width:80.15,
							height:73.95,
							answer:4,
							textAlign:"center"},
					{compId:"a5_dt",
							x:451.8,
							y:125,
							width:80.15,
							height:73.95,
							size:11,
							answer:5,
							textAlign:"center"},
					{compId:"a6_dt",
							x:557.45,
							y:125,
							width:80.15,
							height:73.95,
							size:11,
							answer:6,
							textAlign:"center"},
					{compId:"a7_dt",
							x:662.1,
							y:125,
							width:80.15,
							height:73.95,
							size:11,
							answer:7,
							textAlign:"center"}];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_2_texts = [{compId:"ID_s2_inst",
								x:30,
								y:1,
								width:375.9,
								height:17,
								size:11,
								textAlign:"left"},
						{compId:"ID_s2_txt01",
								x:59,
								y:69.4,
								width:675,
								height:17,
								size:11,
								textAlign:"center"},
						{compId:"ID_s2_txt02",
								x:42.95,
								y:103.4,
								width:82.65,
								height:17,
								size:11,
								textAlign:"center"},
						{compId:"ID_s2_txt03",
								x:140.65,
								y:103.4,
								width:82.65,
								height:17,
								size:11,
								textAlign:"center"},
						{compId:"ID_s2_txt04",
								x:244.3,
								y:103.4,
								width:82.65,
								height:17,
								size:11,
								textAlign:"center"},
						{compId:"ID_s2_txt05",
								x:347,
								y:103.4,
								width:82.65,
								height:17,
								size:11,
								textAlign:"center"},
						{compId:"ID_s2_txt06",
								x:446.65,
								y:103.4,
								width:82.65,
								height:17,
								size:11,
								textAlign:"center"},
						{compId:"ID_s2_txt07",
								x:556.35,
								y:103.4,
								width:82.65,
								height:17,
								size:11,
								textAlign:"center"},
						{compId:"ID_s2_txt08",
								x:660,
								y:103.4,
								width:82.65,
								height:17,
								size:11,
								textAlign:"center"}];
								
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_2_images = [{name:"bg1.png",
							x:30,
							y:63.55, 
							width:720,
							height:257,
							type:""}];
							
    var submit_buttons = [{compId:"ID_s2_CHECK",
								x:594,
								y:377,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"},
						{compId:"ID_s2_RESET",
								x:669,
								y:377,
								width:80,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"}];
								
    var feedbackObj = [{compId:"ID_FEEDBACK",
								x:300,
								y:200,
								width:170,
								height:98,
								size:11,
								image:"../../../common/images/feedback2.png",
								textAlign:"left"}];
		
    var instobj = {ansType:"many-one",clue:1};
	
 var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_2_texts,
							slideImages:slide_2_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj};
			
	
															
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
		    images:common_images,
			slideObject:slides,
			buttonBarPos:{x:725}};
	
}



