loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	
	var slide_2_type = "IMAGE";
	var slide_2_images = [{name:"4_2_2_1B.jpg",
							x:13,
							y:48 , 
							width:422.55,
							height:171.5,
							type:""},
							];								
	var slide_2_texts = [{compId:"ID_title1",
							x:8,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_txt01",
							x:18,
							y:222.85, 
							width:57,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt04",
							x:370,
							y:222.85, 
							width:57,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt02",
							x:167.3+10,
							y:176.5, 
							width:96,
							height:19,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt06",
							x:56.15-24,
							y:62.6, 
							width:135.15,
							height:29.8,
							size:11,
							textAlign:"left"}];							
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts};
	
	var slide_3_type = "IMAGE";
	var slide_3_images = [{name:"4_2_2_1C.jpg",
							x:13.1,
							y:148.25, 
							width:422.55,
							height:71.5,
							type:""},
							{name:"btn_slide_3.png",
							x:75,
							y:230, 
							width:280.75,
							height:74.65,
							type:""},
							{name:"arrow_1.png",
							x:120,
							y:303, 
							width:23,
							height:29,
							type:""},
							{name:"arrow_2.png",
							x:275,
							y:303, 
							width:22,
							height:26,
							type:""}
							];								
	var slide_3_texts = [{compId:"ID_title2",
							x:8,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_txt01",
							x:18,
							y:222.85, 
							width:57,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt04",
							x:370,
							y:222.85, 
							width:57,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt02",
							x:167.3+10,
							y:176.5, 
							width:96,
							height:19,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt07",
							x:85,
							y:240, 
							width:130,
							height:19,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt08",
							x:223,
							y:240, 
							width:130,
							height:19,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt09",
							x:85,
							y:280, 
							width:130,
							height:19,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt10",
							x:223,
							y:280, 
							width:130,
							height:19,
							size:11,
							textAlign:"center"},
							{compId:"ID_bubble",
							x:15.6,
							y:315, 
							size:11},
							{compId:"ID_bubble1",
							x:227.55,
							y:315, 
							size:11},
							];							
	var slide_3_object = {templateType:slide_3_type,
							x:0,
							y:0,
							images:slide_3_images,
							texts:slide_3_texts};		
							
	var slide_4_type = "IMAGE";
	var slide_4_images = [{name:"4_2_2_1C.jpg",
							x:13.1,
							y:148.25, 
							width:422.55,
							height:71.5,
							type:""},
							{name:"leftarrow.png",
							x:90,
							y:159.4, 
							width:50,
							height:19,
							type:""},
							{name:"Arrow.png",
							x:33.45,
							y:103.5, 
							width:23.75,
							height:44.6,
							type:""},
							{name:"4_2_2_1.jpg",
							x:179,
							y:40, 
							width:171,
							height:88,
							type:""},
							{name:"highlight.png",
							x:228.5,
							y:89, 
							width:93.5,
							height:19,
							type:""}];								
	var slide_4_texts = [{compId:"ID_title3",
							x:8,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_txt01",
							x:18,
							y:222.85, 
							width:57,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt04",
							x:370,
							y:222.85, 
							width:57,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt02",
							x:167.3+10,
							y:176.5, 
							width:96,
							height:19,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt11",
							x:56.15,
							y:93, 
							width:116.15,
							height:40,
							size:11,
							textAlign:"center"}];							
	var slide_4_object = {templateType:slide_4_type,
							x:0,
							y:0,
							images:slide_4_images,
							texts:slide_4_texts};	
							
	var slide_5_type = "IMAGE";
	var slide_5_images = [{name:"4_2_2_1C.jpg",
							x:13.1,
							y:148.25, 
							width:422.55,
							height:71.5,
							type:""},
							{name:"btn_slide_5.png",
							x:165,
							y:224.65, 
							width:98.75,
							height:27,
							type:""}];								
	var slide_5_texts = [{compId:"ID_title4",
							x:8,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_txt01",
							x:18,
							y:222.85, 
							width:57,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt04",
							x:370,
							y:222.85, 
							width:57,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt02",
							x:167.3+10,
							y:176.5, 
							width:96,
							height:19,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt12",
							x:167.7,
							y:254.6, 
							width:104,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt13",
							x:3.6,
							y:376.85, 
							width:440,
							height:17,
							size:11,
							textAlign:"left"}];							
	var slide_5_object = {templateType:slide_5_type,
							x:0,
							y:0,
							images:slide_5_images,
							texts:slide_5_texts};						
	var slide_6_type = "IMAGE";
	var slide_6_images = [{name:"4_2_2_1C.jpg",
							x:13.1,
							y:148.25, 
							width:422.55,
							height:71.5,
							type:""}];								
	var slide_6_texts = [{compId:"ID_title5",
							x:8,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_txt01",
							x:18,
							y:222.85, 
							width:57,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt04",
							x:370,
							y:222.85, 
							width:57,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt02",
							x:167.3+10,
							y:176.5, 
							width:96,
							height:19,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt12",
							x:339.8+24,
							y:137.85, 
							width:82,
							height:19,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt05",
							x:3.6,
							y:360, 
							width:440,
							height:17,
							size:11,
							textAlign:"left"}];							
	var slide_6_object = {templateType:slide_6_type,
							x:0,
							y:0,
							images:slide_6_images,
							texts:slide_6_texts};										
	var slides = [slide_2_object,slide_3_object,slide_4_object,slide_5_object,slide_6_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			slideObject:slides};
	
}
