loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiButtonSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}

var STAGE_WIDTH = 500;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	
	var slide_1_type = "IMAGE";
	var slide_1_images = [{name:"1_2_2_4A.png",
							x:120,
							y:100,
							width:230,
							height:125,
							type:""}];							
							
	var slide_1_texts = [{compId:"ID_s1_title",
							x:30,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s1_txt02",
							x:35,
							y:90, 
							width:119,
							height:17,
							size:11,
							textAlign:"left",
							expand:"up"},
							{compId:"ID_s1_txt03",
							x:223,
							y:123, 
							width:70,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s1_txt04",
							x:150,
							y:193, 
							width:70,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s1_txt05",
							x:291,
							y:193, 
							width:70,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s1_txt06",
							x:320,
							y:115, 
							width:100,
							height:17,
							size:11,
							textAlign:"left",
							expand:"up"},
							{compId:"ID_s1_txt01",
							x:20,
							y:300, 
							width:410,
							height:30,
							size:11,
							textAlign:"left",
							expand:"down"}];
	var slide_graphics = [];							
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts,
							graphics:slide_graphics};

							
	
	var slide_2_type = "IMAGE";
	var slide_2_images = [{name:"1_2_2_4B.png",
							x:70,
							y:90,
							width:330,
							height:160,
							type:""}];							
							
	var slide_2_texts = [{compId:"ID_s2_title",
							x:30,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s2_txt02",
							x:5,
							y:90+22, 
							width:119,
							height:17,
							size:11,
							textAlign:"left",
							expand:"up"},
							{compId:"ID_s2_txt10",
							x:198-42-24,
							y:107, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s2_txt11",
							x:263-40-24,
							y:120, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s2_txt12",
							x:329-39-24,
							y:109, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s2_txt13",
							x:195-38-24-11,
							y:188, 
							width:119,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_s2_txt14",
							x:325-40-24,
							y:188, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s2_txt15",
							x:388-42-24,
							y:187, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s2_txt16",
							x:180-42-24,
							y:222, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s2_txt17",
							x:310-41-24,
							y:222, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s2_txt01",
							x:20,
							y:300, 
							width:410,
							height:30,
							size:11,
							textAlign:"left",
							expand:"down"}];
	var slide_graphics = [];							
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts,
							graphics:slide_graphics};

	var slide_3_type = "IMAGE";
	var slide_3_images = [{name:"1_2_2_4C.png",
							x:40,
							y:40,
							width:355.3,
							height:243.05,
							type:""}];							
	var slide_3_texts = [{compId:"ID_s3_title",
							x:30,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s3_txt02",
							x:106-10,
							y:143+7, 
							width:40,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt03",
							x:152-10,
							y:98+7, 
							width:40,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt04",
							x:197-10,
							y:98+7, 
							width:40,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt05",
							x:267-10,
							y:98+7,  
							width:40,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt06",
							x:323-10,
							y:100+7, 
							width:40,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt07",
							x:373-10,
							y:178+7, 
							width:40,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt08",
							x:325-19,
							y:243, 
							width:40,
							height:17,
							size:11,
							textAlign:"center",
							expand:"down"},
							{compId:"ID_s3_txt09",
							x:105-10,
							y:220+7, 
							width:40,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt10",
							x:165-47,
							y:135, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt11",
							x:225-47,
							y:149, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt12",
							x:290-47,
							y:139, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt13",
							x:165-53+5,
							y:213, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt14",
							x:283-49+4,
							y:213, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt15",
							x:345-50+3,
							y:212, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt16",
							x:148-47,
							y:245, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt17",
							x:273-51+5,
							y:245, 
							width:119,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up+down"},
							{compId:"ID_s3_txt01",
							x:20,
							y:300, 
							width:410,
							height:30,
							size:11,
							textAlign:"left",
							expand:"down"}];
	var slide_graphics = [];							
	var slide_3_object = {templateType:slide_3_type,
							x:0,
							y:0,
							images:slide_3_images,
							texts:slide_3_texts,
							graphics:slide_graphics};
						
											
	var slides = [slide_1_object,slide_2_object,slide_3_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			slideObject:slides};
	
}



