//loadScript("../../../common/scripts/templates/slide/ImageSlideNew.js");

function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
    var template_type = "IMAGE";

    var slide_images = [{name:"10.2.1.5.png",
        x:0.75,
        y:180.65,
        width:468.65,
        height:208.1,
        type:""}
		];

    var slide_texts = [
		{compId:"ID_title",
            x:5,
            y:2,
            width:460,
            height:17,
            size:14,
            textAlign:"center"},
		{compId:"cross",
            x:294.45+2,
        	y:197.4-12,
        	width:19.8,
        	height:24.3,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt01",
            x:1,
            y:145.85-41,
            width:105,
            height:17,
            size:10,
            textAlign:"left"},
        {compId:"ID_txt02",
            x:127.25,
            y:145.85-41,
            width:105,
            height:17,
            size:10,
            textAlign:"left"},
		{compId:"ID_txt03",
            x:360,
             y:145.85-41,
            width:105,
            height:17,
            size:10,
            textAlign:"left"},
		{compId:"ID_txt04",
            x:245+6,
            y:293.85-18,
            width:105,
            height:17,
            size:10,
            textAlign:"left"},
		{compId:"ID_txt05",
            x:162.5-17,
            y:39.5-4,
            width:190,
            height:17,
            size:10,
            textAlign:"center"},
		{compId:"ID_txt06",
            x:405,
            y:359.8,
            width:67,
            height:17,
            size:11,
            textAlign:"center"},
			{compId:"ID_bubble02",
            x:251,
            y:94.65+8,
            width:91,
            height:86,
            size:11,
            textAlign:"left"},
			{compId:"ID_bubble01",
            x:37.25-15,
            y:270.2-17+5,
            width:169,
            height:76,
            size:11,
            textAlign:"left"},
			{compId:"staticTxt",
			 bodyText:'<b>A</b>',
			 x:35.35+13,
			 y:188.75, 
			 width:15,
			 height:17,
			 size:11,
		     textAlign:"left",
			color:"#fff"},

			{compId:"staticTxt",
			 bodyText:'<b>B</b>',
			  x:35.35+138,
			  y:188.75, 
			 width:15,
			 height:17,
			 size:11,
		     textAlign:"left",
			color:"#fff",},
			{compId:"staticTxt",
			 bodyText:'<b>C</b>',
			  x:35.35+138+130,
			  y:188.75, 
			 width:15,
			 height:17,
			 size:11,
		     textAlign:"left",
			color:"#fff",},
			{compId:"staticTxt",
			 bodyText:'<b>D</b>',
			  x:428,
			  y:188.75, 
			 width:15,
			 height:17,
			 size:11,
		     textAlign:"left",
			color:"#fff",},
			{compId:"ID_table",
			  x:129,
			  y:22.75, 
			 width:15,
			 height:17,
			 size:11,
		     textAlign:"left",
			color:"#fff",},
			{compId:"staticTxt",
			 bodyText:'G0/0',
			  x:211,
			  y:38.75+294, 
			 width:24,
			 height:17,
			 size:11,
		     textAlign:"left",
			color:"#000",},
			{compId:"staticTxt",
			 bodyText:'<b>R1</b>',
			  x:221.25+13,
			  y:371.75, 
			 width:24,
			 height:17,
			 size:11,
		     textAlign:"left",
			color:"#fff",}
			];
		
	var slide_1_graphics = [{}]	

    var slide_object = {images:slide_images,
	    graphics:slide_1_graphics,
        texts:slide_texts};

    return {templateType:template_type,
        slideObject:slide_object};

}

loadScript("../../../common/scripts/swfobject.js", registerSWF);
