//loadScript("../../../common/scripts/templates/slide/ImageSlideNew.js");

function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
    var template_type = "IMAGE";

    var slide_images = [{name:"2_1_4_6.png",
        x:5,
        y:16.7,
        width:462.35,
        height:332.65,
        type:""}];

    var slide_texts = [{compId:"ID_title",
							x:1,
							y:1, 
							width:468,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt01",
							x:15.9,
							y:365, 
							width:443,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_txt02",
							x:47,
							y:113, 
							width:179,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt03",
							x:21.2,
							y:175, 
							width:74.15,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt04",
							x:95.05,
							y:163, 
							width:91.65,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt05",
							x:185.35,
							y:169.55, 
							width:67.65,
							height:17.45,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt06",
							x:261.9,
							y:154.85, 
							width:64.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt07",
							x:338,
							y:159.85, 
							width:70,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt08",
							x:410,
							y:164.4, 
							width:66.3,
							height:17.45,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt09",
							x:106.75,
							y:86.95, 
							width:50.8,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt10",
							x:262.4,
							y:86.45, 
							width:65.8,
							height:17.45,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt11",
							x:347.05,
							y:86.45, 
							width:54.15,
							height:17.45,
							size:11,
							textAlign:"center"},
							{compId:"staticTxt_1",
			 				 bodyText:"Switch<b>#show version</b>",
							 x:26,
							 y:20.7,
							 width:155,
							 height:17.75,
							size:11,
							 textAlign:"left"},
							 {compId:"staticTxt_2",
			 				 bodyText:"Switch<b>#show flash</b>",
							 x:185.75,
							 y:20.7,
							 width:155,
							 height:17.75,
							size:11,
							 textAlign:"left"},
							 {compId:"staticTxt_3",
			 				 bodyText:"Switch<b>#show interfaces</b>",
							 x:318.5,
							 y:20.7,
							width:155,
							 height:17.75,
							size:11,
							 textAlign:"left"},
							 {compId:"staticTxt_4",
			 				 bodyText:"Switch#<b>show  processes</b><br/>Switch#<b>show  cdp neighbors</b>",
							 x:34-15,
							 y:266.8+2,
							 width:193.2,
							 height:33.50,
							size:11,
							 textAlign:"left"},
							 {compId:"staticTxt_5",
			 				 bodyText:"Switch#<b>show  arp</b></b><br/>Switch<b>#show  mac-address-table</b><br/>Switch<b>#show show  vlan</b>",
							 x:286.6-46,
							 y:269.8,
							 width:214,
							 height:49.25,
							size:11,
							 textAlign:"left"},
							 {compId:"staticTxt_6",
			 				 bodyText:"Switch<b>#show running-config</b>",
							 x:55.45,
							 y:330.3,
							 width:200.4,
							 height:17.75,
							size:11,
							 textAlign:"left"},
							 {compId:"staticTxt_7",
			 				 bodyText:"Switch<b>#show startup-config</b>",
							 x:274.5+9,
							 y:330.3,
							 width:187,
							 height:17.75,
								size:11,
							 textAlign:"left"}];

    var slide_object = {images:slide_images,
        texts:slide_texts};

    return {templateType:template_type,
        slideObject:slide_object};

}

loadScript("../../../common/scripts/swfobject.js", registerSWF);
