//loadScript("../../../common/scripts/templates/slide/ImageSlideNew.js");
loadScript("../../../common/scripts/swfobject.js", registerSWF);

function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}

var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
    var template_type = "IMAGE";

    var slide_images = [{name:"3_3_3_2.jpg",
						x:0,
						y:65,
						width:470,
						height:284,
						type:""}];

    var slide_texts = [{compId:"ID_title",
							x:15,
							y:2, 
							width:460,
							height:17,
							size:16,
							textAlign:"center"},
							{compId:"ID_txt01",
							x:30,
							y:44, 
							width:143,
							height:17,
							size:12,
							textAlign:"center"},
							{compId:"ID_txt02",
							x:239,
							y:44, 
							width:129.05,
							height:17,
							size:12,
							textAlign:"center"},
							{compId:"ID_txt03",
							x:18-6,
							y:113, 
							width:90.65,
							height:21,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt04",
							x:122-16,
							y:113, 
							width:86,
							height:21,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt05",
							x:210-16,
							y:113, 
							width:107.65,
							height:21,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt06",
							x:335-31,
							y:113, 
							width:112.65,
							height:21,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt07",
							x:432-12,
							y:130, 
							width:57,
							height:21,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt08",
							x:12,
							y:139, 
							width:83.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt09",
							x:104,
							y:139, 
							width:83.45,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt10",
							x:197,
							y:139, 
							width:52.5,
							height:33,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt11",
							x:260,
							y:139, 
							width:37.95,
							height:33,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt12",
							x:308,
							y:139, 
							width:51.45,
							height:30,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt13",
							x:369+3,
							y:139, 
							width:37.85,
							height:30,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt14",
							x:10,
							y:182, 
							width:124.8,
							height:34.6,
							size:11,
							textAlign:"left"},
							{compId:"ID_txt15",
							x:137,
							y:182, 
							width:120,
							height:34.6,
							size:11,
							textAlign:"left"},
							{compId:"ID_txt16",
							x:260,
							y:182, 
							width:114,
							height:34.6,
							size:11,
							textAlign:"left"},
							{compId:"ID_txt17",
							x:374,
							y:182, 
							width:108,
							height:34.6,
							size:11,
							textAlign:"left"},
							{compId:"ID_txt18",
							x:13,
							y:338, 
							width:124.8,
							height:34.6,
							size:11,
							textAlign:"left"},
							{compId:"ID_txt19",
							x:160,
							y:338, 
							width:124.8,
							height:34.6,
							size:11,
							textAlign:"left"}];

    var slide_object = {images:slide_images,
        texts:slide_texts};

    return {templateType:template_type,
        slideObject:slide_object};

}
