//loadScript("../../../common/scripts/templates/slide/ImageSlideNew.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "IMAGE";
		
	var slide_images = [{name:"10.1.2.2.png",
							x:9.55,
							y:173.5, 
							width:376.6, 
							height:45.05,
							type:""}];
							
	var slide_texts = [{compId:"ID_title",
							 x:18,
							 y:2,
							 width:460,
							 height:17,
							 size:14,
							 textAlign:"center"},
							
		 {compId:"ID_txt01",
							 x:175.5+16,
							 y:75.35+11,
							 width:36.25,
							 height:17,
							 size:11,
							 textAlign:"center"},
			{compId:"ID_txt02",
							 x:6.55,
							 y:132-14,
							 width:75,
							 height:17,
							 size:11,
							 textAlign:"center"},
			 {compId:"ID_txt03",
							 x:85,
							 y:132-14,
							 width:75,
							 height:17,
							 size:11,
							 textAlign:"center"},
			 {compId:"ID_txt04",
							 x:163.7,
							 y:132-14,
							 width:79,
							 height:17,
							 size:11,
							 textAlign:"center"},
		 {compId:"ID_txt05",
							 x:248,
							 y:125-6,
							 width:72,
							 height:17,
							 size:11,
							 textAlign:"center"},
		 {compId:"ID_txt06",
							 x:332.25-9,
							  y:125-6,
							 width:67,
							 height:17,
							 size:11,
							 textAlign:"center"},
		 {compId:"ID_txt07",
							 x:396.5,
							 y:132-14,
							 width:59.95,
							 height:17,
							 size:11,
							 textAlign:"center"},
		{compId:"ID_txt08",
							 x:24.55+11,
							 y:288.05-6,
							 width:46.85,
							 height:17,
							 size:11,
							 textAlign:"center"},
							{compId:"ID_txt09",
							x:114.5+56,
							y:292.05-9,
							 width:149.85,
							 height:17,
							 size:11,
							 textAlign:"center"},
							{compId:"ID_txt10",
							 x:12.5+7,
							 y:235.8-19,
							 width:66.85,
							 height:17,
							 size:11,
							 textAlign:"center"},
							{compId:"ID_txt11",
							 x:102.65,
							 y:235.8-19,
							 width:79.85,
							 height:17,
							 size:11,
							 textAlign:"center"},
							 {compId:"ID_txt12",
							 x:194.5,
							 y:235.8-19,
							 width:95,
							 height:17,
							 size:11,
							 textAlign:"center"},
								
		 {compId:"ID_txt13",
							 x:300,
							y:235.8-19,
							 width:87,
							 height:17,
							 size:11,
							 textAlign:"center"},
						];
	var slide_graphics=[{type:"border",
							 div:"borderText",
								border:1,
								x:5,
								y:118,
								width:460,
								height:55,
								},
								{type:"border",
							 div:"borderText1",
								border:1,
								x:18.65,
								y:215.8,
								width:376.35,
								height:55,
								},
								{type:"border",
								 div:"borderText01",
								 border:1,
								 x:155.25+9,
								 y:101.85,
								 width:82.5,
								 height:13.55,
								},
								{type:"border",
								 div:"borderText08",
								 border:1,
								 x:9.65+9,
								 y:275.2,
								 width:77.5,
								 height:13.55,
								},
								{type:"border",
								 div:"borderText09",
								 border:1,
								 x:96.75+3,
								 y:275.2,
								 width:296.8,
								 height:13.55,
								}
		]
							
	var slide_object = {images:slide_images,
		graphics:slide_graphics,
						texts:slide_texts};
						
	return {templateType:template_type,
			slideObject:slide_object};
	
}

loadScript("../../../common/scripts/swfobject.js", registerSWF);
