loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/DragDropSlide.js");


function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}

var STAGE_WIDTH = 780;
var STAGE_HEIGHT = 400;

function getData()
{
	/*1st Activity Starts*/
	
   var template_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal_small.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        //dropNormalSkinImage:"../../../common/images/drop_normal.png",
		dropNormalSkinImage:"blank.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

	
     var buttons = [{compId:"ID_s1_drag03",
							x:20,
							y:71,
							width:154,
							height:71,
							size:11,
							color:"#45505B",
							textAlign:"center"},
						{compId:"ID_s1_drag01",
							x:20,
							y:160,
							width:154,
							height:71,
							size:11,
							color:"#45505B",
							textAlign:"center"},
						{compId:"ID_s1_drag02",
							x:20,
							y:249,
							width:154,
							height:71,
							size:11,
							color:"#45505B",
							textAlign:"center"}];


    var dropBox = [{compId:"ID_drop01",
						x:300.95,
						y:67,
						width:152,
						height:78,
						size:11,
						answer:2,
						textAlign:"left"},
					{compId:"ID_drop02",
						x:300.95,
						y:210,
						width:152,
						height:78,
						size:11,
						answer:3,
						textAlign:"left"},
					{compId:"ID_drop03",
						x:300.95,
						y:325,
						width:152,
						height:70,
						size:11,
						answer:1,
						textAlign:"left"}];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_texts = [{compId:"ID_table01",
							x:220.30,
							y:5, 
							width:75,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},							
						{compId:"ID_table02",
							x:301.30,
							y:11.80, 
							width:151,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
						{compId:"ID_table03",
							x:454.30,
							y:11.80, 
							width:303,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
						{compId:"ID_table04",
							x:211.30,
							y:97.80, 
							width:88,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
						{compId:"ID_table05",
							x:211.30,
							y:243.80, 
							width:88,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
						{compId:"ID_table06",
							x:211.30,
							y:353.80, 
							width:88,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
						{compId:"ID_s1_inst",
							x:3,
							y:2, 
							width:200,
							height:17,
							size:11,
							textAlign:"left"}];

    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_images = [{compId:"ID_image01",
							name:"table.jpg",
							x:209,
							y:2,
							width:550,
							height:395,
							size:12,
							textAlign:"left"}];


    var submit_buttons = [{compId:"ID_s1_CHECK",
								x:10,
								y:365,
								width:120,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"},
							{compId:"ID_s1_RESET",
								x:100,
								y:365,
								width:120,
								height:23,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"}];
	
    var feedbackObj = [{compId:"ID_FEEDBACK",
							x:510,
							y:95,
							width:231,
							height:170,
							size:12,
							image:"../../../common/images/feedback.png",
							textAlign:"left"}];
    var instobj = {ansType:""};
    
    return {templateType:template_type,
        textObject:commonTexts,
        buttonObject:buttonObject,
        slideObject:slide_texts,
        slideImages:slide_images,
        dropObject:dropObject,
        submitObject:submit_buttons,
		slideNo:1,
		squence:"multi",
        feedbackObj:feedbackObj,
		instobj:instobj
    };

/*1st Activity ends*/
}
/*2nd Activity Starts*/
function slide2()
{
	var template_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        //dropNormalSkinImage:"../../../common/images/drop_normal.png",
		dropNormalSkinImage:"blank.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};
		
var buttons = [{image:"icon_workgroup_switch.png",
					x:0,
					y:54.25-6,
					width:102,
					height:43,
					size:11,
					color:"#45505B",
					textAlign:"center",
					tag:2,
					},
						
				{image:"icon_ip_phone.png",
					x:105.20,
					y:54.25-6,
					width:102,
					height:43,
					size:11,
					color:"#45505B",
					tag:1,
					textAlign:"center"},
					
				{image:"icon_WAN_media.png",
					x:0,
					y:100.55-6,
					width:102,
					height:43,
					size:11,
					tag:3,
					color:"#45505B",
					textAlign:"center"},
					
				{image:"security.png",
					x:105.20,
					y:100.55-6,
					width:102,
					tag:2,
					height:43,
					size:11,
					color:"#45505B",
					textAlign:"center"},
					
				{image:"icon_tablet.png",
					x:0,
					y:146.85-6,
					width:102,
					tag:1,
					height:43,
					size:11,
					color:"#45505B",
					textAlign:"center"},
					
				{image:"icon_laptop.png",
					x:105.20,
					y:146.85-6,
					width:102,
					height:43,
					tag:1,
					size:11,
					color:"#45505B",
					textAlign:"center"},
					
				{image:"computer.png",
					x:0,
					y:193.15-6,
					width:102,
					height:43,
					size:11,
					tag:1,
					color:"#45505B",
					textAlign:"center"},
					
				{image:"icon_wireless_media.png",
					x:105.20,
					y:193.15-6,
					width:102,
					height:43,
					size:11,
					tag:3,
					color:"#45505B",
					textAlign:"center"},	
							
				{image:"Router.png",
					x:0,
					y:239.45-6,
					width:102,
					height:43,
					tag:2,
					size:11,
					color:"#45505B",
					textAlign:"center"},
					
				{image:"icon_printer.png",
					x:105.20,
					y:239.45-6,
					width:102,
					tag:1,
					height:43,
					size:11,
					color:"#45505B",
					textAlign:"center"},	
							
				{image:"icon_telepresence.png",
					x:0,
					y:285.75-6,
					width:102,
					height:43,
					size:11,
					tag:1,
					color:"#45505B",
					textAlign:"center"},
					
				{image:"Switch-Layer 3.png",
					x:105.20,
					y:285.75-6,
					width:102,
					height:43,
					size:11,
					tag:2,
					color:"#45505B",
					textAlign:"center"},
								
				{image:"Symbol 1.png",
					x:0,
					y:332.05-6,
					width:102,
					height:43,
					size:11,
					tag:2,
					color:"#45505B",
					textAlign:"center"},
					
				{image:"Symbol 2.png",
					x:105.20,
					y:332.05-6,
					width:102,
					height:43,
					size:11,
					tag:3,
					color:"#45505B",
					textAlign:"center"}];


    var dropBox = [{compId:"ID_drop01",
        x:452.50,
        y:33.75,
        width:102,
        height:43 	,
        size:11,
        answer:1,
        textAlign:"center"},
		{compId:"ID_drop02",
		x:554.50,
		y:33.75,
		width:102,
		height:43,
		size:11,
		answer:1,
		textAlign:"center"},
		{compId:"ID_drop03",
		x:656.50,
		y:33.75,
		width:102,
		height:43,
		size:11,
		answer:1,
		textAlign:"center"},
		{compId:"ID_drop04",
        x:452.50,
        y:108.50,
        width:102,
        height:43,
        size:11,
        answer:1,
        textAlign:"center"},
		{compId:"ID_drop05",
		x:554.50,
		y:108.50,
		width:102,
		height:43,
		size:11,
		answer:1,
		textAlign:"center"},
		{compId:"ID_drop06",
		x:656.50,
		y:108.50,
		width:102,
		height:43,
		size:11,
		answer:1,
		textAlign:"center"},
		{compId:"ID_drop07",
        x:452.50,
        y:179.80,
        width:102,
        height:43,
        size:11,
        answer:2,
        textAlign:"center"},
		{compId:"ID_drop08",
		x:554.50,
		y:179.80,
		width:102,
		height:43,
		size:11,
		answer:2,
		textAlign:"center"},
		{compId:"ID_drop09",
		x:656.50,
		y:179.80,
		width:102,
		height:43,
		size:11,
		answer:2,
		textAlign:"center"},
		{compId:"ID_drop10",
        x:452.50,
        y:254.35,
        width:102,
        height:43,
        size:11,
        answer:2,
        textAlign:"center"},
		{compId:"ID_drop11",
		x:554.50,
		y:254.35,
		width:102,
		height:43,
		size:11,
		answer:2,
		textAlign:"center"},
		{compId:"ID_drop12",
        x:452.50,
        y:325.35,
        width:102,
        height:43,
        size:11,
        answer:3,
        textAlign:"center"},
		{compId:"ID_drop13",
		x:554.50,
		y:325.35,
		width:102,
		height:43,
		size:11,
		answer:3,
		textAlign:"center"},
		{compId:"ID_drop14",
		x:656.50,
		y:325.35,
		width:102,
		height:43,
		size:11,
		answer:3,
		textAlign:"center"},
			
		];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_texts = [	{compId:"ID_table01",
							x:220.30,
							y:5, 
							width:75,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},							
							{compId:"ID_table02",
							x:301.30,
							y:11.80, 
							width:151,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
							{compId:"ID_table03",
							x:454.30,
							y:11.80, 
							width:303,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
							{compId:"ID_table04",
							x:211.30,
							y:97.80, 
							width:88,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
							{compId:"ID_table05",
							x:211.30,
							y:243.80, 
							width:88,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
							{compId:"ID_table06",
							x:211.30,
							y:353.80, 
							width:88,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
							{compId:"ID_s1_drag01",
							x:308.30,
							y:75.8, 
							width:141,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"left"},
							{compId:"ID_s1_drag02",
							x:308.30,
							y:220.8, 
							width:144,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"left"},
							{compId:"ID_s1_drag03",
							x:308.30,
							y:337.8, 
							width:144,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"left"},
							{compId:"ID_s2_inst",
							x:0,
							y:-8, 
							width:200,
							height:17,
							size:11,
							textAlign:"left"}];

    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_images = [{compId:"ID_image01",
        name:"1_3_1_7_B.png",
        x:209,
        y:2,
        width:550,
        height:395,
        size:12,
        textAlign:"left"}];


    var submit_buttons = [{compId:"ID_s1_CHECK",
        x:10,
        y:370,
        width:100,
        height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s1_RESET",
            x:113,
            y:370,
			width:90,
			height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:236,
        y:95,
        width:190,
        height:140,
        size:12,
        image:"../../../common/images/feedback.png",
        textAlign:"left"}];
    var instobj = {ansType:"many-one"};
    
    return {templateType:template_type,
        textObject:commonTexts,
        buttonObject:buttonObject,
        slideObject:slide_texts,
        slideImages:slide_images,
        dropObject:dropObject,
        submitObject:submit_buttons,
		slideNo:2,
		squence:"multi",
        feedbackObj:feedbackObj,
	instobj:instobj
    };	
}

/*2nd Activity Ends*/


/*3rd Activity Starts*/

function slide3()
{
	var template_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        //dropNormalSkinImage:"../../../common/images/drop_normal.png",
		dropNormalSkinImage:"blank.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};
		
var buttons = [{compId:"ID_s3_drag14",
						x:0,
						y:48.25+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},
						
						{compId:"ID_s3_drag03",
						x:105.20,
						y:48.25+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},
						
						{compId:"ID_s3_drag02",
						x:0,
						y:94.55+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},
						
						{compId:"ID_s3_drag09",
						x:105.20,
						y:94.55+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},
						
						{compId:"ID_s3_drag08",
						x:0,
						y:140.85+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},
						
						{compId:"ID_s3_drag13",
						x:105.20,
						y:140.85+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},
						
						{compId:"ID_s3_drag04",
						x:0,
						y:187.15+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},
						
						{compId:"ID_s3_drag11",
						x:105.20,
						y:187.15+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},	
								
						{compId:"ID_s3_drag05",
						x:0,
						y:233.45+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},
						
						{compId:"ID_s3_drag12",
						x:105.20,
						y:233.45+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},	
								
						{compId:"ID_s3_drag10",
						x:0,
						y:279.75+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},
						
						{compId:"ID_s3_drag01",
						x:105.20,
						y:279.75+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},	
								
						{compId:"ID_s3_drag07",
						x:0,
						y:326.05+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"},
						
						{compId:"ID_s3_drag06",
						x:105.20,
						y:326.05+8,
						width:102,
						height:30,
						size:11,
						color:"#45505B",
						textAlign:"center"}];
				

    var dropBox = [{compId:"ID_s3_drag1",
        x:452.50,
        y:75.75,
        width:102,
        height:30,
        size:11,
        answer:9,
        textAlign:"center"},
		
		{compId:"ID_drop02",
		x:554.50,
		y:75.75,
		width:102,
		height:30,
		size:11,
		answer:12,
		textAlign:"center"},
		
		{compId:"ID_drop03",
		x:656.50,
		y:75.75,
		width:102,
		height:30,
		size:11,
		answer:2,
		textAlign:"center"},
		
		{compId:"ID_drop04",
        x:452.50,
        y:148.50,
        width:102,
        height:30,
        size:11,
        answer:7,
        textAlign:"center"},
		
		{compId:"ID_drop05",
		x:554.50,
		y:148.50,
		width:102,
		height:30,
		size:11,
		answer:3,
		textAlign:"center"},
		
		{compId:"ID_drop06",
		x:656.50,
		y:148.50,
		width:102,
		height:30,
		size:11,
		answer:14,	
		textAlign:"center"},
		
		{compId:"ID_drop07",
        x:452.50,
        y:223.80,
        width:102,
        height:30,
        size:11,
        answer:4,
        textAlign:"center"},
		
		{compId:"ID_drop08",
		x:554.50,
		y:223.80,
		width:102,
		height:30,
		size:11,
		answer:11,
		textAlign:"center"},
		
		{compId:"ID_drop09",
		x:656.50,
		y:223.80,
		width:102,
		height:30,
		size:11,
		answer:5,
		textAlign:"center"},
		
		{compId:"ID_drop10",
        x:452.50,
        y:292.35,
        width:102,
        height:30,
        size:11,
        answer:13,
        textAlign:"center"},
		
		{compId:"ID_drop11",
		x:554.50,
		y:292.35,
		width:102,
		height:30,
		size:11,
		answer:8,
		textAlign:"center"},
		
		{compId:"ID_drop12",
        x:452.50,
        y:362.35,
        width:102,
        height:30,
        size:11,
        answer:10,
        textAlign:"center"},
		
		{compId:"ID_drop13",
		x:554.50,
		y:362.35,
		width:102,
		height:30,
		size:11,
		answer:6,
		textAlign:"center"},
		
		{compId:"ID_drop14",
		x:656.50,
		y:362.35,
		width:102,
		height:30,
		size:11,
		answer:1,
		textAlign:"center"}];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_texts = [	{compId:"ID_table01",
							x:220.30,
							y:5, 
							width:75,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},							
							{compId:"ID_table02",
							x:301.30,
							y:11.80, 
							width:151,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
							{compId:"ID_table03",
							x:454.30,
							y:11.80, 
							width:303,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
							{compId:"ID_table04",
							x:211.30,
							y:97.80, 
							width:88,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
							{compId:"ID_table05",
							x:211.30,
							y:243.80, 
							width:88,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
							{compId:"ID_table06",
							x:211.30,
							y:353.80, 
							width:88,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"center"},
							{compId:"ID_s1_drag01",
							x:308.30,
							y:81.8, 
							width:141,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"left"},
							{compId:"ID_s1_drag02",
							x:308.30,
							y:229.8, 
							width:144,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"left"},
							{compId:"ID_s1_drag03",
							x:308.30,
							y:340.8, 
							width:144,
							height:17,
							size:11,
							color:"#FFFFFF",
							textAlign:"left"},
							{compId:"ID_s3_inst",
							x:0,
							y:0, 
							width:200,
							height:17,
							size:11,
							textAlign:"left"}];

    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_images = [{compId:"ID_image01",
        name:"1_3_1_7_C.png",
        x:209,
        y:2,
        width:550,
        height:395,
        size:12,
        textAlign:"left"}];


    var submit_buttons = [{compId:"ID_s1_CHECK",
        x:10,
        y:369,
        width:100,
        height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s1_RESET",
            x:113,
            y:369,
			width:90,
			height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:236,
        y:95,
        width:190,
        height:140,
        size:12,
        image:"../../../common/images/feedback.png",
        textAlign:"left"}];
    var instobj = {ansType:""};
    
    return {templateType:template_type,
        textObject:commonTexts,
        buttonObject:buttonObject,
        slideObject:slide_texts,
        slideImages:slide_images,
        dropObject:dropObject,
		slideNo:3,
		squence:"multi",
        submitObject:submit_buttons,
        feedbackObj:feedbackObj,
	instobj:instobj
    };
}
/*3rd Activity Ends*/


