function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../../common/libs/expressInstall.swf");
}

var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
    var template_type = "IMAGE";

    var slide_images = [{name:"11_0_1_2_bg.jpg",
							x:22,
							y:56,
							width:430.35,
							height:290.1,
							type:""}];

    var slide_texts = [{compId:"ID_txt01",
							x:0,
							y:1, 
							width:460,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"left",
							Expand:"right"},
							{compId:"ID_title01",
							x:0,
							y:25, 
							width:450,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"down"}	,
							{compId:"ID_title02",
							x:0,
							y:174, 
							width:450,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"down"}	,
							{compId:"ID_txt03",
							x:152,
							y:93, 
							width:98.15,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"down"},
							{compId:"ID_txt04",
							x:245,
							y:93, 
							width:90.15,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"down"},
							{compId:"ID_txt02",
							x:60,
							y:130, 
							width:98,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"right+left"},
							{compId:"ID_txt05",
							x:318,
							y:131, 
							width:104,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"right+left"},
							{compId:"ID_txt06",
							x:12,
							y:282, 
							width:76,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"right"},
							
							{compId:"ID_txt07",
							x:93,
							y:269, 
							width:79,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"right"},
							
							{compId:"ID_txt08",
							x:174,
							y:244, 
							width:61,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"right"},
							
							{compId:"ID_txt09",
							x:310,
							y:244, 
							width:78,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"left",
							Expand:"right"},
							
							{compId:"ID_txt10",
							x:386,
							y:250, 
							width:87,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"right"}	
							,
							
							{compId:"ID_txt11",
							x:215,
							y:349, 
							width:84,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"down"},
							
							{compId:"ID_txt12",
							x:309,
							y:349, 
							width:82,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"down"},
							
							{compId:"ID_txt13",
							x:392,
							y:346, 
							width:82,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"center",
							Expand:"down"},
							
							{compId:"ID_txt14",
							x:1,
							y:381, 
							width:462,
							height:17,
							size:11,
							color:'#393536',
							textAlign:"right",
							Expand:"up"}											
							];
							 
	var slide_graphics =[];

    var slide_object = {images:slide_images,
                        texts:slide_texts,
						graphics:slide_graphics};

    return {templateType:template_type,
        slideObject:slide_object};

}

loadScript("../../../common/scripts/swfobject.js", registerSWF);