loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	
	var slide_1_type = "IMAGE";
	var slide_1_images = [{name:"arrow1.png",
							x:200,
							y:70, 
							width:13,
							height:25,
							divId:"commonImageText",scrollable:"YES",
							type:""},
							{name:"arrow2.png",
							x:202,
							y:140, 
							width:10,
							divId:"commonImageText",
							scrollable:"YES",
							height:106.15,
							type:""},
							{name:"box1.png",
							x:186.5,
							y:89, 
							width:38,
							height:53,
							scrollable:"YES",
							divId:"commonImageText",
							type:""},
							{name:"box2.png",
							x:126.75,
							y:247, 
							width:41.2,
							height:74.25,
							scrollable:"YES",
							divId:"commonImageText",
							type:""}]					
	var slide_1_texts = [{compId:"ID_s1_title",
							x:5,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_s1_txt01",
							x:218,
							y:185.85, 
							width:210,
							height:17,
							size:11,
							color:"#F68026",
							textAlign:"left"},
							{compId:"ID_s1_txt02",
							x:49,
							y:109, 
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
						{compId:"ID_s1_txt03",
							x:99,
							y:109, 
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
		{compId:"ID_s1_txt04",
							x:149,
							y:109, 
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
		{compId:"ID_s1_txt05",
							x:199,
							y:109, 
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
		{compId:"ID_s1_txt06",
							x:249,
							y:109, 
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
		{compId:"ID_s1_txt07",
							x:299,
							y:109, 
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
		{compId:"ID_s1_txt08",
							x:349,
							y:109, 
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
		{compId:"ID_s1_txt09",
							x:399,
							y:109, 
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
		{compId:"ID_s1_txt10",
							x:123.5,
							y:280, 
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
		{compId:"ID_s1_txt11",
							x:170.5,
							y:280,  
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
		{compId:"ID_s1_txt12",
							x:217,
							y:280,  
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},
		{compId:"ID_s1_txt13",
							x:263,
							y:280, 
							width:22,
							height:17,
							size:11,							
							textAlign:"left"},	
							{compId:"staticTxt",
							bodyText:'<div class="slide1"><div class="ex"><span style="padding-left:25px;">X</span><span>:</span><span>X</span><span>:</span><span>X</span><span>:</span><span>X</span><span>:</span><span>X</span><span>:</span><span>X</span><span>:</span><span>X</span><span>:</span><span style="width:29px">X</span></div><div class="line1"></div><div class="zeros"><span style="padding-left:15px;">0000</span><span style="padding-left:4px;width:44px">0000</span><span style="padding-left:7px;width:42px">0000</span><span style="padding-left:9px;width:38px">0000</span><span style="padding-left:10px;width:37px">0000</span><span style="padding-left:13px;width:37px">0000</span><span style="padding-left:12px;width:36px;">0000</span><span style="padding-left:14px;width:39px" >0000</span></div><div class="line"></div> <div class="row3" style="padding:2px 0 0 50px; font-weight:bold;"><span>:</span><span>:</span><span>:</span><span>:</span><span>:</span><span>:</span><span>:</span></div><div class="line1"></div><div class="zeros" style="padding:0;"><span style="padding-left:15px;">FFFF</span><span style="padding-left:4px;width:44px">FFFF</span><span style="padding-left:7px;width:42px">FFFF</span><span style="padding-left:9px;width:38px">FFFF</span><span style="padding-left:10px;width:37px">FFFF</span><span style="padding-left:13px;width:37px">FFFF</span><span style="padding-left:12px;width:36px;">FFFF</span><span style="padding-left:14px;width:39px" >FFFF</span></div></div>',
							x:25,
							y:55.55, 
							width:408,
							height:122,
							size:11,							
							textAlign:"center",
							},
							{compId:"staticTxt1",
							bodyText:'<div class="slide2"><div class="zeros1"><span>0000</span><span style="">0000</span><span style="">0000</span><span style="">0000</span></div><div class="zeros_2" style="" ><span>1111</span><span style="">1111</span><span style="">1111</span><span style="">1111</span></div></div>',
							x:95,
							y:260.50, 
							width:205,
							height:76,
							size:11,							
							textAlign:"center",
							}];							
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts};
							
	var slide_2_type = "IMAGE";
	var slide_2_images = [];								
	var slide_2_texts = [{compId:"ID_s2_title",
							x:20,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"staticTxt2",
							bodyText:'<div class="slideTable"><div class="row1"><span class="col1">2001</span><span class="col2">:</span><span class="col1">0DB8</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">1111</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0200</span></div><div class="row2"><span class="col1">2001</span><span class="col2">:</span><span class="col1">0DB8</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">00A3</span><span class="col2">:</span><span class="col1">ABCD</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">1234</span></div><div class="row1"><span class="col1">2001</span><span class="col2">:</span><span class="col1">0DB8</span><span class="col2">:</span><span class="col1">000A</span><span class="col2">:</span><span class="col1">0001</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0100</span></div><div class="row2"><span class="col1">2001</span><span class="col2">:</span><span class="col1">0DB8</span><span class="col2">:</span><span class="col1">AAAA</span><span class="col2">:</span><span class="col1">0001</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0200</span></div><div class="row1"><span class="col1">FE80</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0123</span><span class="col2">:</span><span class="col1">4567</span><span class="col2">:</span><span class="col1">89AB</span><span class="col2">:</span><span class="col1">CDEF</span></div>	<div class="row2"><span class="col1">FE80</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0001</span></div>		<div class="row1"><span class="col1">FF02</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0001</span></div>		<div class="row2"><span class="col1">FF02</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0001</span><span class="col2">:</span><span class="col1">FF00</span><span class="col2">:</span><span class="col1">0200</span></div>   <div class="row1"><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0001</span></div>		<div class="row2" style="border:none;"><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span><span class="col2">:</span><span class="col1">0000</span></div></div>',
							x:23,
							y:75.85, 
							width:409,
							height:122,
							size:11,							
							textAlign:"center",
							}
							]					
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts};
							
			
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			slideObject:slides};
	
}
