loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js"); 

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 790;
var STAGE_HEIGHT = 400;
var TYPE = "MULTI_BAR";
var isDD = true;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	var common_images = [];
	
	var slide_1_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal1.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_s1_traget01",
		x:36.5,
        y:128.75,
        width:80,
        height:72,
        size:11,
		tag:6,
        textAlign:"center"},     
       {compId:"ID_s1_traget02",
		x:36.5,
        y:218.75,
        width:80,
        height:72,
        size:11,
		tag:4,
        textAlign:"center"},
		{compId:"ID_s1_traget03",
		x:126.5,
        y:218.75,
        width:80,
        height:72,
        size:11,
		tag:5,
        textAlign:"center"},
	{compId:"ID_s1_traget04",
		x:126.7,
        y:128.75,
        width:80,
        height:72,
        size:11,
		tag:2,
        textAlign:"center"},
		{compId:"ID_s1_traget05",
		x:36.7,
        y:308.75,
        width:80,
        height:72,
        size:11,
		tag:1,
        textAlign:"center"},
		{compId:"ID_s1_traget06",
		x:126.7,
        y:308.75,
        width:80,
        height:72,
        size:11,
		tag:3,
        textAlign:"center"}]   
      
    var dropBox = [{compId:"a1_dt",
		x:244-5,
         y:115,
        width:81,
        height:76,
        size:11,
        answer:1,
        textAlign:"center"},
        {compId:"a2_dt",
		 x:325.85-5,
          y:115,
		 width:81,
         height:76,
         size:11,     
         answer:2,
         textAlign:"center"},
		{compId:"a3_dt",
         x:406-5,
          y:115,
         width:81,
         height:76,
         size:11,
         answer:3,
         textAlign:"center"},
        {compId:"a4_dt",
         x:487-5,
          y:115,
         width:81,
         height:76,
         size:11,
         answer:4,
         textAlign:"center"},
		{compId:"a5_dt",
		 x:568-5,
          y:115,
         width:81,
         height:76,
         size:11,
         answer:5,
         textAlign:"center"},
		{compId:"a6_dt",
         x:649-5,
          y:115,
         width:81,
         height:76,
         size:11,
         answer:6,
         textAlign:"center"},
		];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_1_texts = [
		{compId:"ID_s1_inst",
        x:36,
        y:1,
        width:218,
        height:17,
        size:11,
        textAlign:"left"},
			{compId:"ID_s1_txt01",
            x:242-5,
            y:69.4,
            width:485,
            height:17,
            size:11,
            textAlign:"center"},
			{compId:"ID_s1_txt02",
			x:243.05-5,
        y:217.45,
        width:80.15,
        height:73.95,
            size:11,
            textAlign:"center"},
			{compId:"ID_s1_txt03",
			x:323.8-5,
			y:217.45,
            width:82.65,
            height:17,
            size:11,
            textAlign:"center"},
			{compId:"ID_s1_txt04",
			x:403.55-5,
            y:217.45,
            width:82.65,
            height:17,
            size:11,
            textAlign:"center"},
		    {compId:"ID_s1_txt05",
			x:485.3-5,
            y:217.45,
            width:82.65,
            height:17,
            size:11,
            textAlign:"center"},
		    {compId:"ID_s1_txt06",
			x:566-5,
            y:217.45,
            width:82.65,
            height:17,
            size:11,
            textAlign:"center"},
		    {compId:"ID_s1_txt07",
			x:646.8-5,
            y:217.45,
            width:82.65,
            height:17,
            size:11,
            textAlign:"center"},
    ];
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_1_images = [{name:"bg1.png",
							x:244-5,
							y:113, 
							width:485,
							height:149,
							type:""}];
    var submit_buttons = [{compId:"ID_s1_CHECK",
        x:550,
        y:362,
        width:80,
		height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s1_RESET",
             x:655,
			 y:362,
             width:80,
			 height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];

	

    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:36,
        y:155,
        width:170,
        height:98,
        size:11,
        image:"../../../common/images/feedback4.png",
        textAlign:"left"}];
    var instobj = {ansType:"many-one",clue:1};
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							
							texts:slide_1_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_1_texts,
							slideImages:slide_1_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
	
	/* Slide 2 */
	var slide_2_type = "DRAG_DROP";
    var buttonStyle = {
		normalSkinImage:"drag_normal.png",
		//normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

  var buttons = [{compId:"ID_s2_traget03",
		x:36.5,
        y:128.75,
        width:80,
        height:72,
        size:11,
		tag:3,
        textAlign:"center"},     
       {compId:"ID_s2_traget01",
		x:126.5,
        y:128.75,
        width:80,
        height:72,
        size:11,
		tag:1,
        textAlign:"center"},
		{compId:"ID_s2_traget04",
		x:36.5,
        y:218.75,
        width:80,
        height:72,
        size:11,
		tag:4,
        textAlign:"center"},
	{compId:"ID_s2_traget05",
		x:126.7,
        y:218.75,
        width:80,
        height:72,
        size:11,
		tag:5,
        textAlign:"center"},
		{compId:"ID_s2_traget02",
		x:36.7,
        y:308.75,
        width:80,
        height:72,
        size:11,
		tag:2,
        textAlign:"center"},
		{compId:"ID_s2_traget06",
		x:126.7,
        y:308.75,
        width:80,
        height:72,
        size:11,
		tag:6,
        textAlign:"center"}] 
      
    var dropBox = [{compId:"b1_dt",
		x:244-5,
        y:115,
        width:81,
        height:76,
        size:11,
        answer:1,
        textAlign:"center"},
        {compId:"b2_dt",
		 x:325.85-5,
         y:115,
		 width:81,
         height:76,
         size:11,     
         answer:2,
         textAlign:"center"},
		{compId:"b3_dt",
         x:406-5,
         y:115,
         width:81,
         height:76,
         size:11,
         answer:3,
         textAlign:"center"},
        {compId:"b4_dt",
         x:487-5,
         y:115,
         width:81,
         height:76,
         size:11,
         answer:4,
         textAlign:"center"},
		{compId:"b5_dt",
		 x:568-5,
         y:115,
         width:81,
         height:76,
         size:11,
         answer:5,
         textAlign:"center"},
		{compId:"b6_dt",
         x:649-5,
         y:115,
         width:81,
         height:76,
         size:11,
         answer:6,
         textAlign:"center"},
		];


    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_2_texts = [
		{compId:"ID_s2_inst",
        x:36,
        y:1,
        width:218,
        height:17,
        size:11,
        textAlign:"left"},
		{compId:"ID_s2_txt01",
           x:242-5,
           y:69.4,
           width:485,
           height:17,
           size:11,
           textAlign:"center"},
		{compId:"ID_s2_txt02",
			x:246.05-5,
			y:217.45,
			width:80.15,
			height:73.95,
            size:11,
            textAlign:"center"},
		{compId:"ID_s2_txt03",
			x:323.8-5,
			y:217.45,
            width:82.65,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_s2_txt04",
			x:403.55-5,
            y:217.45,
            width:82.65,
            height:17,
            size:11,
            textAlign:"center"},
		 {compId:"ID_s2_txt05",
			x:485.3-5,
            y:217.45,
            width:82.65,
            height:17,
            size:11,
            textAlign:"center"},
		  {compId:"ID_s1_txt06",
			x:566-5,
            y:217.45,
            width:82.65,
            height:17,
            size:11,
            textAlign:"center"},
		   {compId:"ID_s2_txt07",
			x:646.8-5,
            y:217.45,
            width:82.65,
            height:17,
            size:11,
            textAlign:"center"},
    ];
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_2_images = [{name:"bg1.png",
							x:244-5,
							y:113, 
							width:485,
							height:149,
							type:""},
							];
    var submit_buttons = [{compId:"ID_s2_CHECK",
        x:550,
        y:362,
        width:80,
		height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s2_RESET",
             x:655,
			 y:362,
             width:80,
			 height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:36,
        y:155,
        width:170,
        height:98,
        size:11,
        image:"../../../common/images/feedback2.png",
        textAlign:"left"}];
    var instobj = {ansType:"many-one",clue:1};
	
 var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_2_texts,
							slideImages:slide_2_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };

 /* Slide 3 */
	var slide_3_type = "DRAG_DROP";
    var buttonStyle = {
		normalSkinImage:"drag_normal.png",
		//normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

  var buttons = [{compId:"ID_s3_traget01",
		x:32-10-20,
        y:282.85,
        width:65,
        height:74,
        size:11,
		tag:6,
        textAlign:"center"},     
       {compId:"ID_s3_traget02",
		x:95.15+15-25,
        y:282.85,
        width:65,
        height:74,
        size:11,
		tag:7,
        textAlign:"center"},
		{compId:"ID_s3_traget03",
		x:177.45+15-25,
        y:282.85,
        width:65,
        height:74,
        size:11,
		tag:8,
        textAlign:"center"},
	{compId:"ID_s3_traget04",
		x:259.75+15-25,
        y:282.85,
        width:65,
        height:74,
        size:11,
		tag:9,
        textAlign:"center"},
		{compId:"ID_s3_traget05",
		x:342.05+15-25,
        y:282.85,
        width:65,
        height:74,
        size:11,
		tag:1,
        textAlign:"center"},
		{compId:"ID_s3_traget06",
		x:424.35+15-25,
        y:282.85,
        width:65,
        height:74,
        size:11,
		tag:4,
        textAlign:"center"},
	  {compId:"ID_s3_traget07",
       x:506.65+15-25,
        y:282.85,
        width:65,
        height:74,
        size:11,
        tag:2,
        textAlign:"center"},
		{compId:"ID_s3_traget08",
       x:588.95+15-25,
         y:282.85,
        width:65,
        height:74,
        size:11,
        tag:3,
        textAlign:"center"},
		{compId:"ID_s3_traget09",
       x:671.25+15-25,
       y:282.85,
        width:65,
        height:74,
        size:11,
       tag:5,
        textAlign:"center"},]   
      
    var dropBox = [{compId:"c1_dt",
						x:100,
						y:114,
						width:65,
						height:74,
						size:11,
						answer:1,
						textAlign:"center"},
					{compId:"c2_dt",
						x:156.8+4,
						y:114,
						width:65,
						height:74,
						size:11,     
						answer:2,
						textAlign:"center"},
					{compId:"c3_dt",
						x:218.5+4,
						y:114,
						width:65,
						height:74,
						size:11,
						answer:3,
						textAlign:"center"},
					{compId:"c4_dt",
						x:280.15+4,
						y:114,
						width:65,
						height:74,
						size:11,
						answer:4,
						textAlign:"center"},
					{compId:"c5_dt",
						x:342.45+4,
						y:114,
						width:65,
						height:74,
						size:11,
						answer:5,
						textAlign:"center"},
					{compId:"c6_dt",
						x:404.15+4,
						y:114,
						width:65,
						height:74,
						size:11,
						answer:6,
						textAlign:"center"},
					{compId:"c7_dt",
						x:466.45+4,
						y:114,
						width:65,
						height:74,
						size:11,
						answer:7,
						textAlign:"center"},
					{compId:"c8_dt",
						x:528+4,
						y:114,
						width:65,
						height:74,
						size:11,
						answer:8,
						textAlign:"center"},
					{compId:"c9_dt",
						x:590+4,
						y:114,
						width:65,
						height:74,
						size:11,
						answer:9,
						textAlign:"center"}];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_3_texts = [{compId:"ID_s3_inst",
							x:36,
							y:1,
							width:375,
							height:17,
							size:11,
							textAlign:"left"},
						{compId:"ID_s3_txt01",
						   x:99,
						   y:69.4,
						   width:556,
						   height:157,
						   size:11,
						   textAlign:"center"},
						{compId:"ID_s3_txt02",
							x:99.05,
							y:217.45,
							width:60,
							height:76,
							size:11,
							textAlign:"center"},
						{compId:"ID_s3_txt03",
							x:160.8,
							y:217.45,
							width:60,
							height:17,
							size:11,
							textAlign:"center"},
						{compId:"ID_s3_txt04",
							x:224.55,
							y:217.45,
							width:60,
							height:17,
							size:11,
							textAlign:"center"},
						 {compId:"ID_s3_txt05",
							x:286.3,
							y:217.45,
							width:60,
							height:17,
							size:11,
							textAlign:"center"},
						  {compId:"ID_s3_txt06",
							x:348,
							y:217.45,
							width:60,
							height:17,
							size:11,
							textAlign:"center"},
						   {compId:"ID_s3_txt07",
							x:410.8,
							y:217.45,
							width:60,
							height:17,
							size:11,
							textAlign:"center"},
						{compId:"ID_s3_txt08",
							x:471.9,
							y:217.45,
							width:60,
							height:17,
							size:11,
							textAlign:"center"},
						{compId:"ID_s3_txt09",
							x:533.2,
							y:217.45,
							width:60,
							height:17,
							size:11,
							textAlign:"center"},
						{compId:"ID_s3_txt10",
							x:595.5,
							y:217.45,
							width:60,
							height:17,
							size:11,
							textAlign:"center"}];
							
    var dropObject = {style:buttonStyle,dropBox:dropBox};

      var slide_3_images = [{name:"bg2.png",
							x:100,
							y:114, 
							width:557,
							height:148,
							type:""}];
    var submit_buttons = [{compId:"ID_s3_CHECK",
        x:547,
        y:362,
        width:80,
		height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s3_RESET",
             x:652,
			 y:362,
             width:80,
			 height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:300,
        y:246,
        width:170,
        height:98,
        size:11,
        image:"../../../common/images/feedback2.png",
        textAlign:"left"}];
   var instobj = {ansType:"many-one",clue:1};
	
 var slide_3_object = {templateType:slide_3_type,
							x:0,
							y:0,
							images:slide_3_images,
							texts:slide_3_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_3_texts,
							slideImages:slide_3_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
		
			
	
															
	var slides = [slide_1_object,slide_2_object,slide_3_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
		    images:common_images,
			slideObject:slides,
			buttonBarPos:{x:718}};
	
}



