
loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [{compId:"ID_inst",
							x:4.95,
							y:379, 
							width:460,
							height:17,
							size:12,
							textAlign:"left"}];
	
	var slide_1_type = "IMAGE";
	var slide_1_images = [{name:"6_4_2_1_A.png",
							x:1,
							y:13, 
							width:430.3,
							height:108.25,
							type:""},
							{name:"6_4_2_1.png",
							x:2,
							y:153.4, 
							width:418.15,
							height:340.05,
							type:""},
							{name:"arrow.png",
							x:150,
							y:92, 
							width:10,
							height:85.05,
							type:""}							
							];								
	var slide_1_texts = [{compId:"ID_txt20",
							bodyText:"<table width='376' border='0' cellpadding='0' cellspacing='0' style='font-family:'Courier New', Courier, monospace; font-size:11px;'><tr><td width='729'>R1#<b style='font-weight:bold'>conf t</b></td></tr><tr><td>Enter configuration commands, one per line.  End with CNTL/Z.</td></tr><tr><td>R1(config)#</td></tr><tr><td>R1(config)#<b style='font-weight:bold'>interface gigabitethernet 0/0</b></td></tr><tr><td>R1(config-if)#<b style='font-weight:bold'>ip address 192.168.10.1 255.255.255.0</b></td></tr><tr><td>R1(config-if)#<b style='font-weight:bold'>description Link to LAN-10</b></td></tr><tr><td>R1(config-if)#<b style='font-weight:bold'>no shutdown</b></td></tr><tr><td>%LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to up</td></tr><tr><td>%LINEPROTO-5-UPDOWN: Line protocol on Interface</td></tr><tr><td>GigabitEthernet0/0, changed state to up</td></tr><tr><td>R1(config-if)#<b style='font-weight:bold'>exit</b></td></tr><tr><td>R1(config)#</td></tr><tr><td>R1(config)#<b style='font-weight:bold'>int g0/1</b></td></tr><tr><td>R1(config-if)#<b style='font-weight:bold'>ip add 192.168.11.1 255.255.255.0</b></td></tr><tr><td>R1(config-if)#<b style='font-weight:bold'>des Link to LAN-11</b></td></tr><tr><td>R1(config-if)#<b style='font-weight:bold'>no shut</b></td></tr><tr><td>%LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to up</td></tr><tr><td>%LINEPROTO-5-UPDOWN: Line protocol on Interface</td></tr><tr><td>GigabitEthernet0/1, changed state to up</td> </tr><tr><td>R1(config-if)#<b style='font-weight:bold'>exit</b></td></tr><tr><td>R1(config)#</td></tr><tr><td></td></tr></table>",
							x:26,
							y:164.4, 
							width:393.15,
							height:250.05,
							size:11,
							scroll:"yes",
							color:"#3c3d3f",
							textAlign:"left",
							},
							{compId:"ID_txt01",
							 bodyText:'PC1',
							 x:20.45,
							 y:18.9, 
							 width:38,
							 height:17,
							 size:10,
							 color:"white",
							 textAlign:"left",
							 },
							 {compId:"ID_txt02",
							 bodyText:'PC2',
							 x:20.55,
							 y:90.85, 
							 width:38.9,
							 height:17,
							 size:10,
							 font:"bold",
							 color:"white",
							 textAlign:"left",
							 },
							 {compId:"ID_txt03",
							 bodyText:'.10',
							 x:42.55,
							 y:18.1, 
							 width:28.9,
							 height:17,
							 size:11,
							 textAlign:"center",
							 },
							 {compId:"ID_txt04",
							 bodyText:'.10',
							 x:43.55,
							 y:90.6, 
							 width:27,
							 height:17,
							 size:11,
							 textAlign:"center",
							 },
							 {compId:"ID_txt05",
							 bodyText:'<b>192.168.10.0/24</b>',
							 x:69.45,
							 y:9, 
							 width:104,
							 height:17,
							 size:11,
							 textAlign:"left",
							 },
							 {compId:"ID_txt06",
							 bodyText:'<b>192.168.11.0/24</b>',
							 x:69.45,
							 y:117.9, 
							 width:104,
							 height:17,
							 size:11,
							 textAlign:"left",
							 },
							 {compId:"ID_txt07",
							 bodyText:'G0/0<br/>.1',
							 x:100.1,
							 y:27.8, 
							 width:51,
							 height:27,
							 size:11,
							 textAlign:"right",
							 },
							 {compId:"ID_txt08",
							 bodyText:'.1<br/>G0/1',
							 x:110.15,
							 y:83.9, 
							 width:41.05,
							 height:31,
							 size:11,
							 textAlign:"right",
							 },
							 {compId:"ID_txt09",
							 bodyText:'<b>R1</b>',
							 x:150.35,
							 y:71.15, 
							 width:25.9,
							 height:11.65,
							 size:10,
							 color:"white",
							 textAlign:"center",
							 },
							 {compId:"ID_txt10",
							 bodyText:'<b>R2</b>',
							 x:271.05,
							 y:71.15, 
							 width:25.9,
							 height:11.65,
							 size:10,
							 color:"white",
							 textAlign:"center",
							 },
							 {compId:"ID_txt11",
							 bodyText:'.225<br/>S0/0/0',
							 x:178.3,
							 y:70.45, 
							 width:34.3,
							 height:31,
							 size:11,
							 textAlign:"center",
							 },
							 {compId:"ID_txt12",
							 bodyText:'.226',
							 x:245.25,
							 y:63.9, 
							 width:34.3,
							 height:31,
							 size:11,
							 textAlign:"left",
							 },
							 {compId:"ID_txt13",
							 bodyText:'<b>209.165.200.224 /30</b>',
							 x:177.45,
							 y:40.45, 
							 width:104,
							 height:17,
							 size:11,
							 textAlign:"left",
							 },
							 {compId:"ID_txt14",
							 bodyText:'.1',
							 x:302.25,
							 y:31.1, 
							 width:27,
							 height:17,
							 size:11,
							 textAlign:"left",
							 },
							 {compId:"ID_txt15",
							 bodyText:'.1',
							 x:302.1,
							 y:88, 
							 width:27,
							 height:17,
							 size:11,
							 textAlign:"left",
							 },
							 {compId:"ID_txt16",
							 bodyText:'<b>10.1.1.0/24</b>',
							 x:333.45,
							 y:9, 
							 width:104,
							 height:17,
							 size:11,
							 textAlign:"left",
							 },
							 {compId:"ID_txt17",
							 bodyText:'<b>10.1.2.0/24</b>',
							 x:333.25,
							 y:117.8, 
							 width:104,
							 height:17,
							 size:11,
							 textAlign:"left",
							 },
							 {compId:"ID_txt18",
							 bodyText:'.10',
							 x:385.25,
							 y:18.5, 
							 width:27,
							 height:17,
							 size:11,
							 textAlign:"left",
							 },
							 {compId:"ID_txt19",
							 bodyText:'.10',
							 x:385.9,
							 y:90, 
							 width:27,
							 height:17,
							 size:11,
							 textAlign:"left",
							 }];							
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts};
							
							
	var slide_2_type = "SYNTAX_CHECKER";							
	var slide_2_texts = [{compId:"ID_SC_title",
							x:5,
							y:2, 
							width:390,
							height:17,
							size:11,								
							textAlign:"center"}];
												
	var slide_2_object = {templateType:slide_2_type,
								texts:slide_2_texts,
        						syntax:"sc1"};
								
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			slideObject:slides};
	
}