loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/DragDropSlide.js");


function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}

var STAGE_WIDTH = 770;
var STAGE_HEIGHT = 400;

function getData()
{
    var template_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:["1.png","2.png","3.png","4.png","5.png","6.png","7.png","8.png"],
       overSkinImage:"graphicwirecoverblank.png",
       dropNormalSkinImage:"graphicwirecoverblank.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"drag05",
						x:99.1,
						y:114.85,
						width:19.3,
						height:106,
						size:11,
						tag:5,			
						textAlign:"center"},
					{compId:"drag06",
					   x:129.1,
						y:114.85,
					   width:19.3,
						height:106,
						size:11,
						tag:6,
						textAlign:"center"},
					{compId:"drag07",
						x:159.1,
						y:114.85,
						width:19.3,
						height:106,
						color:"#45505B",
						size:11,
						tag:7,
						textAlign:"center"},
					{compId:"drag08",
						x:189.1,
						y:114.85,
						width:19.3,
						height:106,
						size:11,
						tag:8,			
						textAlign:"center"},
					{compId:"drag1",
						x:99.1,
						y:250.75,
						width:19.3,
						height:106,
						size:11,
						tag:1,			
						textAlign:"center"},
					{compId:"drag02",
						x:129.1,
						y:250.75,
						width:19.3,
						height:106,
						size:11,	
						tag:2,		
						textAlign:"center"},
					{compId:"drag03",
						x:159.1,
						y:250.75,
						width:19.3,
						height:106,
						size:11,
						tag:3,			
						textAlign:"center"},
					{compId:"drag04",
						x:189.1,
						y:250.75,
						width:19.3,
						height:106,
						size:11,
						tag:4,			
						textAlign:"center"}];


    var dropBox = [{compId:"ID_drop01",
						x:490,
						y:54,
						width:19.3,
						height:106,
						size:11,
						answer:6,
						textAlign:"center"},
					{compId:"ID_drop02",
						x:515,
						y:54,
						width:19.3,
						height:106,
						size:11,
						answer:5,
						textAlign:"center"},
					{compId:"ID_drop03",
						x:515+25,
						y:54,
						width:19.3,
						height:106,
						size:11,
						answer:2,
						textAlign:"center"},
					{compId:"ID_drop04",
						x:515+50,
						y:54,
						width:19.3,
						height:106,
						size:11,
						answer:7,
						textAlign:"center"},
					{compId:"ID_drop05",
						x:515+75,
						y:54,
						width:19.3,
						height:106,
						size:11,
						answer:8,
						textAlign:"center"},
					{compId:"ID_drop06",
						x:515+75+25,
						y:54,
						width:19.3,
						height:106,
						size:11,
						answer:1,
						textAlign:"center"},
					{compId:"ID_drop07",
						x:515+75+50,
						y:54,
						width:19.3,
						height:106,
						size:11,
						answer:4,
						textAlign:"center"},
					{compId:"ID_drop08",
						x:515+70+75,
						y:54,
						width:19.3,
						height:106,
						size:11,
						answer:3,
						textAlign:"center"}];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_texts = [{compId:"ID_s1_title",
							x:1,
							y:1, 
							width:300,
							height:17,
							size:11,							
							textAlign:"left",
							expand:"down"},
						{compId:"ID_txt01_1",
							x:1,
							y:1, 
							width:300,
							height:17,
							size:11,							
							textAlign:"left",
							expand:"down"},
						{compId:"ID_txt01",
							x:521.2,
							y:190.9, 
							width:128.9,
							height:41.9,
							size:11,							
							textAlign:"center",
							expand:"down"},
							{compId:"ID_fig_title",
							x:477,
							y:-4, 
							width:213.9,
							height:41.9,
							size:11,							
							textAlign:"center",
							expand:"down"}];

    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_images = [{compId:"ID_image01",
							name:"9_4_2_71.png",
							x:470,
							y:10,
							width:243,
							height:389.85,
							size:11,
							textAlign:"left"},
						{compId:"wire",
							name:"graphicwire.png",
							x:490,
							y:15,
							width:19.15,
							height:46.95,
							size:11,
							textAlign:"left"},
						{compId:"wire1",
							name:"graphicwire.png",
							x:515,
							y:15,
							width:19.15,
							height:46.95,
							size:11,
							textAlign:"left"},
						{compId:"wire2",
							name:"graphicwire.png",
							x:515+25,
							y:15,
							width:19.15,
							height:46.95,
							size:11,
							textAlign:"left"},
						{compId:"wire3",
							name:"graphicwire.png",
							x:515+25+25,
							y:15,
							width:19.15,
							height:46.95,
							size:11,
							textAlign:"left"},
						{compId:"wire4",
							name:"graphicwire.png",
							x:515+25+50,
							y:15,
							width:19.15,
							height:46.95,
							size:11,
							textAlign:"left"},
						{compId:"wire5",
							name:"graphicwire.png",
							x:515+25+75,
							y:15,
							width:19.15,
							height:46.95,
							size:11,
							textAlign:"left"},
						{compId:"wire6",
							name:"graphicwire.png",
							x:515+25+75+25,
							y:15,
							width:19.15,
							height:46.95,
							size:11,
							textAlign:"left"},
						{compId:"wire7",
							name:"graphicwire.png",
							x:515+25+70+50,
							y:15,
							width:19.15,
							height:46.95,
							size:11,
							textAlign:"left"}];


   var submit_buttons = [{compId:"ID_CHECK",
								x:702,
								y:329,
								width:90,
								height:21,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"},
						{compId:"ID_RESET",
								x:702,
								y:359,
								width:90,
								height:21,
								size:11,
								normalSkinImage:"../../../common/images/btn_normal.png",
								textAlign:"center"}];


    var feedbackObj = [{compId:"ID_FEEDBACK",
								x:221,
								y:113,
								width:172,
								height:10,
								size:12,
								image:"../../../common/images/feedback.png",
								textAlign:"left"}];
								
    var instobj = {ansType:""};
    
    return {templateType:template_type,
        textObject:commonTexts,
        buttonObject:buttonObject,
        slideObject:slide_texts,
        slideImages:slide_images,
        dropObject:dropObject,
        submitObject:submit_buttons,
        feedbackObj:feedbackObj,
		instobj:instobj};

}


