loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/DragDropSlide.js");


function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}

var STAGE_WIDTH = 780;
var STAGE_HEIGHT = 388;

function getData()
{
    var template_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        //dropNormalSkinImage:"../../../common/images/drop_normal.png",
		dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_pdu03_DS",
            x:58,
            y:120,
            width:124,
            height:46,
            size:11,
			color:"#45505B",
            textAlign:"center"},
        {compId:"ID_pdu05_DS",
            x:58,
            y:172,
            width:124,
            height:46,
			color:"#45505B",
            size:11,
            textAlign:"center"},
		{compId:"ID_pdu04_DS",
			x:58,
            y:224,
            width:124,
            height:46,
			color:"#45505B",
            size:11,
            textAlign:"center"},
		{compId:"ID_pdu01_DS",
            x:58,
            y:276,
            width:124,
            height:46,
            size:11,
			color:"#45505B",
            textAlign:"center"},
		{compId:"ID_pdu02_DS",
			x:58,
			y:328,
			width:124,
            height:46,
			color:"#45505B",
            size:11,
			textAlign:"center"}];


    var dropBox = [{compId:"ID_drop01",
        x:614.95,
        y:47,
        width:122,
        height:45,
        size:11,
        answer:4,
        textAlign:"center"},
        {compId:"ID_drop02",
            x:614.95,
            y:115.5,
            width:122,
        height:45,
            size:11,
            answer:5,
            textAlign:"center"},
        {compId:"ID_drop03",
            x:614.95,
            y:194,
           width:122,
        height:45,
            size:11,
            answer:1,
            textAlign:"center"},
		{compId:"ID_drop04",
            x:614.95,
            y:246.5,
           width:122,
			height:45,
            size:11,
            answer:3,
            textAlign:"center"},
		{compId:"ID_drop05",
            x:614.95,
            y:296.5,
          width:122,
        height:45,
            size:11,
            answer:2,
            textAlign:"center"},
    ];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [{compId:"ID_inst",
        x:6.35,
        y:9.85,
        width:250,
        height:17,
        size:11,
        textAlign:"left"},
        {compId:"ID_title",
            x:120,
            y:2,
            width:300,
            height:17,
            size:16,
            textAlign:"center"}];
    var slide_texts = [{compId:"ID_title",
							x:10,
							y:2, 
							width:460,
							height:17,
							size:16,
							textAlign:"center"},
						
						{compId:"ID_txt01",
							x:369.2,
							y:47.3, 
							width:150,
							height:17,
							size:11,
							color:"#000000",
							textAlign:"center"},

						{compId:"ID_txt02",
							x:369.2,
							y:95.6, 
							width:47,
							height:17,
							size:11,
							color:"#000000",
							textAlign:"center"},

						{compId:"ID_txt03",
							x:417.2,
							y:95.6, 
							width:57,
							height:17,
							size:11,
							color:"#000000",
							textAlign:"center"},

					{compId:"ID_txt04",
							x:470.85,
							y:95.6, 
							width:50,
							height:17,
							size:11,
							color:"#000000",
							textAlign:"center"},
						
					{compId:"ID_txt05",
							x:405.85,
							y:145, 
							width:63,
							height:17,
							size:11,
							color:"#000000",
							textAlign:"center"},
						
					{compId:"ID_txt06",
							x:470.85,
							y:145, 
							width:50,
							height:17,
						  	size:11,
						    color:"#000000",
							textAlign:"center"},
					
					{compId:"ID_txt07",
							x:350,
							y:195, 
							width:56.55,
							height:17,
							size:11,
						    color:"#000000",
							textAlign:"center"},
						
					{compId:"ID_txt08",
							x:410,
							y:195, 
							width:60,
							height:17,
							size:11,							
						    color:"#000000",
							textAlign:"center"},
						
					{compId:"ID_txt09",
							x:469.85,
							y:195, 
							width:51,
							height:17,
						  	size:11,
						    color:"#000000",
							textAlign:"center"},

						{compId:"ID_txt10",
							x:292.85,
							y:247, 
							width:56.55,
							height:30,
						  	size:11,
						    color:"#000000",
							textAlign:"center"},


							{compId:"ID_txt11",
							x:350,
							y:247, 
							width:56.55,
							height:30,
						  	size:11,
						    color:"#000000",
							textAlign:"center"},


							{compId:"ID_txt12",
							x:410,
							y:247, 
							width:60,
							height:17,
							size:11,
						    color:"#000000",
							textAlign:"center"},


							{compId:"ID_txt13",
							x:470,
							y:247, 
							width:51,
							height:17,
							size:11,
						    color:"#000000",
							textAlign:"center"},

							{compId:"ID_txt14",
							x:523,
							y:247, 
							width:56.55,
							height:30,
						  	size:11,
						    color:"#000000",
							textAlign:"center"},


						{compId:"ID_txt15",
							x:303,
							y:305, 
							width:106.55,
							height:30,
							size:12,
						    color:"#000000",
							textAlign:"center"},

						{compId:"ID_txt16",
							x:618.25,
							y:9.1, 
							width:135.9,
							height:17,
							size:11,
						    color:"#000000",
							textAlign:"center"},
						{compId:"ID_drag_header",
							x:44.5,
							y:90, 
							width:154.8,
							height:17,
							size:11,
						    color:"#000000",
							textAlign:"center"},
						{compId:"ID_drop_header",
							x:483.55,
							y:18, 
							width:148.9,
							height:17,
							size:11,
						    color:"#000000",
							textAlign:"center"}

						];

    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_images = [{compId:"ID_image01",
        name:"man.png",
        x:302.05,
        y:30,
        width:85,
        height:76,
        size:12,
        textAlign:"left"},
		{compId:"ID_image02",
        name:"conncetor.png",
        x:343.9,
        y:39.65,
        width:368.8,
        height:342.8,
        size:12,
        textAlign:"left"},
		{compId:"ID_image03",
        name:"arrowdown.png",
        x:744.8,
        y:34,
        width:10,
        height:271.95,
        size:12,
        textAlign:"left"},
		{compId:"ID_image04",
        name:"bg.png",
        x:488.9,
        y:48.2,
        width:130.35,
        height:243.8,
        size:12,
        textAlign:"left"},
		{compId:"ID_image05",
        name:"whitebg.png",
        x:469.9,
        y:249,
        width:2,
        height:38,
        size:12,
        textAlign:"left"},
		{compId:"ID_image06",
        name:"whitebg.png",
        x:418.9,
        y:97.2,
        width:2,
        height:39,
        size:12,
        textAlign:"left"},
	{compId:"ID_image07",
        name:"whitebg.png",
        x:469.9,
        y:97.2,
        width:2,
        height:39,
        size:12,
        textAlign:"left"},
		{compId:"ID_image08",
        name:"whitebg.png",
        x:469.9,
        y:147.2,
        width:2,
        height:38,
        size:12,
        textAlign:"left"},
		{compId:"ID_image09",
        name:"whitebg.png",
        x:468.9,
        y:197,
        width:2,
        height:38,
        size:12,
        textAlign:"left"},
	{compId:"ID_image10",
        name:"graybg.png",
        x:44.5,
        y:108.5,
        width:157,
        height:274.95,
        size:12,
        textAlign:"left"}];



   var submit_buttons = [{compId:"ID_CHECK",
        x:600,
        y:370,
        width:81,
        height:21,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_RESET",
          x:680,
          y:370,
			width:81,
			height:21,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:298,
        y:79,
        width:231,
        height:170,
        size:11,
        image:"../../../common/images/feedback3.png",
        textAlign:"left"}];
    var instobj = {ansType:""};
    
    return {templateType:template_type,
        textObject:commonTexts,
        buttonObject:buttonObject,
        slideObject:slide_texts,
        slideImages:slide_images,
        dropObject:dropObject,
        submitObject:submit_buttons,
        feedbackObj:feedbackObj,
		
	instobj:instobj
    };

}


