loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/DragDropSlide.js");


function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}

var STAGE_WIDTH = 770;
var STAGE_HEIGHT = 400;

function getData()
{
    var template_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        //dropNormalSkinImage:"../../../common/images/drop_normal.png",
		dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_drag01",
             x:105,
            y:335.8-10,
            width:110,
            height:35,
            size:0,			
            textAlign:"center"},
        {compId:"ID_drag02",
            x:226,
            y:335.8-10,
            width:110,
            height:35,
            size:0,
            textAlign:"center"},
		{compId:"ID_drag03",
			x:345.95,
            y:335.8-10,
			width:110,
            height:35,
			color:"#45505B",
            size:0,
            textAlign:"center"},
		{compId:"ID_drag04",
            x:105,
            y:374-10,
           width:110,
            height:35,
            size:0,			
            textAlign:"center"},
		{compId:"ID_drag05",
			 x:226.2,
            y:374-10,
            width:110,
            height:35,
            size:0,			
            textAlign:"center"},
		{compId:"ID_drag06",
			x:345.95,
            y:374-10,
            width:110,
            height:35,
			color:"#45505B",
            size:0,
            textAlign:"center"}];


    var dropBox = [{compId:"ID_drop01",
        x:661.45,
        y:90-12,
        width:110,
        height:35,
        size:11,
        answer:2,
        textAlign:"center"},
        {compId:"ID_drop02",
        x:661.45,
        y:129.35-12,
        width:110,
        height:35,
        size:11,
        answer:1,
        textAlign:"center"},
        {compId:"ID_drop03",
        x:661.45,
        y:168.35-12,
        width:110,
        height:35,
        size:11,
        answer:3,
        textAlign:"center"},
		{compId:"ID_drop04",
        x:661.45,
        y:208.45-12,
        width:110,
        height:35,
        size:11,
        answer:4,
        textAlign:"center"},
		{compId:"ID_drop05",
        x:661.45,
        y:249.6-12,
        width:110,
        height:35,
        size:11,
        answer:5,
        textAlign:"center"},
		{compId:"ID_drop06",
        x:661.15,
        y:291.8-12,
        width:110,
        height:35,
        size:11,
        answer:6,
        textAlign:"center"}];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_texts = [{compId:"ID_inst",
							x:2,
							y:1, 
							width:710,
							height:27.05,
							size:11,
							expand:"up",							
							textAlign:"left"},
							{compId:"ID_txt01",
							x:254.45,
							y:57.9, 
							width:228,
							height:13.35,
							size:11,
							expand:"up",							
							textAlign:"center"},

						{compId:"ID_txt02",
							x:660.45,
							y:57.9, 
							width:110,
							height:13.35,
							size:11,
							expand:"up",								
							textAlign:"center"},

						{compId:"ID_txt03",
							x:103,
							y:91-12, 
							width:545,
							height:30,
							size:11,
							expand:"down",						
							textAlign:"left"},
					{compId:"ID_txt04",
							x:103,
							y:128.8-12, 
							width:545,
							height:30,
							size:11,
							expand:"down",							
							textAlign:"left"},
					{compId:"ID_txt05",
							x:103,
							y:168.8-12, 
							width:545,
							height:30,
							size:11,
							expand:"down",							
							textAlign:"left"},
					{compId:"ID_txt06",
							x:103,
							y:209.45-12, 
							width:545,
							height:30,
							size:11,
							expand:"down",							
							textAlign:"left"},
					{compId:"ID_txt07",
							x:103,
							y:250.45-12, 
							width:545,
							height:30,
							size:11,
							expand:"down",							
							textAlign:"left"},
					{compId:"ID_txt08",
							x:103,
							y:291.8-12, 
							width:545,
							height:30,
							size:11,
							expand:"down",							
							textAlign:"left"}				
						];

    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_images = [{compId:"ID_image01",
        name:"bg_img.png",
        x:97.05,
        y:50,
        width:676.85,
        height:264.4,
        size:11,
        textAlign:"left"},
		];


   var submit_buttons = [{compId:"ID_CHECK",
        x:610,
        y:352,
        width:120,
        height:21,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_RESET",
          x:703,
          y:352,
			width:120,
			height:21,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:261,
        y:140,
        width:172,
        height:10,
        size:12,
        image:"../../../common/images/feedback.png",
        textAlign:"left"}];
    var instobj = {ansType:""};
    
    return {templateType:template_type,
        textObject:commonTexts,
        buttonObject:buttonObject,
        slideObject:slide_texts,
        slideImages:slide_images,
        dropObject:dropObject,
        submitObject:submit_buttons,
        feedbackObj:feedbackObj,
	instobj:instobj
    };

}