loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [{compId:"ID_txt01",
							x:194.2,
							y:60.95, 
							width:73.5,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt02",
							x:55.2,
							y:136.45, 
							width:65,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt03",
							x:336.8,
							y:136.95, 
							width:71,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt04",
							x:168.2,
							y:136.75, 
							width:105.4,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt05",
							x:152.2,
							y:180.75, 
							width:155.4,
							height:17,
							size:11,
							textAlign:"center"}]
		
	var commonImages = [{name:"5.2.1.2.png",
							x:50.75,
							y:80, 
							width:336.6,
							height:118.5,
							type:""}];
	
var slide_1_type = "IMAGE";
	var slide_1_images = [{name:"blkLeft.png",
							x:100.5,
							y:108.35, 
							width:100,
							height:58,
							type:""},
							{name:"blkRight.png",
							x:238.65,
							y:108.35, 
							width:100,
							height:58,
							type:""}];								
	var slide_1_texts = [{compId:"ID_s1_title",
							x:15,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							
							{compId:"ID_s1_txt05",
							x:17,
							y:213.35, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt06",
							x:302,
							y:213.35, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"}]
	var slide_graphics = [{	x:0.9,/* ID_s1_txt05 */
							y:207, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5},
							{x:282.9,/* ID_s1_txt06 */
							y:207, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5}]
														
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							graphics:slide_graphics,
							images:slide_1_images,
							texts:slide_1_texts};
	var slide_2_type = "IMAGE";
	var slide_2_images = [{name:"blkLeft.png",
							x:100.5,
							y:108.35, 
							width:100,
							height:58,
							type:""},
							{name:"blkRight.png",
							x:238.65,
							y:108.35, 
							width:100,
							height:58,
							type:""}];							
	var slide_2_texts = [{compId:"ID_s2_title",
							x:15,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_s2_txt01",
							x:17,
							y:213.35, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s2_txt02",
							x:302,
							y:213.35, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s2_txt03",
							x:14.3,
							y:300, 
							width:402.2,
							height:21,
							size:11,
							textAlign:"center"}];
	var slide_graphics = [{	x:0.9,/* ID_s2_txt01 */
							y:207, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5},
							{x:282.9,/* ID_s2_txt02 */
							y:207, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5},
							{x:137.5,
							y:248, 
							length:126,
							thickness:3,
							color:"#f68026",
							rotation:40,
							type:"arrow"},
						   {x:296,
							y:248, 
							length:126,

							thickness:3,
							color:"#f68026",
							rotation:139,
							type:"arrow"}]					
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							graphics:slide_graphics,
							images:slide_2_images,
							texts:slide_2_texts};
							
		var slide_3_type = "IMAGE";
	var slide_3_images = [{name:"blkLeft.png",
							x:100.5,
							y:108.35, 
							width:100,
							height:58,
							type:""},
							{name:"blkRight.png",
							x:238.65,
							y:108.35, 
							width:100,
							height:58,
							type:""},
							{name:"leftPur_arrow.png",
							x:129.5,
							y:233, 
							width:64,
							height:69,
							type:""},
							{name:"rightPur_arrow.png",
							x:240,
							y:233, 
							width:64,
							height:69,
							type:""}];								
	var slide_3_texts = [{compId:"ID_s3_title",
							x:15,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_s3_txt01",
							x:17,
							y:213.35, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s3_txt02",
							x:302,
							y:213.35, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s3_txt03",
							x:14.3,
							y:300, 
							width:402.2,
							height:21,
							size:11,
							textAlign:"center"}];
	var slide_graphics = [{	x:0.9,/* ID_s3_txt01 */
							y:207, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5},
							{x:282.9,/* ID_s3_txt02 */
							y:207, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5}]		
	var slide_3_object = {templateType:slide_3_type,
							x:0,
							y:0,
							graphics:slide_graphics,
							images:slide_3_images,
							texts:slide_3_texts};				
	
	var slide_4_type = "IMAGE";
	var slide_4_images = [{name:"blkLefttbot.png",
							x:100.5,
							y:108.35, 
							width:100,
							height:58,
							type:""},
						{name:"blkRightbot.png",
							x:238.65,
							y:108.35, 
							width:100,
							height:58,
							type:""},
						/*{name:"leftPurbot_arrow.png",
							x:129.5,
							y:253, 
							width:64,
							height:69,
							type:""},
						{name:"rightPurbot_arrow.png",
							x:240,
							y:253, 
							width:64,
							height:69,
							type:""},*/
						{name:"s4_purpleSt.png",
							x:22,
							y:119, 
							width:10,
							height:115,
							type:""},
						{name:"s4_purpleSt.png",
							x:400,
							y:119, 
							width:10,
							height:115,
							type:""}];									
	var slide_4_texts = [{compId:"ID_s4_title",
							x:15,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_s4_txt01",
							x:17,
							y:300, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s4_txt02",
							x:302,
							y:300, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s4_txt03",
							x:19.3,
							y:215, 
							width:402.2,
							height:21,
							size:11,
							textAlign:"center"},
							{compId:"ID_s4_txt04",
							x:17,
							y:68.35, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s4_txt05",
							x:302,
							y:68.35,
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"}]
							
	var slide_graphics = [{x:0.9,/* ID_s4_txt01 */
							y:63, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5},
							{x:282.9,/* ID_s4_txt02 */
							y:63, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5},
						{	x:0.9,/* ID_s4_txt04 */
							y:295, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5},
							{x:282.9,/* ID_s4_txt05 */
							y:295, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5}]
	var slide_4_object = {templateType:slide_4_type,
							x:0,
							y:0,
						    graphics:slide_graphics,
							images:slide_4_images,
							texts:slide_4_texts};	
							
	var slide_5_type = "IMAGE";
	var slide_5_images = [{name:"blkLefttbot.png",
							x:100.5,
							y:108.35, 
							width:100,
							height:58,
							type:""},
						{name:"blkRightbot.png",
							x:238.65,
							y:108.35, 
							width:100,
							height:58,
							type:""},
						/*{name:"leftPurbot_arrow.png",
							x:129.5,
							y:253, 
							width:64,
							height:69,
							type:""},
						{name:"rightPurbot_arrow.png",
							x:240,
							y:253, 
							width:64,
							height:69,
							type:""},*/
						{name:"slide5_purArrow.png",
							x:3.55,
							y:82.6, 
							width:24,
							height:165,
							type:""},
						{name:"slide5_purtArrow.png",
							x:409,
							y:82.6,
							width:24,
							height:165,
							type:""}];									
	var slide_5_texts = [{compId:"ID_s5_title",
							x:15,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_s5_txt01",
							x:17,
							y:300, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s5_txt02",
							x:302,
							y:300, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s5_txt03",
							x:19.3,
							y:215, 
							width:402.2,
							height:21,
							size:11,
							textAlign:"center"},
							{compId:"ID_s5_txt04",
							x:17,
							y:68.35, 
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"},
							{compId:"ID_s5_txt05",
							x:302,
							y:68.35,
							width:130,
							height:50.25,
							size:11,
							textAlign:"center"}]
							
	var slide_graphics = [{x:0.9,/* ID_s5_txt01 */
							y:63, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5},
							{x:282.9,/* ID_s5_txt02 */
							y:63, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5},
							{x:0.9,/* ID_s5_txt04 */
							y:295, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5},
							{x:282.9,/* ID_s54_txt05 */
							y:295, 
							width:147.5,
							height:55,
							color:"#FFFFFF",
							stroke:"#D3D1D2",
							thickness:2,
							corner:5}]
	var slide_5_object = {templateType:slide_5_type,
							x:0,
							y:0,
						    graphics:slide_graphics,
							images:slide_5_images,
							texts:slide_5_texts};	
	
	var slides = [slide_1_object,slide_2_object,slide_3_object,slide_4_object,slide_5_object];
											
	//var slides = [slide_5_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			images:commonImages,
			slideObject:slides
			};
	
}