loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js"); 

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 787;
var STAGE_HEIGHT = 400;
var TYPE = "MULTI_BAR";
var isDD = true;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [							
		];
	var common_images = [];
	
	var slide_1_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006979',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_s1_drag06",
		x:30,
        y:84.65,
        width:130,
        height:55.40,
        size:11,
		tag:3,
        textAlign:"center"},     
        {compId:"ID_s1_drag08",
       	x:30,
        y:158.7,
        width:140,
        height:55.40,
        size:11,
		tag:4,
        textAlign:"center"},
		{compId:"ID_s1_drag01",
       	x:30,
        y:232.7,
        width:140,
        height:55.40,
		tag:1,
        textAlign:"center"},
		{compId:"ID_s1_drag04",
       	x:30,
        y:306.75,
        width:140,
        height:55.40,
		tag:2,
        textAlign:"center"},
	{compId:"ID_s1_drag05",
		x:175.8,
        y:84.65,
        width:140,
        height:55.40,
        size:11,
		tag:3,
        textAlign:"center"},     
        {compId:"ID_s1_drag02",
       	x:175.8,
        y:158.7,
        width:140,
        height:55.40,
        size:11,
		tag:1,
        textAlign:"center"},
		{compId:"ID_s1_drag07",
       	x:175.8,
        y:232.7,
        width:140,
        height:55.40,
		tag:4,
        textAlign:"center"},
		{compId:"ID_s1_drag03",
       	x:175.8,
        y:306.75,
        width:140,
        height:55.40,
		tag:2,
        textAlign:"center"},
];
    var dropBox = [{compId:"a1_dt",/*First group*/
        x:365.55,
        y:80.8 - 36,
        width:140,
        height:55.40,
        size:11,
        answer:1,
        textAlign:"center"},
        {compId:"a2_dt",
        x:365.55,
        y:142.15 - 36,
        width:140,
        height:55.40,
        size:11,
        answer:1,
        textAlign:"center"},/*2nd group*/
		{compId:"a3_dt",
         x:590.6,
        y:80.8-36,
        width:140,
         height:55.40,
        size:11,
        answer:2,
        textAlign:"center"},
        {compId:"a4_dt",
         x:590.6,
        y:142.15-36,
        width:140,
         height:55.40,
        size:11,
        answer:2,
        textAlign:"center"},
		{compId:"a5_dt",/*3rd group*/
		 x:365.55,
        y:238.6 - 26 + 16,
        width:140,
        height:55.40,
        size:11,
        answer:3,
        textAlign:"center"},
        {compId:"a6_dt",
         x:365.55,
        y:298.5 - 26 + 16,
        width:140,
        height:55.40,
        size:11,
        answer:3,
        textAlign:"center"},
		{compId:"a7_dt",/*4rd group*/
         x:590.6,
        y:238.6 - 26 + 16,
        width:140,
         height:55.40,
        size:11,
        answer:4,
        textAlign:"center"},
        {compId:"a8_dt",
        x:590.6,
        y:298.5 - 26 + 16,
        width:140,
         height:55.40,
        size:11,
        answer:4,
        textAlign:"center"},
        
		
    ];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_1_texts = [
		{compId:"ID_s1_inst",
        x:30,
        y:1,
        width:291.95,
        height:17,
        size:11,
        textAlign:"left"},
	
		{compId:"ID_s1_txt01",
			x:330,
            y:55.85 - 36,
            width:214.9,
            height:17,
            size:11,
            textAlign:"center"},

       {compId:"ID_s1_txt02",
            x:555.6,
            y:55.85 - 36,
            width:214.9,
            height:17,
            size:11,
            textAlign:"center"},
	{compId:"ID_s1_txt03",
			x:330,
            y:217.4 - 6 - 8,
            width:214.9,
            height:17,
            size:11,
            textAlign:"center"},

       {compId:"ID_s1_txt04",
             x:555.6,
            y:217.4 - 6 - 8,
            width:214.9,
            height:17,
            size:11,
            textAlign:"center"},
		 
    ];
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_1_images = [{name:"bg.png",
							x:325.35,
							y:41.9 - 40, 
							width:218,
							height:158.1+15,
							type:""},
							{name:"bg.png",
							x:550.35,
							y:41.9 - 40, 
							width:218,
							height:158.1+15,
							type:""},
							{name:"bg.png",
							x:325.35,
							y:185, 
							width:218,
							height:158.1+15,
							type:""},
							{name:"bg.png",
							x:550.35,
							y:185,
							width:218,
							height:158.1+15,
							type:""}];
    var submit_buttons = [{compId:"ID_s1_CHECK",
        x:594,
        y:362,
        width:80,
		height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s1_RESET",
             x:697,
			 y:362,
             width:80,
			 height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:30,
        y:117,
        width:130,
        height:23,
        size:11,
        image:"../../../common/images/feedback2.png",
        textAlign:"center"}];
    var instobj = {ansType:"many-one",clue:1};
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_1_texts,
							slideImages:slide_1_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
	
	/* Slide 2 */
	var slide_2_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006979',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_s2_drag08",
		x:30,
        y:84.65,
        width:140,
        height:55.40,
        size:11,
		tag:4,
        textAlign:"center"},     
        {compId:"ID_s2_drag07",
       	x:30,
        y:158.7,
        width:140,
        height:55.40,
        size:11,
		tag:4,
        textAlign:"center"},
		{compId:"ID_s2_drag04",
       	x:30,
        y:232.7,
        width:140,
        height:55.40,
		tag:2,
        textAlign:"center"},
		{compId:"ID_s2_drag05",
       	x:30,
        y:306.75,
        width:140,
        height:55.40,
		tag:3,
        textAlign:"center"},
	{compId:"ID_s2_drag03",
		x:175.8,
        y:84.65,
        width:140,
        height:55.40,
        size:11,
		tag:2,
        textAlign:"center"},     
        {compId:"ID_s2_drag02",
       	x:175.8,
        y:158.7,
        width:140,
        height:55.40,
        size:11,
		tag:1,
        textAlign:"center"},
		{compId:"ID_s2_drag06",
       	x:175.8,
        y:232.7,
        width:140,
        height:55.40,
		tag:3,
        textAlign:"center"},
		{compId:"ID_s2_drag01",
       	x:175.8,
        y:306.75,
        width:140,
        height:55.40,
		tag:1,
        textAlign:"center"},
];
    var dropBox = [{compId:"b1_dt",/*First group*/
        x:365.55,
        y:80.8 - 36,
        width:140,
        height:55.40,
        size:11,
        answer:1,
        textAlign:"center"},
        {compId:"b2_dt",
        x:365.55,
        y:142.15 - 36,
        width:140,
        height:55.40,
        size:11,
        answer:1,
        textAlign:"center"},/*2nd group*/
		{compId:"b3_dt",
         x:590.6,
        y:80.8 - 36,
        width:140,
         height:55.40,
        size:11,
        answer:2,
        textAlign:"center"},
        {compId:"b4_dt",
        x:590.6,
        y:142.15 - 36,
        width:140,
         height:55.40,
        size:11,
        answer:2,
        textAlign:"center"},
		{compId:"b5_dt",/*3rd group*/
		 x:365.55,
        y:238.6 - 13,
        width:140,
        height:55.40,
        size:11,
        answer:3,
        textAlign:"center"},
        {compId:"b6_dt",
         x:365.55,
        y:298.5- 13,
        width:140,
        height:55.40,
        size:11,
        answer:3,
        textAlign:"center"},
		{compId:"b7_dt",/*4rd group*/
         x:590.6,
        y:238.6- 13,
        width:140,
         height:55.40,
        size:11,
        answer:4,
        textAlign:"center"},
        {compId:"b8_dt",
        x:590.6,
        y:298.5- 13,
        width:140,
         height:55.40,
        size:11,
        answer:4,
        textAlign:"center"},
        
		
    ];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_2_texts = [
		{compId:"ID_s2_inst",
        x:30,
        y:1,
        width:291.95,
        height:17,
        size:11,
        textAlign:"left"},
	
		{compId:"ID_s2_txt01",
			x:330,
            y:55.85 - 36,
            width:214.9,
            height:17,
            size:11,
            textAlign:"center"},

       {compId:"ID_s2_txt02",
            x:555.6,
            y:55.85 - 36,
            width:214.9,
            height:17,
            size:11,
            textAlign:"center"},
	{compId:"ID_s2_txt03",
			x:330,
            y:217.4 - 6 - 8,
            width:214.9,
            height:17,
            size:11,
            textAlign:"center"},

       {compId:"ID_s2_txt04",
             x:555.6,
            y:217.4 - 6 - 8,
            width:214.9,
            height:17,
            size:11,
            textAlign:"center"},
		 
    ];
    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_2_images = [{name:"bg.png",
							x:325.35,
							y:41.9 - 40, 
							width:218,
							height:158.1+15,
							type:""},
							{name:"bg.png",
							x:550.35,
							y:41.9 - 40, 
							width:218,
							height:158.1+15,
							type:""},
							{name:"bg.png",
							x:325.35,
							y:185, 
							width:218,
							height:158.1+15,
							type:""},
							{name:"bg.png",
							x:550.35,
							y:185, 
							width:218,
							height:158.1+15,
							type:""}];
    var submit_buttons = [{compId:"ID_s2_CHECK",
        x:594,
        y:362,
        width:80,
		height:23,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_s2_RESET",
             x:697,
			 y:362,
             width:80,
			 height:23,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}
    ];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:30,
        y:117,
        width:130,
        height:23,
        size:11,
        image:"../../../common/images/feedback2.png",
        textAlign:"center"}];
    var instobj = {ansType:"many-one",clue:1};
	
 var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts,
							textObject:commonTexts,
							buttonObject:buttonObject,
							slideObject:slide_2_texts,
							slideImages:slide_2_images,
							dropObject:dropObject,
							submitObject:submit_buttons,
							feedbackObj:feedbackObj,
                            instobj:instobj
    };
			
	
															
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
		    images:common_images,
			slideObject:slides,
			buttonBarPos:{x:728}};
	
}



