//loadScript("../../../common/scripts/templates/slide/ImageSlideNew.js");
loadScript("../../../common/scripts/swfobject.js", registerSWF);

function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}

var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
    var template_type = "IMAGE";

    var slide_images = [{name:"4_1_2_2.png",
						x:10.25,
						y:117.8,
						width:461.2,
						height:240.4,
						type:""}];

    var slide_texts = [{compId:"ID_title",
							x:27,
							y:2, 
							width:460,
							height:17,
							size:14,
							textAlign:"center"},
							{compId:"ID_txt01",
							x:203,
							y:277, 
							width:97.65,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt02",
							x:148.45,
							y:44.45, 
							width:223.6,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_txt03",
							x:38,
							y:102, 
							width:104,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt04",
							x:355,
							y:102, 
							width:104,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt05",
							x:129,
							y:348, 
							width:242.55,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt06",
							x:32,
							y:255+35, 
							width:45.75,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt07",
							x:103,
							y:255+35 , 
							width:45.75,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt08",
							x:37,
							y:152-24, 
							width:104,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt09",
							x:358,
							y:152-25, 
							width:104,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt10",
							x:352,
							y:255+35, 
							width:45.75,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt11",
							x:422,
							y:255+35, 
							width:45.75,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt12",
							x:25.4,
							y:141.95-2, 
							size:11,
							textAlign:"left"},
							{compId:"ID_txt13",
							x:89.6,
							y:182.95-4, 
							size:11,
							textAlign:"right"},
							{compId:"ID_txt16",
							x:25.4,
							y:221.95-6, 
							size:11,
							textAlign:"left"},
							{compId:"ID_txt14",
							x:328.9+15,
							y:141.95-2, 
							size:11,
							textAlign:"left"},
							{compId:"ID_txt15",
							x:328.9+79,
							y:182.95-4, 
							size:11,
							textAlign:"right"},
							{compId:"ID_txt17",
							x:328.9+15,
							y:221.95-6, 
							size:11,
							textAlign:"left"},
							];

    var slide_object = {images:slide_images,
        texts:slide_texts};

    return {templateType:template_type,
        slideObject:slide_object};

}
