loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [{	compId:"ID_title",
							x:15,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center",
							expand:"down"}];
	
	var slide_1_type = "IMAGE";
	var slide_1_images = [{name:"7_2_2_4.png",
							 x:1,
							 y:135, 
							 width:437,
							 height:128,
							 size:11,
							 type:""}];								
	var slide_1_texts = [	{compId:"static_txt02",
							bodyText:"<table width='265' border='0' align='left' cellpadding='0' cellspacing='0'> <tr> <td align='right'>2001:</td> <td align='right'><span>0</span>DB8:</td> <td align='right'><span>000</span>0:</td> <td align='right'>1111:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>0</span>200</td> </tr> <tr> <td align='right'>2001:</td> <td align='right'>DB8:</td> <td align='right'>0:</td> <td align='right'>1111:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>200</td> </tr> <tr> <td colspan='8' align='left'><span class='spacer'>2001:DB8:0:1111::200</span></td> </tr></table>",
							x:176.15-8,
							y:195.65-52, 
							width:266,
							height:16,
							size:11,
							color:"#393536",
							textAlign:"left"},
							{	compId:"ID_s1_txt01",
							x:21,
							y:156, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt02",
							x:21,
							y:195, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt03",
							x:21,
							y:234, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"}
							];							
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts};
							
	var slide_2_type = "IMAGE";
	var slide_2_images = [{name:"7_2_2_4B.png",
							 x:1,
							 y:69, 
							 width:438,
							 height:243.3,
							 size:11,
							 type:""},
							 ];								
	var slide_2_texts = [{	compId:"static_txt02",
							bodyText:"<table width='265' border='0' align='left' cellpadding='0' cellspacing='0'> <tr> <td align='right'>2001:</td> <td align='right'><span>0</span>DB8:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'>ABCD:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>0</span>100</td> </tr> <tr> <td align='right'>2001:</td> <td align='right'>DB8:</td> <td align='right'><span class='green'>0:</span></td> <td align='right'><span class='green'>0:</span></td> <td align='right'>ABCD:</td> <td align='right'><span class='green'>0:</span></td> <td align='right'><span class='green'>0:</span></td> <td align='right'>100</td> </tr> <tr> <td colspan='8' align='left'><span class='spacer_2'>2001:DB8::ABCD:0:0:100</span></td> </tr></table>",
							x:176.15-8,
							y:129.65-54, 
							width:266,
							height:16,
							size:11,
							color:"#393536",
							textAlign:"left"},
							{	compId:"static_txt04",
							bodyText:"2001:DB8:0:0:ABCD::100",
							x:176.15,
							y:231.65, 
							width:170,
							height:16,
							size:11,
							color:"#393536",
							textAlign:"left"},
							{	compId:"ID_s2_txt01",
							x:21,
							y:90, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s2_txt02",
							x:21,
							y:129, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s2_txt03",
							x:21,
							y:168, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s2_txt04",
							x:21,
							y:199.5, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s2_txt05",
							x:21,
							y:231, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s2_txt06",
							x:230.05,
							y:298.2, 
							width:174,
							height:17,
							size:11,
							textAlign:"left"}
							];								
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts};
							
	
	var slide_3_type = "IMAGE";
	var slide_3_images = [{name:"7_2_2_4.png",
							 x:1,
							 y:135, 
							 width:437,
							 height:128,
							 size:11,
							 type:""}];								
	var slide_3_texts = [{	compId:"static_txt02",
							bodyText:"<table width='265' border='0' align='left' cellpadding='0' cellspacing='0'> <tr> <td align='right'>FE80:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>0</span>123:</td> <td align='right'>4567:</td> <td align='right'>89AB:</td> <td align='right'>CDEF</td> </tr> <tr> <td align='right'>FE80:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>123:</td> <td align='right'>4567:</td> <td align='right'>89AB:</td> <td align='right'>CDEF</td> </tr> <tr> <td colspan='8' align='left'><span class='spacer'>FE80::123:4567:89AB:CDEF</span></td> </tr></table>",
							x:176.15-7,
							y:195.65-53, 
							width:268,
							height:16,
							size:11,
							color:"#393536",
							textAlign:"left"},
							{	compId:"ID_s1_txt01",
							x:21,
							y:156, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt02",
							x:21,
							y:195, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt03",
							x:21,
							y:234, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"}
							];								
	var slide_3_object = {templateType:slide_3_type,
							x:0,
							y:0,
							images:slide_3_images,
							texts:slide_3_texts};
	
	var slide_4_type = "IMAGE";
	var slide_4_images = [{name:"7_2_2_4.png",
							 x:1,
							 y:135, 
							 width:437,
							 height:128,
							 size:11,
							 type:""}];								
	var slide_4_texts = [{	compId:"static_txt02",
							bodyText:"<table width='265' border='0' align='left' cellpadding='0' cellspacing='0'> <tr> <td align='right'>FF02:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>1</td> </tr> <tr> <td align='right'>FF02:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>1</td> </tr> <tr> <td colspan='8' align='left'><span class='spacer'>FF02::1</span></td> </tr></table>",
							x:176.15-7,
							y:195.65-53, 
							width:268,
							height:16,
							size:11,
							color:"#393536",
							textAlign:"left"},
							{	compId:"ID_s1_txt01",
							x:21,
							y:156, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt02",
							x:21,
							y:195, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt03",
							x:21,
							y:234, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"}
							];						
	var slide_4_object = {templateType:slide_4_type,
							x:0,
							y:0,
							images:slide_4_images,
							texts:slide_4_texts};
							
	var slide_5_type = "IMAGE";
	var slide_5_images = [{name:"7_2_2_4.png",
							 x:1,
							 y:135, 
							 width:437,
							 height:128,
							 size:11,
							 type:""}];								
	var slide_5_texts = [	{	compId:"static_txt02",
							bodyText:"<table width='265' border='0' align='left' cellpadding='0' cellspacing='0'> <tr> <td align='right'>FF02:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>1:</td> <td align='right'>FF00:</td> <td align='right'><span>0</span>200</td> </tr> <tr> <td align='right'>FF02:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>1:</td> <td align='right'>FF00:</td> <td align='right'>200</td> </tr> <tr> <td colspan='8' align='left'><span class='spacer'>FF02::1:FF00:200</span></td> </tr></table>",
							x:176.15-7,
							y:195.65-53, 
							width:268,
							height:16,
							size:11,
							color:"#393536",
							textAlign:"left"},
							{	compId:"ID_s1_txt01",
							x:21,
							y:156, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt02",
							x:21,
							y:195, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt03",
							x:21,
							y:234, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"}
							];							
	var slide_5_object = {templateType:slide_5_type,
							x:0,
							y:0,
							images:slide_5_images,
							texts:slide_5_texts};
							
	var slide_6_type = "IMAGE";
	var slide_6_images = [{name:"7_2_2_4.png",
							 x:1,
							 y:135, 
							 width:437,
							 height:128,
							 size:11,
							 type:""}];								
	var slide_6_texts = [	{	compId:"static_txt02",
							bodyText:"<table width='265' border='0' align='left' cellpadding='0' cellspacing='0'> <tr> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>1</td> </tr> <tr> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>1:</td> <td align='right'>0:</td> <td align='right'>1</td> </tr> <tr> <td colspan='8' align='left'><span class='spacer'>::1</span></td> </tr></table>",
							x:176.15-7,
							y:195.65-53, 
							width:268,
							height:16,
							size:11,
							color:"#393536",
							textAlign:"left"},
							{	compId:"ID_s1_txt01",
							x:21,
							y:156, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt02",
							x:21,
							y:195, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt03",
							x:21,
							y:234, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"}
							];						
	var slide_6_object = {templateType:slide_6_type,
							x:0,
							y:0,
							images:slide_6_images,
							texts:slide_6_texts};
							
	var slide_7_type = "IMAGE";
	var slide_7_images = [{name:"7_2_2_4.png",
							 x:1,
							 y:135, 
							 width:437,
							 height:128,
							 size:11,
							 type:""}];								
	var slide_7_texts = [{	compId:"static_txt02",
							bodyText:"<table width='265' border='0' align='left' cellpadding='0' cellspacing='0'> <tr> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0:</td> <td align='right'><span>000</span>0</td> </tr> <tr> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0:</td> <td align='right'>0</td> </tr> <tr> <td colspan='8' align='left'><span class='spacer'>::</span></td> </tr></table>",
							x:176.15-7,
							y:195.65-53, 
							width:268,
							height:16,
							size:11,
							color:"#393536",
							textAlign:"left"},
							{	compId:"ID_s1_txt01",
							x:21,
							y:156, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt02",
							x:21,
							y:195, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"},
							{	compId:"ID_s1_txt03",
							x:21,
							y:234, 
							width:146,
							height:17,
							size:11,
							textAlign:"left"}
							];					
	var slide_7_object = {templateType:slide_7_type,
							x:0,
							y:0,
							images:slide_7_images,
							texts:slide_7_texts};
							
							
	var slides = [slide_1_object,slide_2_object,slide_3_object,slide_4_object,slide_5_object,slide_6_object,slide_7_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			slideObject:slides};
	
}
