
loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [{compId:"ID_s1_title",
							x:25,
							y:2, 
							width:430,
							height:17,
							size:14,
							textAlign:"center"},];
	
	var slide_1_type = "IMAGE";
	var slide_1_images = [{name:"3_1_1_2A.png",
						x:38.15,
						y:154.05,
						width:334.55,
						height:58.45,
						type:""}];							
	var slide_1_textboxs = [];							
	var slide_1_texts = [{compId:"ID_s1_txt01",
							x:142.6,
							y:82.1, 
							width:61.65,
							height:14,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt02",
							x:204.45,
							y:82.1, 
							width:92.95,
							height:14,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt03",
							x:5,
							y:380, 
							width:430,
							height:17,
							size:11,
							textAlign:"center",
							expand:"up"},
							{compId:"ID_s1_txt04",
							x:324.35,
							y:39.5, 
							width:39.45,
							height:13,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt05",
							x:36.45,
							y:66.65, 
							width:29.05,
							height:13,
							size:11,
							textAlign:"left"},
							{compId:"ID_s1_txt06",
							x:93.4,
							y:66.65,
							width:27.75,
							height:13,
							size:11,
							textAlign:"left"},
							{compId:"ID_s1_txt07",
							x:155.6,
							y:66.65,
							width:80,
							height:13,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt08",
							x:300.35,
							y:66.65,
							width:88,
							height:13,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt09",
							x:85.7,
							y:91, 
							width:100,
							height:13,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt10",
							x:281.7,
							y:91,
							width:50,
							height:13,
							size:11,
							textAlign:"left"},
							{compId:"ID_s1_txt11",
							x:338.7,
							y:91,
							width:90,
							height:13,
							size:11,
							textAlign:"left"},
							{compId:"ID_s1_txt12",
							x:52.3,
							y:116, 
							width:80,
							height:13,
							size:11,
							textAlign:"left"},
							{compId:"ID_s1_txt13",
							x:190,
							y:140,  
							width:70,
							height:13,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt14",
							x:300,
							y:116,
							width:130,
							height:13,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt15",
							x:135,
							y:116, 
							width:130,
							height:13,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt16",
							x:184,
							y:159, 
							width:110,
							height:13,
							size:11,
							textAlign:"left"},
							{compId:"ID_s1_txt17",
							x:215,
							y:181, 
							width:70,
							height:13,
							size:11,
							textAlign:"left"},
							{compId:"ID_s1_txt18",
							x:373 ,
							y:181,
							width:70,
							height:13,
							size:11,
							textAlign:"left"},
							{compId:"ID_s1_txt19",
							x:5,
							y:390-14, 
							width:440,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_bubble01",
							x:8,
							y:211,
							width:124,
							size:11},
							{compId:"ID_s1_bubble02",
							x:130+5,
							y:209,
							width:164,
							size:11},
							{compId:"ID_s1_bubble03",
							x:290+8,
							y:209,
							width:152,
							size:11}];
	var slide_graphics = [];							
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							textboxs:slide_1_textboxs,
							texts:slide_1_texts,
							graphics:slide_graphics};
							
	var slide_2_type = "IMAGE";
	var slide_2_images = [{name:"3_1_1_2B.png",
						x:103.4,
						y:100.15,
						width:244.1,
						height:201.7,
						type:""}];							
	var slide_2_textboxs = [];							
	var slide_2_texts = [{compId:"ID_s2_bubble01",
							x:149,
							y:25,
							width:186,
							size:11},
							{compId:"ID_s2_bubble02",
							x:236,
							y:208,
							width:67,
							size:11},
							{compId:"ID_s2_bubble03",
							x:77+13,
							y:316-14,
							width:145,
							size:11},
							{compId:"ID_s2_bubble04",
							x:255.1,
							y:312-6,
							width:67,
							size:11},
							{compId:"ID_s2_bubble05",
							x:312.1,
							y:227,
							width:67,
							size:11},
							{compId:"ID_s2_txt01",
							x:154,
							y:284, 
							width:34.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s2_txt02",
							x:200.15,
							y:298, 
							width:34.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s2_txt04",
							x:5,
							y:375, 
							width:430,
							height:17,
							size:11,
							textAlign:"center"},];
	var slide_graphics = [];							
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							textboxs:slide_2_textboxs,
							texts:slide_2_texts,
							graphics:slide_graphics};
							
	var slide_3_type = "IMAGE";
	var slide_3_images = [{name:"3_1_1_2B.png",
						x:103.4,
						y:100.15,
						width:244.1,
						height:201.7,
						type:""}];							
	var slide_3_textboxs = [];							
	var slide_3_texts = [{compId:"ID_s3_bubble01",
							x:155.35,
							y:38-4,
							width:162,
							size:11},
							{compId:"ID_s3_bubble02",
							x:129.1,
							y:177,
							width:162,
							size:11},
							{compId:"ID_s3_bubble03",
							x:84.4,
							y:320-15,
							width:200,
							size:11},
							{compId:"ID_s3_txt04",
							x:5,
							y:375, 
							width:430,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_s3_txt01",
							x:154,
							y:284, 
							width:34.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s3_txt02",
							x:252.75,
							y:262.1, 
							width:34.55,
							height:17,
							size:11,
							textAlign:"left"},];
	var slide_graphics = [];							
	var slide_3_object = {templateType:slide_3_type,
							x:0,
							y:0,
							images:slide_3_images,
							textboxs:slide_3_textboxs,
							texts:slide_3_texts,
							graphics:slide_graphics};
							
	var slide_4_type = "IMAGE";
	var slide_4_images = [{name:"3_1_1_2C.png",
						x:67.3,
						y:128.1,
						width:309.55,
						height:64.10,
						type:""}];							
	var slide_4_textboxs = [];							
	var slide_4_texts = [{compId:"ID_s4_bubble01",
							x:275,
							y:205-13,
							width:162,
							size:11},
							{compId:"ID_s4_bubble02",
							x:10,
							y:206-12,
							width:162,
							size:11},
							{compId:"ID_s4_txt01",
							x:5,
							y:375, 
							width:430,
							height:17,
							size:11,
							textAlign:"center"},];
	var slide_graphics = [];							
	var slide_4_object = {templateType:slide_4_type,
							x:0,
							y:0,
							images:slide_4_images,
							textboxs:slide_4_textboxs,
							texts:slide_4_texts,
							graphics:slide_graphics};
																				
											
	var slides = [slide_1_object,slide_2_object,slide_3_object,slide_4_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			slideObject:slides};
	
}
