//loadScript("../../../common/scripts/templates/slide/ImageSlideNew.js");

function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
    var template_type = "IMAGE";

    var slide_images = [{name:"1_3_1_5.png",
        x:10,
        y:10.25,
        width:450,
        height:380,
        type:""}];

    var slide_texts = [{compId:"ID_txt01",
							x:30,
							y:61.5, 
							width:100,
							height:15,
							size:12,
							textAlign:"left"},
							{compId:"ID_txt02",
							x:139,
							y:47.5, 
							width:110.35,
							height:15,
							size:10,
							textAlign:"left"},
							{compId:"ID_txt03",
							x:242.5,
							y:47.5, 
							width:110,
							height:15,
							size:10,
							textAlign:"center"},
							{compId:"ID_txt04",
							x:352,
							y:47.5, 
							width:110,
							height:15,
							size:10,
							textAlign:"center"},
							{compId:"ID_txt05",
							x:164,
							y:100.5, 
							width:110,
							height:15,
							size:10,
							textAlign:"left"},
							{compId:"ID_txt06",
							x:241.5,
							y:100.5, 
							width:110,
							height:15,
							size:10,
							textAlign:"center"},
							{compId:"ID_txt07",
							x:355,
							y:100.5, 
							width:110,
							height:15,
							size:10,
							textAlign:"left"},
							{compId:"ID_txt08",
							x:30,
							y:191.5, 
							width:100,
							height:17,
							size:12,
							textAlign:"left"},
							{compId:"ID_txt09",
							x:127,
							y:173.5, 
							width:110,
							height:14.95,
							size:10,
							textAlign:"center"},
							{compId:"ID_txt10",
							x:241.5,
							y:174.5, 
							width:110,
							height:15,
							size:10,
							textAlign:"center"},
							{compId:"ID_txt11",
							x:357,
							y:174.5, 
							width:110,
							height:15,
							size:10,
							textAlign:"center"},
							{compId:"ID_txt12",
							x:160.25,
							y:230.5, 
							width:130,
							height:15,
							size:10,
							textAlign:"center"},
							{compId:"ID_txt13",
							x:305,
							y:230.5, 
							width:130,
							height:15,
							size:10,
							textAlign:"center"},
							{compId:"ID_txt14",
							x:30,
							y:322.95, 
							width:150,
							height:17,
							size:12,
							textAlign:"left"},
							{compId:"ID_txt15",
							x:325.5,
							y:289.5, 
							width:110,
							height:14.95,
							size:10,
							textAlign:"left"},
							{compId:"ID_txt16",
							x:325.5,
							y:322.95, 
							width:110,
							height:15,
							size:10,
							textAlign:"left"},
							{compId:"ID_txt17",
							x:325.5,
							y:356.45, 
							width:110,
							height:15,
							size:10,
							textAlign:"left"}
							];

    var slide_object = {images:slide_images,
        texts:slide_texts};

    return {templateType:template_type,
        slideObject:slide_object};

}

loadScript("../../../common/scripts/swfobject.js", registerSWF);
