loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/DragDropSlide.js");


function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}

var STAGE_WIDTH = 770;
var STAGE_HEIGHT = 388;

function getData()
{
    var template_type = "DRAG_DROP";
    var buttonStyle = {normalSkinImage:"../../../common/images/drag_normal.png",
        overSkinImage:"../../../common/images/drop_normal.png",
        //dropNormalSkinImage:"../../../common/images/drop_normal.png",
		dropNormalSkinImage:"drop_normal.png",
        normalTextStyle:'#FFFFFF',
        overTextStyle:'#006699',
        cornorRadius:5,
        selected:0};

    var buttons = [{compId:"ID_drag01",
            x:5.3,
            y:83.8,
            width:140,
            height:41.4,
            size:11,
		tag:5,
			textAlign:"center"},
       {compId:"ID_drag02",
            x:5.3,
            y:137.75,
             width:140,
            height:41.4,
            size:11,
		tag:2,
            textAlign:"center"},
		{compId:"ID_drag03",
            x:5.3,
            y:191.7,
             width:140,
            height:41.4,
            size:11,	
		tag:3,
            textAlign:"center"},
		{compId:"ID_drag05",
            x:5.3,
            y:245.65,
             width:140,
            height:41.4,
            size:11,
		tag:2,
            textAlign:"center"},
		{compId:"ID_drag07",
            x:5.3,
            y:299.6,
             width:140,
            height:41.4,
            size:11,
		tag:3,
            textAlign:"center"},
		{compId:"ID_drag09",
            x:5.3,
            y:353.55,
             width:140,
            height:41.4,
            size:11,
		tag:1,
            textAlign:"center"},
		{compId:"ID_drag04",
            x:168.15,
            y:191.7,
            width:140,
            height:41.4,
            size:11,	
		tag:4,
            textAlign:"center"},
		{compId:"ID_drag06",
            x:168.15,
            y:245.65,
            width:140,
            height:41.4,
            size:11,
		tag:1,
            textAlign:"center"},
		{compId:"ID_drag08",
            x:168.15,
            y:299.6,
            width:140,
            height:41.4,
            size:11,
		tag:4,
            textAlign:"center"},
		{compId:"ID_drag10",
            x:168.15,
            y:353.55,
            width:140,
            height:41.4,
            size:11,
		tag:5,
            textAlign:"center"}];
    var dropBox = [{compId:"ip1_dt",
        x:199.55,
        y:83.8,
        width:140,
        height:41.4,
        size:11,
        answer:1,
        textAlign:"center"},
       {compId:"ip2_dt",
         x:199.55,
		 y:132.2,
         width:140,
         height:41.4,
         size:11,
         answer:1,
        textAlign:"center"},
       {compId:"ip3_dt",
        x:400.6,
        y:83.8,
         width:140,
        height:41.4,
        size:11,
        answer:2,
        textAlign:"center"},
		{compId:"ip4_dt",
         x:400.6,
        y:132.2,
         width:140,
        height:41.4,
        size:11,
        answer:2,
        textAlign:"center"},
		{compId:"ip5_dt",
		 x:605.65,
         y:84.05,
         width:140,
         height:41.4,
         size:11,
         answer:3,
         textAlign:"center"},
		{compId:"ip6_dt",
		 x:605.65,
         y:130.95,
         width:140,
         height:41.4,
         size:11,
         answer:3,
         textAlign:"center"},
		{compId:"ip7_dt",
		 x:400.6,
         y:215.6,
         width:140,
         height:41.4,
         size:11,
         answer:4,
         textAlign:"center"},
		{compId:"ip8_dt",
		  x:400.6,
         y:262.5,
         width:140,
         height:41.4,
         size:11,
         answer:4,
         textAlign:"center"},
		{compId:"ip9_dt",
		 x:604.65,
         y:215.6,
         width:140,
         height:41.4,
         size:11,
         answer:5,
         textAlign:"center"},
		{compId:"ip10_dt",
		 x:604.65,
         y:262.5,
         width:140,
         height:41.4,
         size:11,
         answer:5,
         textAlign:"center"},];

    var buttonObject = {style:buttonStyle,
        buttons:buttons};

    var commonTexts = [];
    var slide_texts = [{compId:"ID_inst",
							x:2,
							y:1, 
							width:778.05,
							height:17,
							size:11,							
							textAlign:"left"},
						{compId:"ID_txt01",
							x:176,
							y:58.85, 
							width:187.95,
							height:17,
							size:11,							
							textAlign:"center"},
						{compId:"ID_txt02",
							x:376.6,
							y:58.85, 
							width:187.95,
							height:17,
							size:11,							
							textAlign:"center"},
						{compId:"ID_txt03",
							x:582.1,
							y:58.85, 
							width:187.95,
							height:17,
							size:11,							
							textAlign:"center"},
						{compId:"ID_txt04",
							x:377.6,
							y:189.4, 
							width:187.95,
							height:17,
							size:11,							
							textAlign:"center"},
						{compId:"ID_txt05",
							x:581.15,
							y:189.4, 
							width:187.95,
							height:17,
							size:11,							
							textAlign:"center"}];

    var dropObject = {style:buttonStyle,dropBox:dropBox};

    var slide_images = [{compId:"ID_image01",
        name:"bg.png",
        x:174,
        y:56,
        width:191.9,
        height:121.65,
        size:11,
        textAlign:"left"},
		{compId:"ID_image02",
        name:"bg.png",
        x:376.2,
        y:56,
        width:191.9,
        height:121.65,
        size:11,
        textAlign:"left"},
		{compId:"ID_image03",
        name:"bg.png",
        x:578.15,
        y:56,
        width:191.9,
        height:121.65,
        size:11,
        textAlign:"left"},
		{compId:"ID_image04",
        name:"bg.png",
        x:376.2,
        y:187.5,
        width:191.9,
        height:121.65,
        size:11,
        textAlign:"left"},
		{compId:"ID_image05",
        name:"bg.png",
        x:578.15,
        y:187.5,
        width:191.9,
        height:121.65,
        size:11,
        textAlign:"left"},
		];


   var submit_buttons = [{compId:"ID_CHECK",
        x:607,
        y:377,
        width:90,
        height:21,
        size:11,
        normalSkinImage:"../../../common/images/btn_normal.png",
        textAlign:"center"},
        {compId:"ID_RESET",
          x:684,
          y:377,
			width:90,
			height:21,
			size:11,
            normalSkinImage:"../../../common/images/btn_normal.png",
            textAlign:"center"}];
    var feedbackObj = [{compId:"ID_FEEDBACK",
        x:-1,
        y:168,
        width:172,
        height:10,
        size:12,
        image:"../../../common/images/feedback.png",
        textAlign:"left"}];
   var instobj = {ansType:"many-one"};
    
    return {templateType:template_type,
        textObject:commonTexts,
        buttonObject:buttonObject,
        slideObject:slide_texts,
        slideImages:slide_images,
        dropObject:dropObject,
        submitObject:submit_buttons,
        feedbackObj:feedbackObj,
	instobj:instobj
    };

}


