//loadScript("../../../common/scripts/templates/slide/ImageSlideNew.js");

function registerSWF(){
    swfobject.registerObject("flashobject", "9.0.0", "../../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
    var template_type = "IMAGE";

    var slide_images = [{name:"10.3.3.2.png",
        x:6.75,
        y:6.65,
        width:468.65,
        height:391,
        type:""},
		];

    var slide_texts = [
		{compId:"ID_title",
            x:5,
            y:2,
            width:460,
            height:17,
            size:14,
            textAlign:"center"},
		{compId:"ID_txt01",
            x:190.4,
            y:15.05,
            width:104,
            height:17,
            size:11,
            textAlign:"center"},
        {compId:"ID_txt02",
            x:93.75+11-3,
            y:53.5,
            width:56,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt03",
            x:207.15+9-3,
              y:53.5-5+8,
            width:56,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt04",
             x:330-5,
              y:53.5,
            width:56,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt05",
            x:24,
            y:191,
            width:135,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt06",
            x:174,
            y:191,
            width:135,
            height:17,
            size:11,
            textAlign:"center"},		
		{compId:"ID_txt07",
            x:350-25,
            y:191,
            width:135,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt08",
            x:29.55,
            y:222.65,
            width:56,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt09",
            x:96.2,
            y:222.65,
            width:56,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt10",
            x:190.7-12,
            y:222.65,
            width:56,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt11",
            x:252.959-9,
            y:222.65,
            width:56,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt12",
            x:320+12,
            y:222.65,
            width:56,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt13",
            x:398-2,
            y:222.65,
            width:56,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt14",
            x:132-8,
            y:271.35,
            width:84,
            height:84,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt15",
            x:48.3-4,
            y:362.1,
            width:76,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt16",
            x:201.5-4,
         y:362.1,
            width:76,
            height:17,
            size:11,
            textAlign:"center"},
		{compId:"ID_txt17",
            x:352.4-4,
            y:362.1,
            width:76,
            height:17,
            size:11,
            textAlign:"center"},
		];
            
		
	var slide_1_graphics = [{}]	

    var slide_object = {images:slide_images,
	    graphics:slide_1_graphics,
        texts:slide_texts};

    return {templateType:template_type,
        slideObject:slide_object};

}

loadScript("../../../common/scripts/swfobject.js", registerSWF);
