
loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	 var template_type = "MULTI_BAR";
	var commonTexts = [];
	var commonImages = [];

	var slide_1_type = "MULTI_BUTTON";	
	var slide_1_buttonStyle = {normalSkinImage:"../../../common/images/text_button_gradient.png",
						overSkinImage:"../../../common/images/text_button_gradient_selected.png",
						normalTextStyle:'#FFFFFF',
						overTextStyle:'#006699',
						cornorRadius:5,
						selected:0};
	var slide_1_buttons = [{compId:"ID_btn01",/*  Button */
						x:0.15,
						y:306.9,
						width:62,
						height:23,
						size:12,
						textAlign:"center"},

						{compId:"ID_btn02",
						x:164.15,
						y:309,
						width:62,
						height:23,
						size:12,
						textAlign:"center"},

						{compId:"ID_btn03",
						x:230.65,
						y:309,
						width:62,
						height:23,
						size:12,
						textAlign:"center"},

						{compId:"ID_btn04",
						x:298.15,
						y:309,
						width:62,
						height:23,
						size:12,
						textAlign:"center"},

						{compId:"ID_btn05",
						x:98.1,
						y:357.9,
						width:62,
						height:23,
						size:12,
						textAlign:"center"},
						
						{compId:"ID_btn06",
						x:164.15,
						y:357.9,
						width:62,
						height:23,
						size:12,
						textAlign:"center"},

						{compId:"ID_btn07",
						x:230.65,
						y:357.9,
						width:62,
						height:23,
						size:12,
						textAlign:"center"},
						
						{compId:"ID_btn08",
						x:298.15,
						y:357.9,
						width:62,
						height:23,
						size:12,
						textAlign:"center"},
							
						{compId:"ID_btn09",/* End Button */
						x:375.6,
						y:357.9,
						width:62,
						height:23,
						size:12,
						textAlign:"center"}];
	var slide_1_buttonObject = {style:slide_1_buttonStyle,
								buttons:slide_1_buttons};
	var slide_1_commonTexts = [];
	var slide_texts = [{compId:"ID_title",
							x:5,
							y:2, 
							width:460,
							height:17,
							size:16,
							textAlign:"center"},
						{compId:"ID_txt01",/* SYN ACK*/
							x:74.15+2,
							y:309.95+2,
							width:86.5,
							height:17,
							size:12,
							color:"#5a5e61",
							textAlign:"center"},

							{compId:"ID_txt02",/* FIN ACK*/
							x:19.15,
							y:361.95+1,
							width:86.5,
							height:17,
							size:12,
							color:"#5a5e61",
							textAlign:"center"},

							{compId:"ID_txt03",/* A*/
							x:110,
							y:35.15,
							width:86.5,
							height:17,
							size:12,
							textAlign:"center"},
							
							{compId:"ID_txt04",/* B*/
							x:296,
							y:35.15,
							width:86.5,
							height:17,
							size:12,
							textAlign:"center"}]

	var common_images = [{name:"5.2.1.3.png",
							x:120,
							y:53.15, 
							width:236.95,
							height:43,
							type:""},
							];
	

	var slide_reset_type = "DESCRIPTION";/* Reset button */
	var slide_reset_images = [];							
	var slide_reset_textboxs = [];							
	var slide_reset_texts = [];	
	var slide_graphics = [{x:183,
							y:95,
							x1:183,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"},
							{x:287,
							y:95,
							x1:287,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"}];						

	var slide_reset_object = {templateType:slide_reset_type,
							x:0,
							y:0,
							images:slide_reset_images,
							textboxs:slide_reset_textboxs,
							texts:slide_reset_texts,
							graphics:slide_graphics
							};

	
	var slide_1_1_type = "DESCRIPTION";
	var slide_1_1_images = [{name:"1.png",
							x:157,
							y:106.60,  
							width:30,
							height:30,
							type:""}]				
					
	var slide_1_1_textboxs = [];							
	var slide_1_1_texts = [{compId:"ID_s1_txt02",
							x:50,
							y:112.60, 
							width:115.50,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s1_txt03",
							x:77.85,
							y:133.10, 
							width:114.45,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s1_txt04",
							x:250-4,
							y:123, 
							width:123.55,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s1_txt05",
							x:43.75,
							y:247.60, 
							width:400,
							height:17,
							size:11,
							textAlign:"center"}];
	var slide_graphics = [{	x:284,
							y:128,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:185,
							type:"arrow"},
							{x:183,
							y:95,
							x1:183,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"},
							{x:287,
							y:95,
							x1:287,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"}];
	var slide_1_1_object = {templateType:slide_1_1_type,
							x:0,
							y:0,
							images:slide_1_1_images,
							textboxs:slide_1_1_textboxs,
							texts:slide_1_1_texts,
							graphics:slide_graphics};
							
								
	var slide_2_type = "DESCRIPTION";
	var slide_2_images = [{name:"1.png",
							x:157,
							y:106.60,  
							width:30,
							height:30,
							type:""},
							{name:"2.png",
							x:288,
							y:148, 
							width:30,
							height:30,
							type:""},
							];							
	var slide_2_textboxs = [];							
	var slide_2_texts = [{compId:"ID_s2_txt02",
							x:50,
							y:112.60, 
							width:115.50,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s2_txt03",
							x:77.85,
							y:133.10, 
							width:114.45,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s2_txt05",
							x:120.5-30,
							y:165.10, 
							width:123.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s2_txt04",
							x:250-4+40,
							y:121, 
							width:80.55,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s2_txt06",
							x:324,
							y:154, 
							width:123.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s2_txt08",
							x:304,
							y:174, 
							width:123.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s2_txt09",
							x:43.75,
							y:247.60, 
							width:400,
							height:17,
							size:11,
							textAlign:"center"}];
	var slide_graphics = [{	x:284,
							y:128,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:185,
							type:"arrow"},
							{x:186,
							y:173,
							length:101,
							thickness:3,
							color:"#F68026",
							rotation:-7,
							type:"arrow"},
							{x:183,
							y:95,
							x1:183,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"},
							{x:287,
							y:95,
							x1:287,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"}];			
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							textboxs:slide_2_textboxs,
							texts:slide_2_texts,
							graphics:slide_graphics};
	var slide_3_type = "DESCRIPTION";
	var slide_3_images = [{name:"1.png",
							x:157,
							y:106.60,  
							width:30,
							height:30,
							type:""},
							{name:"2.png",
							x:288,
							y:148, 
							width:30,
							height:30,
							type:""},
							{name:"3.png",
							x:158,
							y:195, 
							width:30,
							height:30,
							type:""},];							
	var slide_3_textboxs = [];							
	var slide_3_texts = [{compId:"ID_s3_txt02",
							x:50,
							y:112.60, 
							width:115.50,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s3_txt03",
							x:77.85,
							y:133.10, 
							width:114.45,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s2_txt05",
							x:90.5,
							y:165.10, 
							width:110.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s3_txt06",
							x:112,
							y:200, 
							width:76.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s3_txt07",
							x:20,
							y:218, 
							width:168,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s3_txt08",
							x:250-4,
							y:123, 
							width:123.55,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s3_txt09",
							x:324,
							y:154, 
							width:123.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s3_txt11",
							x:304,
							y:179, 
							width:123.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s3_txt12",
							x:60,
							y:260, 
							width:378,
							height:17,
							size:11,
							textAlign:"center"},
							];
	var slide_graphics = [{	x:284,
							y:128,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:185,
							type:"arrow"},
							{x:186,
							y:173,
							length:101,
							thickness:3,
							color:"#F68026",
							rotation:-7,
							type:"arrow"},
							{x:284,
							y:215,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:185,
							type:"arrow"},
							{x:183,
							y:95,
							x1:183,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"},
							{x:287,
							y:95,
							x1:287,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"}];			
	var slide_3_object = {templateType:slide_3_type,
							x:0,
							y:0,
							images:slide_3_images,
							textboxs:slide_3_textboxs,
							texts:slide_3_texts,
							graphics:slide_graphics};
	var slide_4_type = "DESCRIPTION";
	var slide_4_images = [{name:"1.png",
							x:156,
							y:106.60,  
							width:30,
							height:30,
							type:""}];							
	var slide_4_textboxs = [];							
	var slide_4_texts = [{compId:"ID_s4_txt02",
							x:50,
							y:112.60, 
							width:115.50,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s4_txt03",
							x:300.2+2,
							y:123, 
							width:70,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s4_txt04",
							x:180,
							y:247.6, 
							width:180,
							height:17,
							size:11,
							textAlign:"left"},
							];
	var slide_graphics = [{	x:284,
							y:128,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:185,
							type:"arrow"},
							{x:183,
							y:95,
							x1:183,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"},
							{x:287,
							y:95,
							x1:287,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"}];			
	var slide_4_object = {templateType:slide_4_type,
							x:0,
							y:0,
							images:slide_4_images,
							textboxs:slide_4_textboxs,
							texts:slide_4_texts,
							graphics:slide_graphics};
							
	var slide_5_type = "DESCRIPTION";
	var slide_5_images = [{name:"1.png",
							x:156,
							y:106.60,  
							width:30,
							height:30,
							type:""},	
							{name:"2.png",
							x:286,
							y:149,  
							width:30,
							height:30,
							type:""}];							
	var slide_5_textboxs = [];							
	var slide_5_texts = [{compId:"ID_s5_txt02",
							x:50,
							y:112.60, 
							width:115.50,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s5_txt03",
							x:120.5,
							y:165.10, 
							width:76.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s5_txt04",
							x:300.2+2,
							y:123, 
							width:70,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s5_txt05",
							x:320+2,
							y:152, 
							width:123.55,
							height:17,
							size:11,
							textAlign:"left"}];
	var slide_graphics = [{	x:284,
							y:128,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:185,
							type:"arrow"},
							{x:186,
							y:173,
							length:101,
							thickness:3,
							color:"#F68026",
							rotation:-7,
							type:"arrow"},
							{x:183,
							y:95,
							x1:183,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"},
							{x:287,
							y:95,
							x1:287,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"}];			
	var slide_5_object = {templateType:slide_5_type,
							x:0,
							y:0,
							images:slide_5_images,
							textboxs:slide_5_textboxs,
							texts:slide_5_texts,
							graphics:slide_graphics};
							
	var slide_6_type = "DESCRIPTION";
	var slide_6_images = [{name:"1.png",
							x:156,
							y:106.60,  
							width:30,
							height:30,
							type:""},	
							{name:"2.png",
							x:286,
							y:148,  
							width:30,
							height:30,
							type:""},	
							{name:"3.png",
							x:286,
							y:173,  
							width:30,
							height:30,
							type:""},]						
	var slide_6_textboxs = [];							
	var slide_6_texts = [{compId:"ID_s6_txt02",
							x:50,
							y:112.60, 
							width:115.50,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s6_txt03",
							x:120.5,
							y:165.10, 
							width:76.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s6_txt04",
							x:300.2+2,
							y:123, 
							width:70,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s6_txt06",
							x:320+2,
							y:152, 
							width:123.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s6_txt08",
							x:320+2,
							y:177, 
							width:80,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s6_txt04",
							x:126,
							y:185+7, 
							width:80,
							height:17,
							size:11,
							textAlign:"left"},];
	var slide_graphics = [{	x:284,
							y:128,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:185,
							type:"arrow"},
							{x:186,
							y:173,
							length:101,
							thickness:3,
							color:"#F68026",
							rotation:-7,
							type:"arrow"},
							{x:186,
							y:200,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:-7,
							type:"arrow"},
							{x:183,
							y:95,
							x1:183,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"},
							{x:287,
							y:95,
							x1:287,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"}
							];			
	var slide_6_object = {templateType:slide_6_type,
							x:0,
							y:0,
							images:slide_6_images,
							textboxs:slide_6_textboxs,
							texts:slide_6_texts,
							graphics:slide_graphics};
	var slide_7_type = "DESCRIPTION";
	var slide_7_images = [{name:"1.png",
							x:156,
							y:106.60,  
							width:30,
							height:30,
							type:""},	
							{name:"2.png",
							x:286,
							y:148,  
							width:30,
							height:30,
							type:""},	
							{name:"3.png",
							x:286,
							y:173,  
							width:30,
							height:30,
							type:""},
							{name:"4.png",
							x:156,
							y:209,  
							width:30,
							height:30,
							type:""}];							
	var slide_7_textboxs = [];							
	var slide_7_texts = [{compId:"ID_s7_txt02",
							x:50,
							y:112.60, 
							width:115.50,
							height:17,
							size:11,
							textAlign:"right"},
							{compId:"ID_s7_txt03",
							x:120.5,
							y:165.10, 
							width:76.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s7_txt04",
							x:300.2+2,
							y:123, 
							width:70,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s7_txt06",
							x:320+2,
							y:152, 
							width:123.55,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s7_txt10",
							x:322,
							y:177, 
							width:80,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s7_txt07",
							x:126,
							y:185+7, 
							width:80,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s7_txt08",
							x:118-3,
							y:214, 
							width:75,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s7_txt12",
							x:302.2,
							y:220.6, 
							width:80,
							height:17,
							size:11,
							textAlign:"left"},
							{compId:"ID_s7_txt13",
							x:43.75,
							y:257.60, 
							width:400,
							height:17,
							size:11,
							textAlign:"center"}];
	var slide_graphics = [{	x:284,
							y:128,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:185,
							type:"arrow"},
							{x:186,
							y:173,
							length:101,
							thickness:3,
							color:"#F68026",
							rotation:-7,
							type:"arrow"},
							{x:186,
							y:200,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:-7,
							type:"arrow"},
							{x:284,
							y:228,
							length:101,
							thickness:3,
							color:"#5FBC21",
							rotation:185,
							type:"arrow"},
							{x:183,
							y:95,
							x1:183,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"},
							{x:287,
							y:95,
							x1:287,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"}];			
	var slide_7_object = {templateType:slide_7_type,
							x:0,
							y:0,
							images:slide_7_images,
							textboxs:slide_7_textboxs,
							texts:slide_7_texts,
							graphics:slide_graphics};
	var slide_8_type = "DESCRIPTION";
	var slide_8_images = [{name:"end.png",
							x:189.10,
							y:170.25, 
							width:90,
							height:110,
							type:""}];							
	var slide_8_textboxs = [];							
	var slide_8_texts = [{compId:"ID_s8_txt01",
							x:195.10,
							y:140.25,  
							width:91.45,
							height:17,
							size:11,
							textAlign:"center"},];
	var slide_graphics = [{x:183,
							y:95,
							x1:183,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"},
							{x:287,
							y:95,
							x1:287,
							y1:240, 
							lineWidth:2,
							type:"line",
							color:"#666263"}];			
	var slide_8_object = {templateType:slide_8_type,
							x:0,
							y:0,
							images:slide_8_images,
							textboxs:slide_8_textboxs,
							texts:slide_8_texts,
							graphics:slide_graphics};
										
	var slide_1_slides = [slide_reset_object,slide_1_1_object,slide_2_object,slide_3_object,slide_4_object,slide_5_object,slide_6_object,slide_7_object,slide_8_object];
	
	var slide_graphics = [{	x:66,/* shapes for multibutton Background color 1 */
							y:301, 
							width:303.95,
							height:39,
							color:"#cdeaf8",
							stroke:"#918f90",
							thickness:2,
							corner:0},

							{x:12,/* shapes for multibutton Background color 1 */
							y:350, 
							width:358.75,
							height:39,
							color:"#cdeaf8",
							stroke:"#918f90",
							thickness:2,
							corner:0}]	

	var slide_1_object = {templateType:slide_1_type,
									 x:0,
									 y:0,
							textObject:slide_texts,
							images:common_images,
							buttonObject:slide_1_buttonObject,
							slideObject:slide_1_slides,graphics:slide_graphics};
	
var slide_11_type = "IMAGE";
	var slide_11_images = [{name:"5_2_1_7_A.png",
							x:1,
							y:28, 
							width:453.90, 
							height:221.30,
							scrollable:"YES",
							divId:"commonImageText",
							type:""},
							{name:"box.jpg",
							x:36.75,
							y:271.9, 
							width:367, 
							height:80,
							type:"STD"}];								
	var slide_11_texts = [{compId:"ID_s2_title",
							x:5,
							y:2, 
							width:430,
							height:17,
							size:16,
							textAlign:"center"},
							{compId:"ID_s2_text01",
							x:57,
							y:291, 
							width:350,
							height:17,
							size:11,
							color:"#000000",
							textAlign:"left"},
							];							
	var slide_11_object = {templateType:slide_11_type,
							x:0,
							y:0,
							images:slide_11_images,
							texts:slide_11_texts};
	var slide_12_type = "IMAGE";
	var slide_12_images = [{name:"5_2_1_7_B.png",
							x:1,
							y:28, 
							width:453.90, 
							height:221.30,
							scrollable:"YES",
							divId:"commonImageText",
							type:""},
							{name:"box.jpg",
						x:36.75,
							y:271.9, 
							width:367, 
							height:80,
							type:"STD"}];								
	var slide_12_texts = [{compId:"ID_s3_title",
							x:5,
							y:2, 
							width:430,
							height:17,
							size:16,
							textAlign:"center"},
							{compId:"ID_s3_text01",
							x:57,
							y:291, 
							width:350,
							height:17,
							size:11,
							color:"#000000",
							textAlign:"left"},
							
							];							
	var slide_12_object = {templateType:slide_12_type,
							x:0,
							y:0,
							images:slide_12_images,
							texts:slide_12_texts};
	
	var slides = [slide_1_object,slide_11_object,slide_12_object];
											
	//var slides = [slide_5_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			images:commonImages,
			slideObject:slides
			};
	
}