loadScript("../../../common/scripts/swfobject.js", registerSWF);
//loadScript("../../../common/scripts/templates/slide/MultiBarSlide.js");

function registerSWF(){
	swfobject.registerObject("flashobject", "9.0.0", "../../../common/libs/expressInstall.swf");
}


var STAGE_WIDTH = 470;
var STAGE_HEIGHT = 400;

function getData()
{
	var template_type = "MULTI_BAR";
	var commonTexts = [];
	
	var slide_1_type = "IMAGE";
	var slide_1_images = [	 {name:"6_2_1_4_A.png",
							 x:-5,
							 y:128, 
							 width:452,
							 height:273,
							 size:10,
							 type:""},
						{name:"6_2_1_4_B.png",
							 x:85,
        					 y:3,
        					 width:272.15,
        					 height:106.1,
							 type:""}
							 ];								
	var slide_1_texts = [  {compId:"ID_s1_txt01",
							bodyText:"<b>PC1</b>",
							x:105.95,
							y:71.5, 
							width:26.9,
							height:17,
							size:11,
							color:"white",
							textAlign:"center"},
							{compId:"ID_s1_txt02",
							bodyText:".10",
							x:143.3,
							y:78.9, 
							width:20.25,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt03",
							bodyText:"<b>192.168.10.0/24</b>",
							x:185.7,
							y:109.75, 
							width:87.7,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt04",
							bodyText:".20",
							x:261.25,
							y:11.9, 
							width:17,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt05",
							bodyText:"<b>R1</b>",
							x:335.75,
							y:90.9, 
							width:19.1,
							height:17,
							color:"white",
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt06",
							bodyText:".1",
							x:276.7,
							y:79.8, 
							width:65.2,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_s1_txt07",
							bodyText:"<b>PC2</b>",
							x:222.95,
							y:12.55, 
							width:26.9,
							height:17,
							size:11,
							color:"white",
							textAlign:"center"},
							{compId:"ID_txt20",
							bodyText:"<table width='400' border='0' cellpadding='0' cellspacing='0' style='font-family:'Courier New !important'><tr><td colspan='5'>C:\\Users\\PC1&gt;<b style='font-weight:bold'> netstat -r</b></td></tr><tr><td colspan='5'><span style='color:#fefefe'>.</span></td></tr><tr><td colspan='5'>IPv4 Route Table</td></tr><tr><td colspan='5'>===================================================================================</td></tr><tr><td colspan='5'>Active Routes:</td></tr><tr><td width='107'><div align='right'>Network Destination</div></td><td width='91'><div align='right'>Netmask</div></td><td width='73'><div align='right'>Gateway</div></td><td width='80'><div align='right'>Interface</div></td><td width='35'><div align='right'>Metric</div></td></tr><tr><td><div align='right'>0.0.0.0&nbsp;</div></td><td><div align='right'>0.0.0.0</div></td><td><div align='right'>192.168.10.1</div></td><td><div align='right'>192.168.10.10</div></td><td><div align='right'>25</div></td></tr><tr><td><div align='right'>127.0.0.0&nbsp;</div></td><td><div align='right'>255.0.0.0</div></td><td><div align='right'>On-link</div></td><td><div align='right'>127.0.0.1</div></td><td><div align='right'>306</div></td></tr><tr><td><div align='right'>127.0.0.1&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>127.0.0.1</div></td><td><div align='right'>306</div></td></tr><tr><td><div align='right'>127.255.255.255&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>127.0.0.1</div></td><td><div align='right'>306</div></td></tr><tr><td style='color:#F26200; font-weight:bold;'><div align='right'>192.168.10.0&nbsp;</div></td><td style='color:#F26200; font-weight:bold;'><div align='right' style='color:#F26200; font-weight:bold;'>255.255.255.0</div></td><td style='color:#F26200; font-weight:bold;'><div align='right'>On-link</div></td><td style='color:#F26200; font-weight:bold;'><div align='right'>192.168.10.10</div></td><td style='color:#F26200; font-weight:bold;'><div align='right'>281</div></td></tr><tr><td><div align='right'>192.168.10.10&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>192.168.10.10</div></td><td><div align='right'>281</div></td></tr><tr><td><div align='right'>192.168.10.255&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>192.168.10.10</div></td><td><div align='right'>281</div></td></tr><tr><td><div align='right'>224.0.0.0&nbsp;</div></td><td><div align='right'>240.0.0.0</div></td><td><div align='right'>On-link</div></td><td><div align='right'>127.0.0.1</div></td><td><div align='right'>306</div></td></tr><tr><td><div align='right'>224.0.0.0&nbsp;</div></td><td><div align='right'>240.0.0.0</div></td><td><div align='right'>On-link</div></td><td><div align='right'>192.168.10.10</div></td><td><div align='right'>281</div></td></tr><tr><td><div align='right'>255.255.255.255&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>127.0.0.1</div></td><td><div align='right'>306</div></td></tr><tr><td><div align='right'>255.255.255.255&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>192.168.10.10</div></td><td><div align='right'>281</div></td></tr><tr><td colspan='5'>===================================================================================</td></tr><tr><td colspan='5'></td></tr></table>",
							x:21,
							y:140, 
							width:432,
							height:263,
							size:10,
							scroll:"yes",
							color:"#3c3d3f",
							textAlign:"left",
							},
							{compId:"ID_s1_txt01",
							x:7,
							y:152, 
							width:104,
							height:17,
							size:10,
							textAlign:"center"},
							{compId:"ID_s1_txt01",
							x:9,
							y:365, 
							width:104,
							height:17,
							size:10,
							textAlign:"center"}
							];							
	var slide_1_object = {templateType:slide_1_type,
							x:0,
							y:0,
							images:slide_1_images,
							texts:slide_1_texts};
							
	var slide_2_type = "IMAGE";
	var slide_2_images = [{name:"6_2_1_4_A.png",
							 x:-5,
							 y:128, 
							 width:452,
							 height:273,
							 size:10,
							 type:""},
						{name:"6_2_1_4_C.png",
							 x:4,
        					 y:33,
        					 width:435.55,
        					 height:66.65,
							 type:""}
							 ];								
	var slide_2_texts = [{compId:"ID_s2_txt01",
							bodyText:"<b>PC1</b>",
							x:25.95,
							y:49.55, 
							width:26.9,
							height:17,
							size:11,
							color:"white",
							textAlign:"center"},
							{compId:"ID_s2_txt02",
							bodyText:".10",
							x:60.3,
							y:55.9, 
							width:20.25,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_s2_txt03",
							bodyText:"<b>192.168.10.0/24</b>",
							x:108.7,
							y:87.75, 
							width:87.7,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_s2_txt04",
							bodyText:".1",
							x:241.25,
							y:55.9, 
							width:17,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_s2_txt05",
							bodyText:"<b>R1</b>",
							x:271.75,
							y:68.9, 
							width:19.1,
							height:17,
							color:"white",
							size:11,
							textAlign:"center"},
							{compId:"ID_s2_txt06",
							bodyText:"<b>10.10.10.10</b>",
							x:368.7,
							y:73.8, 
							width:65.2,
							height:17,
							size:11,
							textAlign:"center"},
							{compId:"ID_txt20",
							bodyText:"<table width='400' border='0' cellpadding='0' cellspacing='0' style='font-family:'Courier New !important'><tr><td colspan='5'>C:\\Users\\PC1&gt;<b style='font-weight:bold'> netstat -r</b></td></tr><tr><td colspan='5'><span style='color:#fefefe'>.</span></td></tr><tr><td colspan='5'>IPv4 Route Table</td></tr><tr><td colspan='5'>===================================================================================</td></tr><tr><td colspan='5'>Active Routes:</td></tr><tr><td width='107'><div align='right'>Network Destination</div></td><td width='91'><div align='right'>Netmask</div></td><td width='73'><div align='right'>Gateway</div></td><td width='80'><div align='right'>Interface</div></td><td width='35'><div align='right'>Metric</div></td></tr><tr><td style='color:#F26200; font-weight:bold;'><div align='right'>0.0.0.0&nbsp;</div></td><td style='color:#F26200; font-weight:bold;'><div align='right'>0.0.0.0</div></td><td style='color:#F26200; font-weight:bold;'><div align='right'>192.168.10.1</div></td><td style='color:#F26200; font-weight:bold;'><div align='right'>192.168.10.10</div></td><td style='color:#F26200; font-weight:bold;'><div align='right'>25</div></td></tr><tr><td><div align='right'>127.0.0.0&nbsp;</div></td><td><div align='right'>255.0.0.0</div></td><td><div align='right'>On-link</div></td><td><div align='right'>127.0.0.1</div></td><td><div align='right'>306</div></td></tr><tr><td><div align='right'>127.0.0.1&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>127.0.0.1</div></td><td><div align='right'>306</div></td></tr><tr><td><div align='right'>127.255.255.255&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>127.0.0.1</div></td><td><div align='right'>306</div></td></tr><tr><td><div align='right'>192.168.10.0&nbsp;</div></td><td ><div align='right' >255.255.255.0</div></td><td ><div align='right'>On-link</div></td><td ><div align='right'>192.168.10.10</div></td><td ><div align='right'>281</div></td></tr><tr><td><div align='right'>192.168.10.10&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>192.168.10.10</div></td><td><div align='right'>281</div></td></tr><tr><td><div align='right'>192.168.10.255&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>192.168.10.10</div></td><td><div align='right'>281</div></td></tr><tr><td><div align='right'>224.0.0.0&nbsp;</div></td><td><div align='right'>240.0.0.0</div></td><td><div align='right'>On-link</div></td><td><div align='right'>127.0.0.1</div></td><td><div align='right'>306</div></td></tr><tr><td><div align='right'>224.0.0.0&nbsp;</div></td><td><div align='right'>240.0.0.0</div></td><td><div align='right'>On-link</div></td><td><div align='right'>192.168.10.10</div></td><td><div align='right'>281</div></td></tr><tr><td><div align='right'>255.255.255.255&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>127.0.0.1</div></td><td><div align='right'>306</div></td></tr><tr><td><div align='right'>255.255.255.255&nbsp;</div></td><td><div align='right'>255.255.255.255</div></td><td><div align='right'>On-link</div></td><td><div align='right'>192.168.10.10</div></td><td><div align='right'>281</div></td></tr><tr><td colspan='5'>===================================================================================</td></tr><tr><td colspan='5'></td></tr></table>",
							x:21,
							y:140, 
							width:432,
							height:263,
							size:10,
							scroll:"yes",
							color:"#3c3d3f",
							textAlign:"left",
							},
							{compId:"ID_s1_txt01",
							x:7,
							y:152, 
							width:104,
							height:17,
							size:10,
							textAlign:"center"},
							{compId:"ID_s1_txt01",
							x:9,
							y:365, 
							width:104,
							height:17,
							size:10,
							textAlign:"center"}
							];							
	var slide_2_object = {templateType:slide_2_type,
							x:0,
							y:0,
							images:slide_2_images,
							texts:slide_2_texts};
							
	var slides = [slide_1_object,slide_2_object];
						
	return {templateType:template_type,
			textObject:commonTexts,
			slideObject:slides};
	
}
